In [1]:
import time

start_time = time.time()
print(f"Start time recorded: {start_time}")

Start time recorded: 1762782117.6968791

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [2]:
do = False # @param{type:"boolean"}
if do:
    %pip install torchinfo -qq
    %pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
    %pip install starfile -qq
    %pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

In [3]:
if do:
    !git clone https://github.com/phonchi/CryoParticleSegment.git

In [4]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

In [5]:
if do:
    #%git clone https://github.com/netw0rkf10w/CRF.git
    %cd CryoParticleSegment/Modeling/CRF_main
    !python setup.py clean --all
    !rm -rf build/
    !python setup.py build_ext --inplace --force
    !python setup.py install

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [6]:
if do:
    %pip install pycuda==2024.1
    %pip install "numpy<2.0"
    %pip install mrcfile -qq

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [7]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C_CSN_D_float_u_output/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C_CSN_D_float_u_output/results_100_CRF/10017/unet_eb5_dice_CRF" # @param {type:"string"}

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
rm: cannot remove '/content/sample_data': No such file or directory

In [10]:
IMAGE_DIR = "/content/image_dir"

In [11]:
%cd /content/

/content

### ✅ Packages Handling

In [12]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [13]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [14]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 8
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [15]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [16]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [17]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:86: UserWarning:
Access to the secret `HF_TOKEN` has not been granted on this notebook.
You will not be requested again.
Please restart the session if you want to be prompted again.
  warnings.warn(

config.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/122M [00:00<?, ?B/s]

In [18]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [19]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [20]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [21]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [22]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [23]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:27<00:00,  3.07it/s]

In [24]:
processed_micrographs.shape

(84, 3840, 3840)

In [25]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [26]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [27]:
del model
torch.cuda.empty_cache()

In [28]:
model = model_post

In [29]:
RESULT_DIR

'/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C_CSN_D_float_u_output/results_100_CRF/10017/unet_eb5_dice_CRF'

In [30]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [31]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [32]:
!cp {RESULT_DIR}/label_images.npy .

In [33]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [34]:
label_images.shape

(84, 3840, 3840)

In [35]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [36]:
!cp {RESULT_DIR}/best_config.txt .

In [37]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [38]:
radius = RADIUS

In [39]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [40]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

547 465
546 486
508 391
394 385
410 384
497 413
334 328
475 434
530 444
596 515
516 446
501 467
550 480
501 474
584 492
558 488
514 452
520 457
485 432
576 505
562 475
523 430
531 462
533 408
481 376
477 368
494 388
533 420
527 413
548 492
550 487
477 363
534 453
557 490
543 467
547 464
536 460
551 458
558 499
535 452
427 389
543 453
558 492
398 383
240 239
416 385
299 294
499 482
565 490
504 418
541 464
535 454
568 508
503 483
564 510
486 443
531 454
584 527
457 369
482 394
440 430
499 440
478 457
450 426
463 435
443 421
397 380
482 432
430 380
458 401
479 431
114 114
461 416
531 490
434 408
521 461
430 410
474 428
470 436
316 311
457 394
473 415
429 370
457 403

In [41]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [42]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [43]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [44]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1508,3951,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,427,3950,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1238,3948,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3524,3951,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,586,3949,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
36078,1809,151,00398@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36079,316,148,00399@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36080,1979,175,00400@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36081,2856,156,00401@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36082,3602,160,00402@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [45]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [46]:
cv_list

[[(1380, 3823),
  (299, 3822),
  (1110, 3820),
  (3396, 3823),
  (458, 3821),
  (119, 3819),
  (2410, 3816),
  (3584, 3816),
  (625, 3814),
  (3040, 3807),
  (1186, 3803),
  (2823, 3785),
  (2697, 3791),
  (1564, 3780),
  (3692, 3768),
  (1699, 3766),
  (2949, 3760),
  (3195, 3743),
  (975, 3730),
  (1294, 3730),
  (468, 3684),
  (33, 3679),
  (1791, 3681),
  (366, 3672),
  (3702, 3662),
  (1134, 3655),
  (1534, 3655),
  (2765, 3658),
  (1438, 3665),
  (3260, 3649),
  (3052, 3649),
  (3791, 3620),
  (1714, 3564),
  (3692, 3570),
  (1001, 3594),
  (754, 3565),
  (3092, 3551),
  (1128, 3537),
  (3227, 3547),
  (3507, 3500),
  (41, 3530),
  (876, 3504),
  (675, 3518),
  (3588, 3527),
  (2364, 3489),
  (3002, 3497),
  (138, 3485),
  (1581, 3476),
  (3413, 3454),
  (2777, 3457),
  (603, 3469),
  (3775, 3457),
  (3374, 3437),
  (1776, 3457),
  (764, 3430),
  (1478, 3435),
  (2268, 3421),
  (3568, 3408),
  (999, 3413),
  (16, 3409),
  (2931, 3403),
  (2643, 3411),
  (516, 3407),
  (2807, 3359),
  (885, 3367),
  (673, 3349),
  (209, 3358),
  (3047, 3351),
  (1604, 3332),
  (2143, 3333),
  (3373, 3320),
  (322, 3321),
  (2662, 3303),
  (3809, 3269),
  (3620, 3288),
  (1072, 3299),
  (895, 3281),
  (1876, 3265),
  (3066, 3256),
  (3169, 3228),
  (2809, 3220),
  (3332, 3184),
  (1221, 3195),
  (327, 3210),
  (2599, 3207),
  (502, 3200),
  (3545, 3192),
  (2262, 3228),
  (2695, 3185),
  (3745, 3190),
  (631, 3214),
  (2148, 3150),
  (3157, 3135),
  (1598, 3122),
  (792, 3124),
  (234, 3136),
  (3822, 3087),
  (1271, 3108),
  (3556, 3091),
  (607, 3087),
  (3447, 3090),
  (497, 3067),
  (2305, 3081),
  (3645, 3040),
  (3368, 3030),
  (3822, 2996),
  (1346, 2998),
  (371, 3007),
  (25, 2953),
  (2316, 2966),
  (3285, 2947),
  (2081, 2943),
  (3822, 2924),
  (2910, 2942),
  (2789, 2935),
  (268, 2929),
  (3754, 2907),
  (890, 2915),
  (3385, 2862),
  (1140, 2880),
  (3029, 2874),
  (90, 2852),
  (3772, 2809),
  (2510, 2827),
  (2698, 2822),
  (3600, 2808),
  (869, 2773),
  (532, 2740),
  (2775, 2735),
  (3395, 2744),
  (3249, 2743),
  (1038, 2750),
  (2871, 2748),
  (3036, 2730),
  (2589, 2742),
  (2506, 2730),
  (3693, 2706),
  (1989, 2685),
  (481, 2673),
  (2954, 2658),
  (692, 2656),
  (3413, 2652),
  (3600, 2647),
  (3240, 2646),
  (1741, 2647),
  (970, 2634),
  (2170, 2620),
  (592, 2612),
  (30, 2603),
  (254, 2597),
  (1642, 2603),
  (2672, 2591),
  (2521, 2573),
  (1331, 2566),
  (1545, 2590),
  (3237, 2548),
  (2828, 2541),
  (122, 2541),
  (2336, 2547),
  (3803, 2530),
  (3347, 2544),
  (3700, 2513),
  (1192, 2516),
  (2602, 2510),
  (2260, 2515),
  (1886, 2476),
  (744, 2461),
  (1626, 2473),
  (3543, 2460),
  (1713, 2457),
  (2360, 2446),
  (1337, 2431),
  (2934, 2458),
  (3455, 2423),
  (3160, 2414),
  (1561, 2406),
  (3740, 2389),
  (597, 2402),
  (3042, 2379),
  (327, 2375),
  (3623, 2371),
  (1405, 2361),
  (2838, 2351),
  (2041, 2348),
  (1731, 2344),
  (1918, 2346),
  (2650, 2310),
  (193, 2333),
  (1379, 2289),
  (1088, 2312),
  (1590, 2306),
  (3100, 2313),
  (3597, 2260),
  (3269, 2301),
  (2354, 2289),
  (77, 2255),
  (361, 2278),
  (592, 2267),
  (508, 2234),
  (1997, 2238),
  (2749, 2222),
  (3766, 2271),
  (3821, 2211),
  (3250, 2189),
  (946, 2158),
  (2462, 2190),
  (440, 2178),
  (774, 2170),
  (1599, 2179),
  (3003, 2186),
  (642, 2126),
  (3582, 2113),
  (2345, 2110),
  (2535, 2106),
  (3397, 2118),
  (3487, 2107),
  (54, 2125),
  (1054, 2086),
  (2156, 2079),
  (21, 2044),
  (2013, 2046),
  (916, 2045),
  (2569, 2035),
  (3581, 2031),
  (690, 2034),
  (322, 2025),
  (3779, 2039),
  (426, 2009),
  (1330, 2009),
  (221, 2005),
  (3190, 2014),
  (1537, 1976),
  (1451, 2005),
  (828, 1969),
  (1726, 1972),
  (2734, 1951),
  (2897, 1903),
  (1102, 1923),
  (914, 1914),
  (1307, 1905),
  (3216, 1888),
  (3442, 1919),
  (3655, 1872),
  (1489, 1835),
  (670, 1859),
  (96, 1861),
  (1515, 1821),
  (2755, 1843),
  (2136, 1812),
  (3820, 1817),
  (3004, 1810),
  (1395, 1805),
  (2854, 1749),
  (488, 1763),
  (2120, 1729),
  (3087, 1734),
  (48, 1714),
  (1584, 1729),
  (2792, 1693),
  (3425, 1685),
  (1407, 1677),
  (3619, 1682),
  (1936, 1672),
  (3309, 1654),
  (2230, 1657),
  (1854, 1647),
  (568, 1651),
  (2713, 1625),
  (2986, 1619),
  (341, 1598),
  (3249, 1561),
  (3819, 1535),
  (3090, 1551),
  (156, 1557),
  (456, 1543),
  (1894, 1543),
  (2698, 1532),
  (967, 1519),
  (3710, 1499),
  (3612, 1505),
  (3166, 1500),
  (1460, 1480),
  (877, 1474),
  (206, 1472),
  (762, 1452),
  (425, 1451),
  (3740, 1416),
  (2577, 1395),
  (1188, 1407),
  (496, 1394),
  (2216, 1398),
  (1401, 1388),
  (2696, 1389),
  (2318, 1385),
  (3662, 1383),
  (1093, 1377),
  (3617, 1324),
  (787, 1328),
  (2448, 1316),
  (1264, 1324),
  (3294, 1350),
  (1962, 1325),
  (3176, 1306),
  (1059, 1290),
  (1448, 1286),
  (2830, 1279),
  (3528, 1272),
  (408, 1268),
  (913, 1253),
  (2609, 1254),
  (3015, 1244),
  (58, 1257),
  (284, 1266),
  (1349, 1242),
  (2282, 1221),
  (1828, 1204),
  (1240, 1213),
  (567, 1215),
  (2740, 1176),
  (1435, 1185),
  (2152, 1180),
  (2521, 1184),
  (3821, 1147),
  (2071, 1152),
  (1522, 1150),
  (3320, 1166),
  (3483, 1136),
  (2995, 1106),
  (1799, 1082),
  (1311, 1076),
  (866, 1114),
  (2649, 1067),
  (2432, 1065),
  (1063, 1067),
  (1934, 1034),
  (2819, 1018),
  (1095, 983),
  (746, 985),
  (2246, 975),
  (66, 973),
  (3417, 957),
  (477, 962),
  (3065, 943),
  (2051, 946),
  (3818, 911),
  (1849, 916),
  (1748, 915),
  (3145, 896),
  (1094, 882),
  (2408, 861),
  (961, 866),
  (3434, 848),
  (2712, 825),
  (450, 832),
  (3067, 819),
  (3790, 818),
  (1174, 811),
  (352, 794),
  (2957, 792),
  (3365, 790),
  (1844, 770),
  (2482, 782),
  (1297, 812),
  (1654, 765),
  (32, 752),
  (1955, 743),
  (1414, 736),
  (2980, 713),
  (1611, 692),
  (3701, 705),
  (749, 680),
  (168, 672),
  (22, 663),
  (1143, 653),
  (538, 647),
  (1804, 640),
  (1031, 631),
  (1517, 617),
  (2483, 611),
  (1336, 614),
  (3156, 591),
  (628, 584),
  (40, 560),
  (458, 560),
  (3792, 549),
  (2296, 554),
  (2616, 533),
  (1629, 571),
  (2385, 538),
  (126, 522),
  (3360, 504),
  (978, 496),
  (1449, 520),
  (1726, 519),
  (3622, 510),
  (3172, 500),
  (595, 505),
  (1345, 516),
  (1138, 506),
  (1041, 485),
  (2938, 508),
  (2836, 498),
  (253, 455),
  (480, 479),
  (3299, 463),
  (83, 461),
  (3689, 456),
  (3809, 449),
  (3445, 450),
  (2211, 453),
  (3116, 421),
  (1442, 424),
  (347, 417),
  (2290, 402),
  (1227, 369),
  (19, 353),
  (3239, 343),
  (1583, 355),
  (1409, 342),
  (1506, 332),
  (954, 326),
  (861, 313),
  (178, 287),
  (1640, 295),
  (3766, 291),
  (1884, 274),
  (3534, 270),
  (3184, 261),
  (301, 254),
  (1318, 239),
  (724, 234),
  (885, 215),
  (17, 190),
  (1133, 211),
  (2468, 197),
  (2341, 223),
  (783, 169),
  (3269, 145),
  (2019, 139),
  (3119, 103),
  (2566, 136),
  (168, 117),
  (2180, 109),
  (600, 106),
  (2718, 94),
  (340, 110),
  (711, 95),
  (3157, 67),
  (1799, 94),
  (3492, 86),
  (2821, 84),
  (2933, 60),
  (3218, 52),
  (1874, 35),
  (128, 26),
  (3095, 24),
  (2999, 70),
  (2078, 26),
  (1195, 88),
  (806, 40),
  (207, 21),
  (3799, 22),
  (2309, 24),
  (3462, 17),
  (2692, 21)],
 [(363, 3821),
  (3407, 3818),
  (2432, 3820),
  (3118, 3819),
  (276, 3817),
  (730, 3816),
  (1459, 3810),
  (3010, 3809),
  (3766, 3807),
  (1743, 3804),
  (959, 3798),
  (2588, 3803),
  (2166, 3792),
  (1185, 3794),
  (3225, 3789),
  (3605, 3787),
  (1890, 3786),
  (2785, 3786),
  (2262, 3776),
  (505, 3767),
  (850, 3771),
  (1311, 3754),
  (1581, 3751),
  (3158, 3741),
  (729, 3729),
  (3558, 3700),
  (354, 3725),
  (2674, 3720),
  (2428, 3727),
  (3590, 3687),
  (131, 3767),
  (1127, 3700),
  (40, 3706),
  (970, 3704),
  (1395, 3699),
  (2954, 3692),
  (3405, 3672),
  (3435, 3649),
  (2761, 3664),
  (2384, 3649),
  (857, 3629),
  (401, 3645),
  (561, 3636),
  (2586, 3620),
  (3334, 3608),
  (3203, 3602),
  (1079, 3596),
  (1483, 3591),
  (1340, 3589),
  (245, 3615),
  (2251, 3569),
  (1641, 3565),
  (2876, 3585),
  (874, 3550),
  (761, 3535),
  (3041, 3537),
  (2157, 3529),
  (1743, 3522),
  (163, 3477),
  (486, 3480),
  (2543, 3471),
  (2462, 3460),
  (3612, 3453),
  (293, 3442),
  (2328, 3444),
  (2759, 3432),
  (1526, 3429),
  (3511, 3421),
  (3304, 3420),
  (1785, 3427),
  (2953, 3418),
  (64, 3406),
  (965, 3397),
  (3175, 3406),
  (1674, 3379),
  (185, 3363),
  (1124, 3348),
  (1224, 3346),
  (3693, 3345),
  (1851, 3341),
  (2654, 3326),
  (1557, 3331),
  (1320, 3348),
  (965, 3297),
  (3442, 3284),
  (2574, 3271),
  (43, 3253),
  (162, 3268),
  (3588, 3278),
  (1238, 3242),
  (3780, 3243),
  (3034, 3258),
  (1663, 3251),
  (799, 3217),
  (2165, 3233),
  (2867, 3221),
  (606, 3222),
  (2708, 3189),
  (1059, 3172),
  (1830, 3204),
  (1307, 3166),
  (945, 3171),
  (3611, 3166),
  (1416, 3125),
  (2629, 3129),
  (1011, 3101),
  (3338, 3096),
  (3259, 3103),
  (3442, 3088),
  (1904, 3091),
  (1122, 3089),
  (573, 3082),
  (313, 3090),
  (2728, 3080),
  (2120, 3061),
  (895, 3020),
  (1219, 3022),
  (1456, 3020),
  (2263, 3019),
  (227, 3014),
  (2010, 3000),
  (3724, 2970),
  (794, 2963),
  (3273, 2946),
  (1809, 2941),
  (1563, 2923),
  (2428, 2931),
  (2080, 2928),
  (1898, 2906),
  (2311, 2904),
  (3819, 2876),
  (3579, 2884),
  (2937, 2845),
  (2174, 2868),
  (3178, 2852),
  (1367, 2846),
  (859, 2858),
  (240, 2848),
  (3653, 2831),
  (3396, 2814),
  (2106, 2812),
  (2348, 2811),
  (1585, 2808),
  (539, 2840),
  (1463, 2793),
  (51, 2796),
  (3813, 2770),
  (2480, 2770),
  (674, 2738),
  (3231, 2757),
  (1784, 2734),
  (2591, 2770),
  (421, 2740),
  (1958, 2744),
  (3725, 2703),
  (516, 2705),
  (1599, 2701),
  (2357, 2685),
  (1702, 2693),
  (3278, 2676),
  (3070, 2653),
  (241, 2661),
  (777, 2635),
  (1786, 2644),
  (3668, 2632),
  (1248, 2634),
  (1581, 2604),
  (476, 2610),
  (1889, 2597),
  (3496, 2578),
  (3366, 2586),
  (2512, 2581),
  (2016, 2572),
  (2734, 2565),
  (1447, 2556),
  (3245, 2551),
  (3632, 2546),
  (1806, 2521),
  (1336, 2519),
  (2899, 2506),
  (148, 2498),
  (2438, 2499),
  (1074, 2491),
  (1654, 2485),
  (1419, 2473),
  (829, 2471),
  (2753, 2465),
  (3112, 2456),
  (3416, 2454),
  (41, 2440),
  (1311, 2423),
  (3681, 2422),
  (3552, 2445),
  (3036, 2407),
  (2419, 2399),
  (1856, 2407),
  (1633, 2369),
  (346, 2358),
  (905, 2361),
  (1733, 2338),
  (2651, 2345),
  (3505, 2319),
  (521, 2354),
  (804, 2321),
  (3648, 2323),
  (3699, 2283),
  (1129, 2320),
  (256, 2306),
  (2495, 2288),
  (2378, 2281),
  (589, 2273),
  (3060, 2261),
  (2901, 2265),
  (375, 2263),
  (1644, 2254),
  (706, 2260),
  (19, 2253),
  (1315, 2256),
  (482, 2229),
  (988, 2261),
  (1839, 2227),
  (2939, 2181),
  (128, 2208),
  (1454, 2168),
  (3334, 2151),
  (873, 2149),
  (3433, 2161),
  (366, 2138),
  (85, 2135),
  (2052, 2110),
  (2395, 2122),
  (3542, 2100),
  (968, 2112),
  (3649, 2113),
  (706, 2071),
  (1643, 2054),
  (2855, 2056),
  (435, 2060),
  (3781, 2045),
  (530, 2043),
  (45, 2027),
  (2078, 2013),
  (1528, 2011),
  (604, 2004),
  (328, 1980),
  (3577, 1952),
  (1768, 1957),
  (2319, 1959),
  (2749, 1951),
  (3796, 1927),
  (1153, 1920),
  (3181, 1925),
  (1471, 1929),
  (1357, 1901),
  (3269, 1904),
  (2494, 1912),
  (1897, 1897),
  (1422, 1845),
  (811, 1881),
  (53, 1841),
  (2839, 1841),
  (3563, 1820),
  (2067, 1805),
  (2605, 1840),
  (1632, 1851),
  (3528, 1805),
  (1979, 1821),
  (948, 1853),
  (1814, 1812),
  (2157, 1804),
  (2739, 1802),
  (419, 1784),
  (3315, 1756),
  (2288, 1761),
  (2836, 1740),
  (2681, 1709),
  (3171, 1717),
  (1953, 1718),
  (758, 1745),
  (3006, 1749),
  (2168, 1695),
  (1762, 1691),
  (3456, 1665),
  (2325, 1655),
  (1967, 1637),
  (80, 1657),
  (1613, 1628),
  (1020, 1630),
  (1411, 1608),
  (3211, 1590),
  (1720, 1578),
  (2265, 1574),
  (526, 1555),
  (1464, 1553),
  (3564, 1522),
  (71, 1545),
  (2113, 1524),
  (2516, 1538),
  (3354, 1548),
  (2767, 1509),
  (152, 1500),
  (3474, 1491),
  (418, 1485),
  (1313, 1477),
  (1727, 1467),
  (2201, 1445),
  (3007, 1439),
  (3670, 1440),
  (3550, 1441),
  (847, 1421),
  (237, 1397),
  (117, 1382),
  (2074, 1387),
  (1002, 1434),
  (3347, 1358),
  (760, 1367),
  (3747, 1390),
  (2476, 1355),
  (1080, 1381),
  (1552, 1376),
  (2820, 1382),
  (17, 1336),
  (1655, 1359),
  (2232, 1323),
  (2557, 1295),
  (3359, 1293),
  (1784, 1324),
  (911, 1279),
  (378, 1286),
  (2949, 1254),
  (2107, 1260),
  (2391, 1246),
  (1512, 1231),
  (3574, 1222),
  (3749, 1221),
  (1360, 1202),
  (1884, 1204),
  (106, 1227),
  (1058, 1200),
  (1734, 1171),
  (240, 1208),
  (1466, 1159),
  (3630, 1153),
  (468, 1131),
  (666, 1134),
  (2220, 1121),
  (1653, 1114),
  (806, 1117),
  (3088, 1113),
  (3768, 1099),
  (2776, 1096),
  (2696, 1101),
  (1163, 1066),
  (555, 1064),
  (45, 1056),
  (2088, 1044),
  (367, 1049),
  (2586, 1041),
  (1387, 1019),
  (1902, 1019),
  (2952, 1018),
  (3727, 1005),
  (317, 942),
  (732, 973),
  (3028, 958),
  (3386, 939),
  (190, 948),
  (2608, 944),
  (1607, 984),
  (342, 916),
  (2497, 908),
  (2355, 934),
  (623, 954),
  (17, 903),
  (1361, 919),
  (3755, 927),
  (1831, 899),
  (3123, 891),
  (1110, 853),
  (2902, 878),
  (3040, 847),
  (1585, 857),
  (2795, 834),
  (3328, 812),
  (680, 828),
  (945, 768),
  (3746, 773),
  (1639, 765),
  (2428, 758),
  (807, 758),
  (3418, 751),
  (1394, 748),
  (3202, 752),
  (567, 731),
  (2268, 720),
  (1301, 713),
  (2128, 717),
  (3580, 700),
  (1729, 683),
  (694, 686),
  (1443, 656),
  (1201, 659),
  (863, 663),
  (2389, 649),
  (1614, 610),
  (2157, 597),
  (3509, 627),
  (2976, 572),
  (1926, 586),
  (1018, 587),
  (3820, 550),
  (2275, 537),
  (569, 536),
  (2387, 543),
  (3364, 522),
  (2659, 562),
  (773, 531),
  (1282, 514),
  (1765, 529),
  (1862, 510),
  (3164, 491),
  (3269, 497),
  (1063, 484),
  (593, 460),
  (1167, 480),
  (3481, 473),
  (373, 467),
  (2455, 445),
  (3381, 432),
  (1324, 416),
  (3081, 411),
  (272, 402),
  (900, 408),
  (1856, 393),
  (3170, 373),
  (1013, 393),
  (2026, 377),
  (483, 374),
  (3159, 342),
  (2640, 374),
  (3456, 370),
  (1131, 344),
  (135, 343),
  (2267, 347),
  (3667, 313),
  (1475, 298),
  (349, 304),
  (1635, 309),
  (3059, 292),
  (1957, 272),
  (55, 253),
  (3509, 247),
  (2180, 254),
  (3735, 222),
  (285, 228),
  (433, 209),
  (650, 188),
  (2867, 216),
  (53, 179),
  (3175, 167),
  (3375, 168),
  (2106, 158),
  (780, 159),
  (1356, 143),
  (2778, 154),
  (874, 154),
  (1530, 141),
  (1185, 126),
  (692, 107),
  (525, 92),
  (77, 72),
  (3282, 67),
  (3567, 37),
  (3682, 44),
  (2204, 56),
  (1750, 41),
  (854, 41),
  (2562, 50),
  (2084, 47),
  (1988, 39),
  (3798, 30),
  (587, 20),
  (440, 77),
  (2978, 17),
  (1359, 18),
  (2732, 16)],
 [(2108, 3822),
  (2897, 3819),
  (1709, 3819),
  (2572, 3816),
  (3429, 3816),
  (929, 3809),
  (1025, 3812),
  (2353, 3804),
  (492, 3798),
  (3286, 3801),
  (3558, 3796),
  (1512, 3783),
  (1272, 3804),
  (3697, 3784),
  (3387, 3738),
  (912, 3736),
  (776, 3740),
  (1126, 3734),
  (20, 3728),
  (1348, 3721),
  (2919, 3726),
  (2308, 3724),
  (3378, 3680),
  (1437, 3690),
  (3738, 3690),
  (698, 3689),
  (3303, 3674),
  (1225, 3663),
  (2415, 3663),
  (3380, 3627),
  (3556, 3632),
  (1538, 3654),
  (1808, 3651),
  (1386, 3621),
  (54, 3617),
  (158, 3582),
  (376, 3578),
  (3812, 3566),
  (3095, 3558),
  (3381, 3556),
  (2115, 3549),
  (91, 3540),
  (1684, 3536),
  (228, 3523),
  (845, 3481),
  (3219, 3460),
  (2924, 3461),
  (1692, 3419),
  (2338, 3422),
  (3711, 3412),
  (2662, 3397),
  (331, 3372),
  (3222, 3340),
  (905, 3368),
  (2105, 3397),
  (3124, 3356),
  (1534, 3334),
  (611, 3346),
  (2192, 3319),
  (3625, 3288),
  (223, 3289),
  (451, 3312),
  (3819, 3261),
  (2551, 3291),
  (1701, 3254),
  (529, 3251),
  (2117, 3240),
  (101, 3242),
  (3562, 3272),
  (1927, 3243),
  (1320, 3230),
  (954, 3223),
  (2003, 3198),
  (3620, 3189),
  (1161, 3179),
  (1790, 3156),
  (3756, 3153),
  (3238, 3143),
  (399, 3139),
  (3464, 3132),
  (516, 3136),
  (2627, 3130),
  (2130, 3121),
  (3670, 3116),
  (2476, 3094),
  (1898, 3090),
  (3785, 3071),
  (1230, 3072),
  (2335, 3066),
  (585, 3058),
  (388, 3029),
  (3477, 3018),
  (3688, 3017),
  (860, 3029),
  (2632, 3006),
  (2781, 2996),
  (1254, 2980),
  (1828, 2974),
  (1946, 3001),
  (70, 3007),
  (2186, 2958),
  (907, 2903),
  (2325, 2905),
  (1565, 2857),
  (2178, 2833),
  (1739, 2820),
  (1153, 2813),
  (3434, 2811),
  (186, 2780),
  (2087, 2775),
  (2621, 2781),
  (466, 2762),
  (3669, 2751),
  (994, 2735),
  (3775, 2722),
  (3292, 2728),
  (2687, 2713),
  (2358, 2712),
  (379, 2733),
  (2541, 2738),
  (1260, 2721),
  (3552, 2712),
  (1953, 2694),
  (1743, 2682),
  (25, 2671),
  (155, 2658),
  (541, 2668),
  (631, 2669),
  (372, 2631),
  (2203, 2620),
  (2847, 2621),
  (1458, 2609),
  (2084, 2582),
  (3341, 2567),
  (2496, 2588),
  (1001, 2611),
  (66, 2576),
  (3553, 2570),
  (3104, 2528),
  (897, 2514),
  (1154, 2524),
  (399, 2490),
  (212, 2492),
  (1730, 2478),
  (3674, 2495),
  (3257, 2442),
  (1865, 2447),
  (1457, 2473),
  (91, 2437),
  (3365, 2410),
  (3709, 2382),
  (3598, 2370),
  (1941, 2358),
  (2083, 2351),
  (339, 2351),
  (1044, 2328),
  (3026, 2334),
  (457, 2331),
  (3245, 2339),
  (491, 2290),
  (3410, 2324),
  (1624, 2287),
  (2750, 2285),
  (1372, 2307),
  (2926, 2296),
  (323, 2256),
  (34, 2261),
  (2730, 2252),
  (172, 2267),
  (2215, 2233),
  (2054, 2254),
  (3475, 2248),
  (760, 2240),
  (1822, 2238),
  (350, 2189),
  (77, 2191),
  (1981, 2164),
  (3588, 2185),
  (2905, 2172),
  (1203, 2158),
  (1684, 2143),
  (1462, 2124),
  (3025, 2134),
  (2508, 2136),
  (911, 2099),
  (176, 2109),
  (474, 2099),
  (3584, 2089),
  (822, 2129),
  (1615, 2087),
  (2811, 2069),
  (3812, 2064),
  (1201, 2067),
  (2952, 2050),
  (2304, 2023),
  (1085, 2019),
  (3088, 2003),
  (1676, 2011),
  (703, 2004),
  (1529, 1994),
  (3632, 1993),
  (2262, 1955),
  (2054, 1951),
  (1335, 1918),
  (2176, 1904),
  (94, 1923),
  (3024, 1908),
  (3354, 1885),
  (186, 1868),
  (517, 1886),
  (3264, 1833),
  (2040, 1816),
  (860, 1801),
  (2516, 1788),
  (279, 1786),
  (2944, 1806),
  (982, 1781),
  (413, 1757),
  (121, 1753),
  (18, 1736),
  (3510, 1700),
  (600, 1703),
  (2888, 1693),
  (3064, 1673),
  (3662, 1681),
  (496, 1659),
  (1227, 1683),
  (183, 1636),
  (107, 1656),
  (20, 1632),
  (1085, 1645),
  (1586, 1621),
  (2577, 1607),
  (3265, 1605),
  (3168, 1587),
  (1739, 1578),
  (3540, 1580),
  (815, 1583),
  (2966, 1568),
  (2821, 1572),
  (1311, 1593),
  (3669, 1541),
  (935, 1529),
  (95, 1525),
  (637, 1510),
  (3343, 1513),
  (1650, 1499),
  (1441, 1534),
  (2796, 1458),
  (27, 1392),
  (665, 1394),
  (1776, 1377),
  (1917, 1376),
  (875, 1372),
  (1366, 1395),
  (752, 1361),
  (2580, 1355),
  (3534, 1388),
  (241, 1350),
  (1656, 1374),
  (2278, 1310),
  (2454, 1320),
  (1545, 1302),
  (3749, 1299),
  (3819, 1258),
  (65, 1254),
  (3329, 1286),
  (846, 1255),
  (1729, 1270),
  (1113, 1258),
  (1361, 1215),
  (1232, 1198),
  (298, 1194),
  (2046, 1212),
  (187, 1180),
  (577, 1159),
  (3609, 1137),
  (3752, 1130),
  (1427, 1129),
  (3223, 1130),
  (1278, 1096),
  (3697, 1072),
  (2059, 1071),
  (3354, 1052),
  (1858, 1042),
  (1155, 1034),
  (2952, 1038),
  (20, 1016),
  (663, 1030),
  (927, 1006),
  (272, 1011),
  (3483, 996),
  (1686, 1002),
  (452, 946),
  (2434, 946),
  (3668, 938),
  (1906, 946),
  (577, 941),
  (3758, 951),
  (1593, 930),
  (2636, 955),
  (82, 935),
  (1509, 914),
  (1025, 894),
  (145, 921),
  (3382, 876),
  (3228, 867),
  (2416, 851),
  (2528, 848),
  (3148, 823),
  (2749, 860),
  (911, 794),
  (34, 810),
  (1800, 766),
  (2712, 767),
  (3266, 769),
  (1051, 772),
  (1230, 771),
  (3787, 754),
  (2383, 743),
  (852, 743),
  (2150, 737),
  (2806, 750),
  (137, 711),
  (944, 717),
  (3396, 714),
  (3250, 696),
  (2548, 683),
  (2665, 693),
  (2863, 684),
  (2273, 672),
  (2020, 676),
  (1152, 649),
  (3659, 630),
  (1364, 606),
  (2421, 630),
  (3321, 601),
  (554, 612),
  (2541, 595),
  (1364, 570),
  (960, 609),
  (3824, 563),
  (2750, 583),
  (2632, 581),
  (322, 542),

In [47]:
tp_config

(0.25, 0.4)

In [48]:
import trackpy as tp

In [49]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [50]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

623
567
640
363
398
558
316
475
613
639
569
471
591
488
667
600
548
559
522
594
609
643
608
706
603
611
618
663
634
572
576
642
592
581
587
619
584
646
575
620
423
640
573
366
208
422
266
476
626
590
609
594
574
500
577
490
587
616
625
594
397
511
445
430
434
421
381
499
450
491
500
102
469
483
422
538
405
483
442
263
486
509
453
467

In [51]:
tp_list

[array([[2929.71390189,   60.76990781],
        [1418.77521497,   69.86751301],
        [1342.05100107,   95.60723408],
        ...,
        [1906.82538059, 3736.80558839],
        [2704.03325138, 3776.28601535],
        [3689.22004982, 3766.13391711]]),
 array([[  86.59908458,   81.48326773],
        [2400.17702122,  104.31348539],
        [ 695.51869692,  101.20935428],
        ...,
        [ 472.96732669, 3762.87410323],
        [3602.47165835, 3785.15549632],
        [2777.96963538, 3782.90040237]]),
 array([[ 276.86832646,   58.34740997],
        [ 921.79226291,   81.89700757],
        [2960.76965004,  100.37591383],
        ...,
        [1962.08441239, 3764.59499364],
        [2748.72353708, 3781.14441503],
        [3689.08646824, 3779.60503222]]),
 array([[2921.38900981,   60.71218544],
        [2248.51561813,   52.10861417],
        [1422.41085729,   84.58189328],
        [1748.28810123,   96.03705257],
        [2670.0897219 ,  175.74089361],
        [ 165.93165567,  159.78967329],
        [1065.25342945,  135.57128768],
        [3013.59621397,  147.53057354],
        [1465.58154152,  186.87122541],
        [2403.98545125,  230.9379416 ],
        [3447.89507211,  172.85050149],
        [ 620.63493144,  212.12073759],
        [3212.57429696,  189.66063918],
        [3315.85203941,  194.31144383],
        [1777.29716166,  199.07733443],
        [2719.16514791,  276.95183373],
        [ 380.0841226 ,  247.49190842],
        [1248.48647372,  315.11557393],
        [1578.54864063,  253.14163125],
        [3588.80788137,  304.2739061 ],
        [ 736.62189755,  329.23825031],
        [2973.60633051,  281.72256165],
        [ 821.44408202,  279.67681217],
        [2528.50273264,  357.36863994],
        [2359.87198287,  294.7450597 ],
        [2415.6753412 ,  354.1863819 ],
        [2837.3622389 ,  310.97660424],
        [1369.9049614 ,  371.99363823],
        [1754.00919389,  348.42554589],
        [1850.89481224,  367.03928982],
        [3333.69975055,  334.21515979],
        [1074.89348876,  366.00980499],
        [1954.69847189,  397.80787159],
        [3481.57309223,  350.39734443],
        [ 953.00484699,  436.75369608],
        [1490.33785721,  444.68687027],
        [1203.47091742,  420.4281273 ],
        [2273.64614736,  395.02749971],
        [2832.60727518,  443.10310464],
        [ 753.00221157,  456.63685292],
        [1865.42940729,  504.46524055],
        [2153.99976303,  490.58100903],
        [ 308.09808896,  448.52951125],
        [2508.02971114,  504.9722569 ],
        [2630.63288538,  473.42218387],
        [2388.0679864 ,  444.21923615],
        [1573.61161467,  537.11212043],
        [2225.16780708,  555.89514753],
        [ 945.32784138,  498.79990015],
        [2055.68848589,  503.96470456],
        [2924.59697511,  543.05541715],
        [3209.34244567,  562.05113832],
        [2321.10343944,  551.73701403],
        [ 778.08585478,  594.18219016],
        [3276.02364155,  570.70947163],
        [ 128.71914007,  619.79165514],
        [1529.38769965,  578.61579366],
        [3074.492493  ,  571.45101366],
        [3728.75238753,  633.01832812],
        [ 619.2009409 ,  581.25171028],
        [1363.72052431,  589.190619  ],
        [1978.54849685,  637.53687694],
        [2623.57375038,  603.19983645],
        [2758.24974643,  683.53943981],
        [2498.1918812 ,  623.47755929],
        [3201.64337787,  691.86278112],
        [ 898.3696477 ,  652.71103884],
        [1263.69755959,  673.27527279],
        [  89.28921794,  654.26134881],
        [1050.84261382,  674.28078939],
        [ 406.45599224,  662.68902706],
        [ 303.34258675,  670.6033123 ],
        [ 748.37241177,  675.33089017],
        [3247.85357129,  734.46904372],
        [1804.55738751,  707.53077332],
        [3626.62418272,  722.26170343],
        [1554.04990042,  723.2828317 ],
        [1317.75426884,  726.02927205],
        [3407.64111484,  769.18315873],
        [2755.04079284,  742.12778244],
        [2391.87226314,  778.1464583 ],
        [2301.48279595,  790.64991191],
        [1731.82250679,  839.38323632],
        [1287.22769768,  827.72931411],
        [1593.81089102,  845.78158617],
        [2199.28843074,  855.10884491],
        [3462.44301843,  857.32731834],
        [2825.57771578,  875.94797948],
        [1973.19395519,  851.72847682],
        [2891.11228199,  900.06641343],
        [2520.08880849,  901.37409752],
        [ 120.83634048,  884.51770518],
        [1576.08663452,  993.41508784],
        [ 774.3557009 ,  947.29787895],
        [1807.16060488, 1008.52951801],
        [ 282.51542168,  960.29591411],
        [ 498.7793977 ,  979.33134258],
        [2228.52989981, 1001.69682203],
        [2368.60889069, 1000.95017833],
        [1995.29079368,  987.74737884],
        [3698.4362794 ,  970.71206614],
        [2642.8089892 ,  986.66825858],
        [2833.32701775,  990.04757374],
        [3318.02533933, 1006.65438331],
        [ 161.75085192, 1030.05424205],
        [ 928.5066268 ,  994.66039542],
        [ 347.65723431, 1075.77682403],
        [2233.34077589, 1093.79697779],
        [ 462.64395083, 1114.04988858],
        [1699.73711473, 1095.78046361],
        [1224.70604157, 1095.30354761],
        [1111.21979051, 1150.56978626],
        [  62.12179513, 1163.54322749],
        [1875.17286652, 1108.21881838],
        [3682.25292076, 1131.95416371],
        [1547.75094174, 1161.45121878],
        [ 885.23244092, 1151.07425105],
        [3045.91291951, 1155.15601279],
        [3488.97547701, 1219.37600861],
        [1229.26006669, 1209.38455239],
        [1051.13019258, 1233.68712871],
        [2443.89582927, 1281.76634784],
        [2061.78669931, 1265.8630763 ],
        [2621.15006415, 1283.7623606 ],
        [2938.50227879, 1243.77448114],
        [  95.10852493, 1252.19775556],
        [1329.379515  , 1262.48544256],
        [1987.1796744 , 1303.36713482],
        [ 892.64628175, 1320.12170015],
        [3583.59168778, 1261.21437809],
        [3689.13423165, 1329.1398277 ],
        [2323.87741565, 1303.97037103],
        [2203.73580319, 1354.09161393],
        [ 422.67235406, 1325.66646458],
        [1546.57506516, 1328.26437916],
        [3347.54517271, 1318.62959778],
        [1218.51380633, 1369.39032924],
        [2559.42094686, 1371.01957941],
        [ 988.69481671, 1370.61521539],
        [1451.15144903, 1366.52510074],
        [ 858.17412754, 1399.58368354],
        [ 192.7468352 , 1390.21272944],
        [2314.06779308, 1439.12256505],
        [3642.06024303, 1452.10961835],
        [1117.26605543, 1402.73452671],
        [3225.23269537, 1407.78724083],
        [2918.26609913, 1481.59073642],
        [3140.68984632, 1482.26404904],
        [2221.04256027, 1442.30167003],
        [3554.05816962, 1468.98023061],
        [ 101.46532201, 1480.73708422],
        [1295.82412644, 1476.44224064],
        [ 348.21349973, 1513.7673595 ],
        [ 881.31536611, 1512.99992482],
        [2361.84019328, 1525.07586207],
        [2966.77592851, 1569.35730098],
        [ 289.63937577, 1563.35863956],
        [1774.85066364, 1546.04869047],
        [1456.05115704, 1587.36406995],
        [3330.73701617, 1592.12505814],
        [1279.36791332, 1594.10015895],
        [1091.8634759 , 1583.06539504],
        [ 680.99791793, 1632.16092652],
        [3494.08733361, 1614.53050634],
        [ 574.10844477, 1582.95643891],
        [2082.52604606, 1621.5464807 ],
        [3391.77309193, 1699.82799735],
        [2705.7205691 , 1654.08016116],
        [2949.28962569, 1635.53990199],
        [ 288.94315707, 1664.97549299],
        [3699.80819507, 1688.4942182 ],
        [ 148.55362427, 1669.03247046],
        [1789.99286291, 1715.75640427],
        [ 737.69158351, 1683.15030554],
        [1716.37261514, 1714.87541082],
        [2224.45635564, 1768.41911747],
        [1135.87171889, 1710.75113535],
        [1410.68492488, 1707.08540839],
        [ 294.27135186, 1799.96043335],
        [3639.7831864 , 1789.43691759],
        [1303.69767071, 1737.40212189],
        [ 514.32953368, 1807.57449183],
        [2475.1259379 , 1774.52914695],
        [2773.81228682, 1822.37315247],
        [2959.20463439, 1780.46144403],
        [3394.33525283, 1804.00737808],
        [3482.61001781, 1840.42714505],
        [2288.40704711, 1838.23384348],
        [1160.36226476, 1830.53552888],
        [1476.54619915, 1844.49268692],
        [2120.73885007, 1810.18775384],
        [ 450.40418004, 1841.10129186],
        [ 623.01969494, 1847.465471  ],
        [ 249.41885303, 1842.38385218],
        [1905.77936867, 1865.93226752],
        [3777.57412715, 1894.49303753],
        [2172.53713034, 1947.72438514],
        [3490.96556763, 1910.65658964],
        [2759.52381543, 1918.9458806 ],
        [3594.43603807, 1900.2734939 ],
        [ 369.35210759, 1961.55956314],
        [2380.10676576, 1939.03817912],
        [2973.03605136, 1987.3755633 ],
        [ 177.27249735, 1983.36518678],
        [ 704.92968996, 1983.28751095],
        [ 907.05348408, 2072.96030791],
        [1326.67330729, 2019.01664476],
        [3290.35434539, 2071.69903436],
        [2740.80542584, 2028.34437773],
        [2553.07867503, 2052.4723469 ],
        [2133.54668251, 2045.98752337],
        [1035.03077935, 2107.79971194],
        [1872.08685215, 2116.36910018],
        [1586.94439685, 2093.6492485 ],
        [3457.978789  , 2128.1634398 ],
        [2425.13213782, 2116.98963962],
        [1959.17872226, 2156.69478152],
        [1261.33233562, 2140.27375813],
        [ 188.58226885, 2123.19856498],
        [3119.94637989, 2160.3517319 ],
        [3626.38869387, 2201.16626396],
        [1148.71215246, 2159.93002651],
        [2564.96420985, 2155.34687988],
        [ 751.37856908, 2234.40187069],
        [3515.79943486, 2170.95220345],
        [1611.90392501, 2212.28565489],
        [ 858.19965434, 2212.39082019],
        [1025.24706014, 2283.41899775],
        [ 435.70183621, 2241.05723262],
        [2236.12672291, 2267.32757004],
        [3017.22631791, 2285.18672032],
        [2374.34373325, 2287.69636539],
        [1330.77141023, 2266.94844976],
        [2467.5065463 , 2318.27326179],
        [3786.36096672, 2345.73843892],
        [2067.81313392, 2317.4440953 ],
        [ 702.51547852, 2355.0007083 ],
        [2929.82962745, 2368.35041777],
        [1778.30700993, 2370.73451284],
        [3709.83154523, 2403.02396567],
        [1147.57364173, 2402.54970299],
        [3434.42304936, 2402.24855464],
        [1354.93947876, 2416.17490825],
        [2615.70828957, 2438.70948219],
        [ 167.21028813, 2420.26957418],
        [ 827.03900275, 2442.89045046],
        [ 467.35124438, 2514.23201187],
        [3028.07281863, 2464.59858032],
        [1258.82571656, 2499.42128509],
        [1719.66364949, 2561.0065293 ],
        [ 361.24877527, 2564.41406282],
        [ 222.42170042, 2569.9375834 ],
        [2754.78555696, 2539.60541948],
        [1127.988726  , 2541.91847158],
        [2884.54320896, 2530.71892481],
        [2338.88273335, 2544.84730905],
        [ 575.89844642, 2561.44839634],
        [2577.16665129, 2552.58801173],
        [2044.44829711, 2573.3801405 ],
        [ 470.38599881, 2619.4374053 ],
        [ 689.66019609, 2594.72266136],
        [1458.83897714, 2640.87795428],
        [ 343.36352463, 2638.98186631],
        [1719.19965179, 2634.30498467],
        [1863.29125818, 2661.36460174],
        [ 209.34802284, 2662.4479594 ],
        [2520.58608793, 2696.27759949],
        [1291.15901334, 2709.6979134 ],
        [1998.35448714, 2741.90793706],
        [3242.94573532, 2687.88219065],
        [2997.82247936, 2730.35708742],
        [1807.23509259, 2752.54716854],
        [2449.26661355, 2777.92302789],
        [1039.50347745, 2729.55718076],
        [3459.39913116, 2756.92126814],
        [ 512.69197025, 2734.17158116],
        [1485.33658753, 2757.86191177],
        [ 426.49767201, 2802.63487708],
        [2614.01981117, 2807.94608764],
        [1615.51281951, 2776.41399348],
        [ 215.48013852, 2783.95102872],
        [1832.84907368, 2838.13988293],
        [3468.37973829, 2874.10766268],
        [1499.80618043, 2881.90211607],
        [3682.78409137, 2900.48155198],
        [2102.86825569, 2926.36735283],
        [2641.94834206, 2890.63376963],
        [ 583.48488792, 2890.40554262],
        [ 944.12945237, 2865.25096965],
        [2589.32726474, 2886.54449635],
        [1362.02275109, 2993.12639497],
        [1663.10986584, 2964.85782068],
        [2750.24376068, 3014.396764  ],
        [1745.86817513, 2999.98019104],
        [3075.25692524, 2978.78866921],
        [1940.14552606, 3059.13894562],
        [3564.03901761, 3048.89520881],
        [1473.44100477, 3079.23198468],
        [ 307.90254698, 3066.02943004],
        [ 792.29954424, 3138.30677353],
        [3205.23692822, 3068.73252854],
        [2830.57539141, 3093.50303258],
        [ 997.31086647, 3087.3522055 ],
        [2634.11369611, 3090.99257361],
        [2439.80619674, 3094.94878563],
        [3424.78504141, 3113.76408894],
        [2927.44871795, 3148.01137459],
        [ 152.46222574, 3127.15825262],
        [ 683.14457195, 3156.98814737],
        [1133.91662763, 3179.3754879 ],
        [3128.42443933, 3235.42056038],
        [1882.92132537, 3234.28660201],
        [1381.75102994, 3205.461242  ],
        [1237.91568961, 3184.1394791 ],
        [3239.91636253, 3199.07565389],
        [ 857.27830668, 3215.73047417],
        [2797.00695236, 3250.67596101],
        [1982.48404276, 3225.9486103 ],
        [ 443.55121499, 3292.21740557],
        [2985.46394788, 3249.50046008],
        [2159.69546691, 3345.46311412],
        [2545.84612437, 3313.08402621],
        [ 285.15608525, 3335.39975077],
        [3166.32667347, 3336.1070439 ],
        [1617.4597399 , 3320.64521331],
        [ 535.00618512, 3372.54262669],
        [2831.5019209 , 3398.38071563],
        [1078.48848253, 3435.94797647],
        [2462.38478094, 3439.1055342 ],
        [2617.1047648 , 3444.78982393],
        [ 963.15877271, 3458.95263628],
        [1254.89496685, 3463.24487643],
        [1618.96588348, 3533.97677173],
        [1849.25174372, 3493.58181194],
        [ 678.61718388, 3542.00910916],
        [ 813.35256592, 3548.66763538],
        [ 334.86607644, 3519.26996696],
        [2958.19160258, 3538.25511105],
        [2567.77157066, 3586.07840862],
        [ 918.30785863, 3614.18852391],
        [1120.91296871, 3581.72188729],
        [2245.78714867, 3544.82824407],
        [2661.44794521, 3594.9109589 ],
        [1744.63084273, 3588.04372253],
        [1186.12521279, 3607.56177626],
        [2091.48994379, 3671.98344785],
        [1317.07847052, 3604.50420041],
        [1881.06187625, 3616.172818  ],
        [ 155.45381821, 3616.12850905],
        [ 561.49831112, 3618.23926358],
        [1495.42862628, 3631.58120249],
        [2249.92804167, 3712.9381953 ],
        [2989.31997419, 3677.39003378],
        [1597.90313883, 3642.71425337],
        [2601.34514343, 3729.30154786],
        [1124.96778871, 3719.06046608],
        [2815.71796932, 3728.80094877],
        [ 720.20746715, 3683.93130779],
        [2488.48932086, 3709.28060781],
        [ 358.72033954, 3757.22400403],
        [ 148.32611982, 3746.66520805],
        [1428.51862656, 3743.10963062],
        [1301.52794235, 3785.83002402]]),
 array([[3373.59782977,   60.92415508],
        [3010.19513463,   56.64205329],
        [2012.72142111,   92.39561129],
        [2423.76518683,   65.01917934],
        [ 242.71044214,   66.00797742],
        [2307.47100166,   72.09179545],
        [ 895.38757614,  152.51250918],
        [ 692.97402667,   96.43920813],
        [1603.91968194,  165.52148664],
        [ 120.18507616,  141.85992848],
        [1071.09830338,  133.21112352],
        [3257.50085803,  116.41942278],
        [1303.11827352,  124.02017504],
        [2216.4635383 ,  207.78826131],
        [3051.65446179,  145.9789987 ],
        [1958.24334536,  143.28081589],
        [ 373.13974162,  194.67876615],
        [ 581.01108272,  167.07285702],
        [1670.07515538,  220.35492313],
        [ 693.43025035,  265.72432688],
        [2059.72155025,  241.02762149],
        [1834.04042101,  223.91022319],
        [2912.39341137,  202.76768216],
        [2755.56974766,  274.85409316],
        [1438.17019216,  323.88097721],
        [2294.00485861,  305.28915233],
        [3196.48888684,  257.96707553],
        [3673.06087412,  254.09906656],
        [2389.34729581,  259.69363155],
        [2142.07679171,  288.11388158],
        [1189.23905285,  304.03883793],
        [1613.96580401,  295.43358946],
        [3038.47515539,  284.8289048 ],
        [ 808.02434997,  286.79913263],
        [ 624.03436495,  331.84535772],
        [3508.1858301 ,  317.89289155],
        [ 916.34111028,  354.67824936],
        [2096.44898368,  379.60548713],
        [ 399.1942387 ,  422.05338641],
        [1752.05654231,  354.76622922],
        [1369.83354108,  408.16511024],
        [2329.75223065,  381.86820625],
        [3383.75842118,  399.12398396],
        [2791.56422276,  429.30575661],
        [ 238.23468778,  475.65088139],
        [2468.5783382 ,  458.662881  ],
        [1306.09657035,  533.15531887],
        [2087.44530077,  510.55466623],
        [1842.63205054,  511.99212702],
        [2610.72830754,  549.72547845],
        [1462.71525767,  511.28105096],
        [3670.70025882,  508.12406988],
        [1132.7059296 ,  528.1853778 ],
        [2255.36881955,  532.43715029],
        [1961.84861984,  528.07586515],
        [ 414.01136417,  573.75552947],
        [3180.97109827,  588.14155663],
        [2823.7814191 ,  578.46598439],
        [3253.86358003,  603.48885574],
        [3374.73981475,  572.65004527],
        [2344.09636064,  586.51603029],
        [3537.81473506,  611.77851265],
        [ 152.86056268,  589.4266251 ],
        [ 593.74393349,  619.35073397],
        [2688.61254613,  659.89401605],
        [1009.93149731,  677.84539597],
        [ 476.93849784,  618.42609433],
        [ 653.62990613,  640.00206963],
        [1059.05546414,  687.98809939],
        [1195.71632238,  638.18859039],
        [1526.26726026,  650.10161826],
        [ 866.46454284,  665.44672426],
        [2930.59110365,  697.04502962],
        [3626.2234515 ,  727.03420335],
        [3073.31116812,  729.78616682],
        [1263.2077299 ,  685.68147783],
        [3306.39667826,  716.8575331 ],
        [2084.92540838,  717.07103209],
        [2188.38949215,  755.76470588],
        [2321.21785466,  724.66930596],
        [ 530.99570493,  764.07305784],
        [2483.62714409,  778.6983726 ],
        [1908.79897889,  833.46972752],
        [ 417.59079164,  766.05019184],
        [3691.81549388,  804.67966187],
        [3476.77566652,  814.90462358],
        [ 253.55536412,  827.06999757],
        [2203.74190054,  859.86732504],
        [ 718.99007781,  841.82164766],
        [ 826.21407636,  816.31951916],
        [2791.45085846,  824.45032886],
        [3084.9399506 ,  828.05588144],
        [3381.77775816,  860.69240953],
        [1998.27354132,  834.16100712],
        [ 445.42935898,  892.28260554],
        [2691.76168898,  921.00748369],
        [3228.13632157,  848.64161147],
        [1693.19936262,  855.08753124],
        [3608.6667933 ,  911.83180588],
        [ 574.04134424,  881.87884148],
        [3721.77244827,  942.34896009],
        [ 654.30246669,  972.76136471],
        [1301.03399004,  918.28570398],
        [2407.80999412,  945.78318636],
        [2151.68754577,  938.81579847],
        [ 853.09552268,  949.37418045],
        [2558.41587977,  962.60014919],
        [1444.86848224, 1020.59553992],
        [1822.14839538,  982.13080017],
        [2917.52106075,  986.00206995],
        [3606.83210769,  959.84752171],
        [ 133.9829536 ,  998.06205782],
        [3316.17719016, 1010.42623791],
        [ 448.39127806,  994.1388094 ],
        [1004.64970159, 1001.5501492 ],
        [3140.3262842 , 1026.69946957],
        [1269.6423292 , 1068.86691956],

In [52]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [53]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [54]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,3057.713902,188.769908,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1546.775215,197.867513,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1470.051001,223.607234,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3233.792363,182.682060,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,724.648597,232.740406,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
43922,3369.219554,3908.322244,00462@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43923,3449.979314,3855.615170,00463@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43924,553.635980,3919.019685,00464@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43925,798.445287,3904.078283,00465@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43926,2610.676474,3893.280818,00466@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [55]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [56]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [57]:
nms_config

(0.5, 0.6)

In [58]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [59]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3471
Number of Particles: 666
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 604
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3483
Number of Particles: 676
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3249
Number of Particles: 454
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3280
Number of Particles: 453
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3432
Number of Particles: 625
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2998
Number of Particles: 452
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3419
Number of Particles: 511
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3485
Number of Particles: 659
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3488
Number of Particles: 671
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3375
Number of Particles: 627
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3430
Number of Particles: 490
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3471
Number of Particles: 638
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3411
Number of Particles: 510
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 713
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3478
Number of Particles: 637
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 570
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3287
Number of Particles: 594
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3220
Number of Particles: 555
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3471
Number of Particles: 642
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3482
Number of Particles: 647
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 690
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3436
Number of Particles: 652
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 764
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 663
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3478
Number of Particles: 659
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 664
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 709
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3478
Number of Particles: 684
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3466
Number of Particles: 608
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 629
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3476
Number of Particles: 709
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 649
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 626
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 625
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3483
Number of Particles: 668
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 631
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3488
Number of Particles: 686
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3389
Number of Particles: 597
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3448
Number of Particles: 663
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3052
Number of Particles: 523
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 702
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3476
Number of Particles: 608
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3219
Number of Particles: 431
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2684
Number of Particles: 524
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3349
Number of Particles: 477
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2966
Number of Particles: 544
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3382
Number of Particles: 493
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3488
Number of Particles: 659
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3446
Number of Particles: 639
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3477
Number of Particles: 637
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 632
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3447
Number of Particles: 617
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3421
Number of Particles: 498
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 614
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3337
Number of Particles: 521
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 632
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3433
Number of Particles: 654
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3405
Number of Particles: 722
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3456
Number of Particles: 676
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3206
Number of Particles: 477
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3458
Number of Particles: 550
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3375
Number of Particles: 494
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3386
Number of Particles: 468
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3378
Number of Particles: 469
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3345
Number of Particles: 464
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3252
Number of Particles: 454
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3427
Number of Particles: 550
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3371
Number of Particles: 510
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3392
Number of Particles: 521
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3357
Number of Particles: 560
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 1921
Number of Particles: 554
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3433
Number of Particles: 523
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 523
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3355
Number of Particles: 500
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 580
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3325
Number of Particles: 460
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3409
Number of Particles: 546
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3417
Number of Particles: 481
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2918
Number of Particles: 518
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3410
Number of Particles: 541
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3343
Number of Particles: 566
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3295
Number of Particles: 514
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3359
Number of Particles: 554

In [60]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [61]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [62]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,2301.6,3760.0,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,2458.0,360.0,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,2798.4,3094.2,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3467.0,728.0,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3046.0,432.0,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
49145,3695.0,1855.0,00549@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49146,612.0,3583.0,00550@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49147,934.0,2471.0,00551@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49148,2431.0,2111.0,00552@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49149,3840.0,1791.0,00553@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [63]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')

In [64]:
# @markdown ---
# @markdown time used
end_time = time.time()
print(f"End time recorded: {end_time}")

elapsed_time = end_time - start_time
elapsed_time = elapsed_time


hours = int(elapsed_time // 3600)
remaining_seconds = elapsed_time % 3600

minutes = int(remaining_seconds // 60)
seconds = round(remaining_seconds % 60, 3)

print(f"Time spend : {hours} h, {minutes} m, {seconds} s")


gpu_used = "L4" # @param ["CPU high", "T4", "T4 high", "L4"]
per_unit_cost_dict = {"L4" : 1.71, "T4 high" : 1.41, "T4" : 1.19, "CPU high" :  0.24}
per_unit_cost = per_unit_cost_dict[gpu_used]
print(f"unit price per hr {per_unit_cost}")

cost_units = per_unit_cost * elapsed_time / 3600

per_unit_US = 10.49 / 100

cost_price_US = cost_units * per_unit_US

print(f"unit cost : {round(cost_units, 4)}")
print(f"unit price US: {cost_price_US}")
print(f"unit price NTD: {cost_price_US * 30.76}")

End time recorded: 1762783306.939631
Time spend : 0 h, 19 m, 49.243 s
unit price per hr 1.71
unit cost : 0.5649
unit price US: 0.059256993217147
unit price NTD: 1.822745111359442