In [1]:
import time

start_time = time.time()
print(f"Start time recorded: {start_time}")

Start time recorded: 1763014795.4815695

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [2]:
do = False # @param{type:"boolean"}
if do:
    %pip install torchinfo -qq
    %pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
    %pip install starfile -qq
    %pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

In [3]:
if do:
    !git clone https://github.com/phonchi/CryoParticleSegment.git

In [4]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

In [5]:
if do:
    #%git clone https://github.com/netw0rkf10w/CRF.git
    %cd CryoParticleSegment/Modeling/CRF_main
    !python setup.py clean --all
    !rm -rf build/
    !python setup.py build_ext --inplace --force
    !python setup.py install

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [6]:
if do:
    %pip install pycuda==2024.1
    %pip install "numpy<2.0"
    %pip install mrcfile -qq

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [7]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C_CSN_D_float_u_output/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C_CSN_D_float_u_output/results_50_CRF/10017/unet_eb5_dice_CRF" # @param {type:"string"}

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
IMAGE_DIR = "/content/image_dir"

In [11]:
%cd /content/

/content

### ✅ Packages Handling

In [12]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [13]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [14]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 8
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [15]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [16]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [17]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

config.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/122M [00:00<?, ?B/s]

In [18]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [19]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [20]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [21]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [22]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [23]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:27<00:00,  3.05it/s]

In [24]:
processed_micrographs.shape

(84, 3840, 3840)

In [25]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [26]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [27]:
del model
torch.cuda.empty_cache()

In [28]:
model = model_post

In [29]:
RESULT_DIR

'/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C_CSN_D_float_u_output/results_50_CRF/10017/unet_eb5_dice_CRF'

In [30]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [31]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [32]:
!cp {RESULT_DIR}/label_images.npy .

In [33]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [34]:
label_images.shape

(84, 3840, 3840)

In [35]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [36]:
!cp {RESULT_DIR}/best_config.txt .

In [37]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [38]:
radius = RADIUS

In [39]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [40]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

536 449
549 476
509 395
375 354
388 356
503 428
378 365
481 439
536 444
582 497
538 486
521 485
537 464
478 442
575 484
542 467
506 433
517 457
488 434
577 507
556 461
525 436
510 436
524 404
487 379
488 389
504 405
554 446
505 392
548 492
547 475
487 375
532 440
550 464
544 470
546 453
528 453
537 437
544 485
520 423
416 372
542 447
563 503
374 351
301 295
402 362
348 337
526 493
562 487
490 398
529 450
528 448
566 512
525 497
555 491
484 435
525 447
555 482
479 383
482 396
448 433
491 427
488 457
473 438
464 422
463 437
403 385
459 400
404 344
449 383
459 399
223 223
461 407
488 438
399 354
496 421
416 396
472 411
463 418
354 344
465 402
463 402
414 354
463 398

In [41]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [42]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [43]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [44]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,3530,3950,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1511,3951,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,431,3950,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,1238,3948,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,248,3947,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
35651,1815,150,00393@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35652,315,148,00394@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35653,2854,155,00395@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35654,1981,174,00396@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35655,3603,160,00397@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [45]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [46]:
cv_list

[[(3402, 3822),
  (1383, 3823),
  (303, 3822),
  (1110, 3820),
  (120, 3819),
  (623, 3813),
  (3583, 3814),
  (2410, 3815),
  (3040, 3807),
  (3686, 3782),
  (1186, 3801),
  (1795, 3780),
  (2823, 3783),
  (2693, 3789),
  (1564, 3780),
  (1698, 3763),
  (2952, 3761),
  (975, 3728),
  (1295, 3729),
  (3421, 3689),
  (27, 3688),
  (468, 3685),
  (366, 3672),
  (1782, 3681),
  (1136, 3653),
  (1532, 3653),
  (2769, 3658),
  (1435, 3665),
  (3054, 3648),
  (16, 3607),
  (3694, 3573),
  (992, 3594),
  (754, 3565),
  (3227, 3547),
  (3089, 3554),
  (1127, 3538),
  (37, 3532),
  (879, 3506),
  (675, 3518),
  (2365, 3490),
  (138, 3485),
  (2999, 3493),
  (1577, 3476),
  (2776, 3459),
  (602, 3469),
  (3786, 3447),
  (1773, 3459),
  (765, 3431),
  (1479, 3436),
  (2265, 3425),
  (999, 3414),
  (16, 3408),
  (2931, 3403),
  (2644, 3413),
  (516, 3409),
  (3148, 3373),
  (2808, 3359),
  (673, 3350),
  (209, 3358),
  (884, 3369),
  (1597, 3339),
  (2144, 3330),
  (3372, 3321),
  (331, 3312),
  (2661, 3301),
  (1071, 3299),
  (3619, 3290),
  (895, 3280),
  (1876, 3262),
  (3166, 3231),
  (2808, 3222),
  (1219, 3197),
  (329, 3211),
  (2599, 3208),
  (503, 3204),
  (3546, 3193),
  (2261, 3229),
  (2694, 3185),
  (3744, 3191),
  (633, 3212),
  (2140, 3146),
  (3155, 3136),
  (1598, 3121),
  (792, 3122),
  (236, 3140),
  (3823, 3088),
  (3304, 3107),
  (1271, 3109),
  (3561, 3087),
  (3451, 3090),
  (608, 3086),
  (2305, 3084),
  (2006, 3053),
  (3367, 3032),
  (3246, 3022),
  (1347, 2997),
  (374, 3011),
  (3627, 3006),
  (24, 2954),
  (2315, 2966),
  (3286, 2944),
  (1809, 2927),
  (2077, 2942),
  (2906, 2941),
  (2785, 2934),
  (2587, 2936),
  (268, 2929),
  (890, 2914),
  (1141, 2881),
  (3030, 2874),
  (3360, 2852),
  (2509, 2826),
  (2698, 2820),
  (3601, 2816),
  (46, 2759),
  (3039, 2739),
  (2781, 2734),
  (3248, 2744),
  (1039, 2750),
  (2872, 2750),
  (889, 2759),
  (2589, 2741),
  (2507, 2729),
  (2168, 2759),
  (3694, 2707),
  (1991, 2686),
  (2954, 2658),
  (2094, 2663),
  (3566, 2653),
  (3396, 2689),
  (3237, 2645),
  (1739, 2646),
  (971, 2636),
  (31, 2606),
  (253, 2598),
  (1638, 2601),
  (2675, 2587),
  (2522, 2573),
  (1333, 2566),
  (1546, 2591),
  (3237, 2551),
  (3807, 2535),
  (2828, 2541),
  (122, 2544),
  (3345, 2546),
  (2337, 2545),
  (1170, 2513),
  (3700, 2513),
  (2602, 2510),
  (2261, 2517),
  (393, 2487),
  (1886, 2479),
  (745, 2461),
  (1628, 2474),
  (3541, 2462),
  (1712, 2458),
  (2360, 2446),
  (1336, 2429),
  (2934, 2460),
  (3455, 2425),
  (3160, 2410),
  (3821, 2380),
  (1562, 2405),
  (441, 2397),
  (3740, 2388),
  (597, 2402),
  (3039, 2380),
  (327, 2376),
  (3622, 2371),
  (1404, 2361),
  (1735, 2347),
  (2838, 2357),
  (2040, 2347),
  (1917, 2346),
  (2643, 2314),
  (191, 2332),
  (3801, 2313),
  (1382, 2286),
  (1087, 2311),
  (1589, 2302),
  (3099, 2314),
  (76, 2253),
  (3274, 2296),
  (2353, 2287),
  (362, 2279),
  (3597, 2244),
  (594, 2268),
  (510, 2235),
  (2760, 2222),
  (3741, 2245),
  (1997, 2237),
  (3822, 2215),
  (3248, 2188),
  (946, 2160),
  (436, 2174),
  (2463, 2190),
  (26, 2150),
  (769, 2162),
  (1603, 2179),
  (3004, 2185),
  (642, 2126),
  (2345, 2110),
  (3443, 2111),
  (68, 2094),
  (1054, 2086),
  (2155, 2079),
  (2013, 2044),
  (21, 2044),
  (915, 2045),
  (688, 2034),
  (323, 2024),
  (3779, 2039),
  (427, 2009),
  (1331, 2009),
  (221, 2005),
  (3191, 2014),
  (1536, 1979),
  (1448, 2005),
  (827, 1969),
  (1725, 1971),
  (2734, 1952),
  (1105, 1925),
  (914, 1914),
  (2886, 1900),
  (1306, 1905),
  (3217, 1889),
  (3440, 1919),
  (3653, 1875),
  (95, 1864),
  (669, 1858),
  (991, 1810),
  (2755, 1842),
  (3819, 1819),
  (1073, 1839),
  (2136, 1811),
  (3003, 1809),
  (1395, 1805),
  (505, 1785),
  (2855, 1749),
  (469, 1719),
  (3086, 1736),
  (2119, 1728),
  (1106, 1731),
  (46, 1713),
  (1584, 1728),
  (2793, 1694),
  (3425, 1687),
  (1406, 1678),
  (3619, 1682),
  (3815, 1646),
  (3313, 1650),
  (2227, 1658),
  (570, 1653),
  (1852, 1646),
  (657, 1624),
  (2713, 1625),
  (2987, 1618),
  (1932, 1635),
  (341, 1597),
  (3244, 1561),
  (3090, 1551),
  (155, 1557),
  (454, 1546),
  (1895, 1544),
  (2697, 1531),
  (968, 1520),
  (3611, 1507),
  (3166, 1499),
  (3713, 1497),
  (1457, 1482),
  (878, 1477),
  (3229, 1447),
  (206, 1472),
  (765, 1453),
  (424, 1450),
  (2575, 1395),
  (1188, 1408),
  (496, 1393),
  (2216, 1398),
  (1401, 1385),
  (1099, 1377),
  (2692, 1389),
  (2318, 1385),
  (2086, 1365),
  (785, 1328),
  (1258, 1321),
  (2449, 1315),
  (3292, 1350),
  (1962, 1326),
  (1758, 1345),
  (3176, 1306),
  (1058, 1293),
  (2827, 1278),
  (3517, 1280),
  (2073, 1274),
  (417, 1266),
  (2608, 1254),
  (3014, 1244),
  (57, 1256),
  (900, 1249),
  (1344, 1241),
  (2282, 1220),
  (1826, 1200),
  (1240, 1214),
  (570, 1215),
  (2151, 1181),
  (2739, 1176),
  (2523, 1185),
  (3821, 1148),
  (2072, 1153),
  (1522, 1151),
  (3322, 1164),
  (3484, 1136),
  (617, 1116),
  (297, 1121),
  (2995, 1106),
  (1795, 1088),
  (863, 1112),
  (1300, 1072),
  (2650, 1067),
  (2430, 1060),
  (1063, 1066),
  (1932, 1035),
  (1828, 1001),
  (2818, 1021),
  (479, 981),
  (1094, 985),
  (750, 986),
  (2246, 975),
  (673, 948),
  (66, 974),
  (3412, 959),
  (482, 948),
  (3071, 957),
  (3819, 908),
  (1850, 918),
  (1748, 916),
  (3144, 898),
  (1095, 884),
  (2409, 861),
  (965, 863),
  (2722, 833),
  (1319, 841),
  (449, 832),
  (3067, 825),
  (1040, 800),
  (3790, 816),
  (1174, 812),
  (352, 797),
  (3403, 822),
  (2484, 781),
  (1276, 783),
  (920, 781),
  (1656, 765),
  (35, 752),
  (1422, 737),
  (944, 702),
  (2966, 758),
  (1610, 696),
  (3702, 704),
  (749, 677),
  (168, 672),
  (21, 661),
  (1143, 653),
  (852, 657),
  (537, 647),
  (1805, 638),
  (1031, 631),
  (1517, 617),
  (2482, 613),
  (1332, 615),
  (3156, 597),
  (626, 586),
  (3794, 550),
  (38, 559),
  (456, 560),
  (2299, 556),
  (2616, 534),
  (1721, 532),
  (1630, 571),
  (2385, 539),
  (132, 525),
  (3628, 509),
  (1446, 520),
  (3186, 534),
  (1347, 518),
  (595, 504),
  (2949, 505),
  (1104, 504),
  (2835, 495),
  (482, 478),
  (74, 462),
  (3689, 458),
  (3810, 448),
  (3442, 453),
  (2211, 451),
  (231, 433),
  (3103, 416),
  (1440, 423),
  (347, 418),
  (2292, 403),
  (17, 361),
  (1226, 369),
  (545, 378),
  (3025, 360),
  (3238, 345),
  (1409, 343),
  (954, 325),
  (860, 315),
  (3811, 267),
  (3738, 296),
  (178, 286),
  (460, 288),
  (2926, 308),
  (3533, 271),
  (1883, 275),
  (3183, 257),
  (1316, 239),
  (724, 234),
  (1730, 235),
  (3097, 204),
  (884, 214),
  (17, 188),
  (1133, 210),
  (782, 165),
  (3267, 145),
  (2020, 140),
  (2565, 135),
  (168, 117),
  (2179, 108),
  (593, 113),
  (2714, 102),
  (340, 111),
  (714, 93),
  (1797, 96),
  (2821, 80),
  (2934, 60),
  (3217, 50),
  (2998, 71),
  (126, 24),
  (3094, 24),
  (2077, 26),
  (1873, 35),
  (1196, 88),
  (805, 40),
  (211, 19),
  (2309, 26),
  (3466, 62),
  (2691, 22)],
 [(3120, 3820),
  (274, 3815),
  (2434, 3819),
  (729, 3816),
  (3396, 3815),
  (1457, 3810),
  (3009, 3808),
  (1743, 3805),
  (3765, 3808),
  (1659, 3783),
  (959, 3798),
  (2587, 3799),
  (1184, 3795),
  (2164, 3788),
  (3228, 3790),
  (3605, 3784),
  (2787, 3785),
  (170, 3783),
  (1885, 3781),
  (2262, 3773),
  (505, 3766),
  (1310, 3754),
  (848, 3771),
  (1578, 3755),
  (3151, 3741),
  (731, 3727),
  (2673, 3722),
  (354, 3724),
  (2427, 3726),
  (41, 3704),
  (1391, 3702),
  (1122, 3699),
  (971, 3700),
  (852, 3677),
  (2955, 3692),
  (3410, 3688),
  (2758, 3666),
  (1251, 3664),
  (107, 3631),
  (403, 3647),
  (563, 3636),
  (2586, 3619),
  (3333, 3607),
  (3200, 3602),
  (1076, 3599),
  (1482, 3592),
  (1339, 3592),
  (242, 3613),
  (1922, 3557),
  (2392, 3553),
  (2247, 3568),
  (1642, 3565),
  (2874, 3585),
  (872, 3550),
  (3039, 3536),
  (760, 3534),
  (2154, 3525),
  (1743, 3520),
  (161, 3481),
  (483, 3478),
  (2429, 3486),
  (3419, 3456),
  (2543, 3469),
  (3612, 3453),
  (1873, 3441),
  (2329, 3444),
  (294, 3435),
  (2758, 3432),
  (1522, 3427),
  (3499, 3428),
  (3302, 3420),
  (1760, 3411),
  (2953, 3416),
  (69, 3405),
  (968, 3399),
  (3175, 3406),
  (2969, 3340),
  (1675, 3379),
  (183, 3361),
  (2210, 3363),
  (1224, 3354),
  (1124, 3347),
  (3692, 3346),
  (1851, 3341),
  (2652, 3326),
  (1556, 3332),
  (963, 3299),
  (3441, 3284),
  (20, 3254),
  (2576, 3272),
  (160, 3267),
  (1666, 3258),
  (3589, 3276),
  (1235, 3243),
  (1850, 3247),
  (3781, 3244),
  (3037, 3258),
  (362, 3245),
  (799, 3220),
  (2164, 3233),
  (2866, 3221),
  (608, 3223),
  (2709, 3191),
  (18, 3174),
  (1804, 3176),
  (1309, 3167),
  (945, 3169),
  (3611, 3165),
  (1417, 3125),
  (2625, 3126),
  (1009, 3102),
  (3341, 3098),
  (3441, 3099),
  (3258, 3103),
  (1904, 3090),
  (1122, 3087),
  (572, 3083),
  (312, 3090),
  (2729, 3080),
  (2119, 3062),
  (3153, 3048),
  (2843, 3053),
  (893, 3019),
  (1219, 3021),
  (1457, 3022),
  (2260, 3020),
  (234, 3006),
  (2011, 2999),
  (1034, 2994),
  (3723, 2970),
  (792, 2964),
  (3275, 2945),
  (1806, 2945),
  (2080, 2927),
  (2429, 2931),
  (3442, 2896),
  (2308, 2903),
  (1898, 2900),
  (3820, 2875),
  (3575, 2884),
  (2175, 2869),
  (3170, 2858),
  (856, 2858),
  (1367, 2845),
  (240, 2847),
  (3654, 2828),
  (2996, 2834),
  (2025, 2827),
  (3395, 2816),
  (2104, 2812),
  (2348, 2813),
  (1582, 2810),
  (541, 2841),
  (57, 2796),
  (1461, 2794),
  (3814, 2765),
  (2477, 2764),
  (3225, 2761),
  (683, 2737),
  (420, 2740),
  (1959, 2742),
  (3724, 2703),
  (515, 2705),
  (3351, 2684),
  (2354, 2688),
  (1702, 2691),
  (3280, 2679),
  (240, 2660),
  (3076, 2646),
  (52, 2670),
  (1783, 2642),
  (3663, 2631),
  (1247, 2634),
  (475, 2616),
  (1892, 2592),
  (1143, 2627),
  (3494, 2579),
  (3367, 2586),
  (2511, 2580),
  (2732, 2567),
  (391, 2553),
  (2013, 2577),
  (1447, 2557),
  (3242, 2549),
  (3632, 2546),
  (2899, 2502),
  (150, 2497),
  (1073, 2489),
  (3574, 2479),
  (1653, 2476),
  (826, 2472),
  (2751, 2465),
  (3418, 2454),
  (3111, 2455),
  (242, 2423),
  (41, 2439),
  (1311, 2420),
  (3676, 2422),
  (3535, 2409),
  (3034, 2409),
  (1630, 2372),
  (345, 2356),
  (906, 2361),
  (1733, 2338),
  (2651, 2345),
  (3504, 2313),
  (521, 2354),
  (803, 2322),
  (259, 2309),
  (3650, 2324),
  (918, 2280),
  (3699, 2282),
  (1129, 2318),
  (2494, 2290),
  (2604, 2268),
  (2375, 2275),
  (590, 2274),
  (2907, 2267),
  (3060, 2263),
  (375, 2264),
  (1643, 2255),
  (19, 2254),
  (705, 2259),
  (1314, 2257),
  (2020, 2240),
  (985, 2263),
  (481, 2230),
  (1836, 2225),
  (3120, 2203),
  (2939, 2177),
  (138, 2208),
  (1454, 2164),
  (3345, 2156),
  (3450, 2175),
  (873, 2149),
  (366, 2138),
  (83, 2135),
  (2050, 2116),
  (2394, 2122),
  (3541, 2100),
  (965, 2111),
  (3656, 2107),
  (703, 2068),
  (432, 2060),
  (1644, 2055),
  (2851, 2058),
  (3778, 2034),
  (1174, 2036),
  (45, 2027),
  (1528, 2012),
  (2077, 2015),
  (328, 1980),
  (2317, 1960),
  (3596, 1955),
  (1767, 1956),
  (1152, 1921),
  (3796, 1929),
  (2748, 1949),
  (3180, 1924),
  (1472, 1926),
  (2465, 1914),
  (3266, 1905),
  (1897, 1895),
  (810, 1882),
  (2031, 1843),
  (59, 1855),
  (2839, 1841),
  (1975, 1828),
  (2068, 1804),
  (2604, 1844),
  (3535, 1815),
  (1627, 1850),
  (948, 1853),
  (1811, 1813),
  (2157, 1803),
  (2736, 1798),
  (416, 1783),
  (3315, 1756),
  (2280, 1766),
  (2837, 1740),
  (3172, 1718),
  (1950, 1707),
  (3015, 1754),
  (2168, 1690),
  (1762, 1692),
  (3442, 1657),
  (2324, 1654),
  (1950, 1633),
  (78, 1653),
  (1611, 1627),
  (1019, 1629),
  (1415, 1607),
  (2265, 1580),
  (1721, 1579),
  (523, 1554),
  (1464, 1553),
  (72, 1544),
  (2110, 1524),
  (2513, 1538),
  (1861, 1492),
  (2768, 1511),
  (152, 1500),
  (418, 1486),
  (1970, 1465),
  (1313, 1477),
  (1726, 1467),
  (2199, 1449),
  (3006, 1439),
  (842, 1423),
  (238, 1397),
  (113, 1384),
  (2078, 1394),
  (999, 1433),
  (3307, 1358),
  (1078, 1381),
  (1553, 1377),
  (2819, 1381),
  (17, 1335),
  (1654, 1360),
  (2233, 1321),
  (3359, 1290),
  (1777, 1325),
  (2554, 1294),
  (919, 1284),
  (379, 1285),
  (2945, 1254),
  (2393, 1250),
  (2106, 1259),
  (1511, 1232),
  (3574, 1223),
  (2721, 1201),
  (3749, 1215),
  (1883, 1204),
  (1360, 1199),
  (1056, 1206),
  (105, 1227),
  (1731, 1174),
  (239, 1208),
  (1469, 1157),
  (3627, 1152),
  (468, 1132),
  (666, 1135),
  (2845, 1160),
  (1652, 1113),
  (804, 1116),
  (3088, 1113),
  (3769, 1098),
  (2779, 1095),
  (1166, 1069),
  (556, 1066),
  (44, 1056),
  (365, 1051),
  (2078, 1045),
  (1898, 1020),
  (1380, 1015),
  (2600, 961),
  (732, 974),
  (1603, 982),
  (187, 944),
  (2357, 934),
  (623, 953),
  (17, 913),
  (1357, 919),
  (3725, 920),
  (2496, 906),
  (3125, 910),
  (332, 906),
  (1835, 920),
  (1106, 879),
  (3621, 864),
  (2905, 874),
  (3040, 846),
  (1584, 857),
  (2791, 834),
  (2663, 806),
  (3327, 814),
  (681, 828),
  (964, 776),
  (3745, 773),
  (806, 758),
  (2425, 758),
  (1636, 761),
  (3416, 751),
  (1390, 748),
  (567, 732),
  (2265, 720),
  (2681, 719),
  (156, 715),
  (1302, 714),
  (2129, 716),
  (3576, 699),
  (1730, 680),
  (721, 683),
  (1444, 651),
  (1202, 658),
  (902, 664),
  (2288, 630),
  (2390, 639),
  (1615, 608),
  (2159, 597),
  (1920, 596),
  (3821, 546),
  (573, 546),
  (3347, 527),
  (3386, 519),
  (2273, 536),
  (2384, 543),
  (2017, 533),
  (771, 529),
  (1621, 516),
  (1858, 512),
  (1278, 507),
  (3171, 500),
  (1760, 523),
  (3260, 506),
  (1166, 475),
  (3478, 478),
  (373, 467),
  (2455, 444),
  (3380, 435),
  (1325, 416),
  (3080, 412),
  (270, 404),
  (904, 408),
  (1858, 395),
  (2024, 377),
  (483, 373),
  (3162, 363),
  (2642, 373),
  (3459, 369),
  (134, 342),
  (2274, 345),
  (3667, 315),
  (537, 307),
  (1490, 317),
  (349, 304),
  (1633, 307),
  (1865, 293),
  (3056, 294),
  (1272, 266),
  (2700, 265),
  (1772, 281),
  (1959, 266),
  (54, 254),
  (3511, 247),
  (2167, 290),
  (3733, 227),
  (576, 222),
  (435, 208),
  (649, 188),
  (52, 178),
  (3375, 172),
  (3174, 165),
  (2107, 162),
  (784, 154),
  (1356, 144),
  (875, 153),
  (1529, 141),
  (1183, 129),
  (691, 109),
  (519, 88),
  (76, 72),
  (3282, 69),
  (2200, 58),
  (1745, 60),
  (3685, 45),
  (3567, 59),
  (2560, 52),
  (2083, 47),
  (1988, 43),
  (834, 39),
  (587, 23),
  (2980, 18),
  (442, 74),
  (1359, 18),
  (2730, 17)],
 [(1171, 3822),
  (2899, 3819),
  (1711, 3819),
  (2488, 3809),
  (3429, 3816),
  (2352, 3803),
  (3559, 3796),
  (3284, 3802),
  (490, 3796),
  (1272, 3803),
  (3698, 3783),
  (1503, 3774),
  (2722, 3770),
  (912, 3734),
  (780, 3738),
  (1125, 3734),
  (20, 3729),
  (2922, 3729),
  (2308, 3723),
  (3376, 3714),
  (1396, 3717),
  (172, 3684),
  (3738, 3688),
  (699, 3692),
  (3304, 3673),
  (2414, 3664),
  (1530, 3667),
  (1227, 3665),
  (2259, 3652),
  (1321, 3621),
  (1992, 3617),
  (1808, 3650),
  (2792, 3615),
  (1382, 3623),
  (2353, 3621),
  (164, 3593),
  (1252, 3556),
  (378, 3579),
  (3810, 3566),
  (3381, 3557),
  (2115, 3548),
  (67, 3584),
  (1249, 3525),
  (2347, 3526),
  (1683, 3537),
  (228, 3524),
  (2784, 3535),
  (827, 3492),
  (3218, 3460),
  (2924, 3461),
  (3604, 3428),
  (2342, 3419),
  (3709, 3411),
  (2662, 3396),
  (3222, 3340),
  (335, 3364),
  (2100, 3398),
  (904, 3366),
  (3105, 3364),
  (612, 3346),
  (1533, 3330),
  (2192, 3317),
  (236, 3299),
  (444, 3315),
  (3818, 3261),
  (2548, 3291),
  (1699, 3255),
  (2118, 3240),
  (102, 3244),
  (529, 3253),
  (1927, 3243),
  (325, 3220),
  (1321, 3230),
  (951, 3221),
  (2700, 3180),
  (2002, 3202),
  (3620, 3189),
  (1161, 3180),
  (1786, 3156),
  (3756, 3154),
  (403, 3143),
  (3465, 3132),
  (517, 3135),
  (2630, 3128),
  (2127, 3121),
  (304, 3111),
  (2476, 3092),
  (1899, 3090),
  (3786, 3071),
  (669, 3067),
  (220, 3099),
  (1229, 3067),
  (2334, 3071),
  (583, 3056),
  (2264, 3009),
  (3476, 3021),
  (863, 3026),
  (2631, 3005),
  (2781, 2996),
  (1256, 2977),
  (1828, 2975),
  (1949, 3001),
  (70, 3009),
  (2187, 2960),
  (337, 2944),
  (2913, 2940),
  (1270, 2883),
  (907, 2900),
  (2324, 2906),
  (1563, 2857),
  (2175, 2827),
  (1737, 2818),
  (1134, 2828),
  (3432, 2810),
  (2622, 2782),
  (185, 2780),
  (2932, 2809),
  (2087, 2778),
  (3670, 2755),
  (2791, 2743),
  (2693, 2720),
  (996, 2740),
  (735, 2708),
  (3291, 2728),
  (2543, 2737),
  (3552, 2713),
  (1953, 2692),
  (1742, 2682),
  (27, 2663),
  (155, 2662),
  (2761, 2670),
  (3214, 2659),
  (2848, 2619),
  (1456, 2606),
  (2084, 2580),
  (3342, 2565),
  (1002, 2611),
  (65, 2577),
  (3129, 2567),
  (896, 2516),
  (1153, 2515),
  (400, 2490),
  (210, 2493),
  (1731, 2476),
  (3256, 2445),
  (1864, 2448),
  (1459, 2472),
  (91, 2438),
  (3729, 2373),
  (3598, 2370),
  (1941, 2358),
  (335, 2345),
  (2083, 2350),
  (460, 2332),
  (1042, 2329),
  (3026, 2335),
  (3247, 2341),
  (493, 2290),
  (1628, 2290),
  (1373, 2304),
  (2753, 2282),
  (2925, 2300),
  (31, 2253),
  (1159, 2271),
  (173, 2268),
  (2201, 2252),
  (2054, 2253),
  (757, 2242),
  (558, 2207),
  (79, 2203),
  (1800, 2217),
  (338, 2218),
  (3587, 2184),
  (2901, 2180),
  (949, 2176),
  (1684, 2141),
  (1976, 2167),
  (1459, 2126),
  (3025, 2134),
  (2509, 2137),
  (909, 2098),
  (174, 2117),
  (474, 2101),
  (1617, 2088),
  (822, 2129),
  (3584, 2086),
  (2814, 2070),
  (1199, 2068),
  (2951, 2046),
  (2416, 2042),
  (1084, 2020),
  (1701, 2009),
  (3089, 2004),
  (706, 2005),
  (966, 2006),
  (1526, 1990),
  (3594, 1984),
  (2282, 1993),
  (979, 1916),
  (89, 1924),
  (3022, 1909),
  (3352, 1886),
  (2182, 1891),
  (186, 1869),
  (509, 1886),
  (3261, 1834),
  (2038, 1815),
  (280, 1788),
  (2943, 1807),
  (2512, 1789),
  (981, 1780),
  (413, 1756),
  (135, 1740),
  (18, 1737),
  (888, 1690),
  (3507, 1701),
  (595, 1693),
  (2888, 1692),
  (3064, 1674),
  (504, 1661),
  (102, 1658),
  (195, 1652),
  (3648, 1671),
  (19, 1632),
  (1225, 1677),
  (1085, 1647),
  (310, 1655),
  (942, 1624),
  (1585, 1609),
  (2574, 1606),
  (3267, 1607),
  (3166, 1587),
  (1741, 1574),
  (3541, 1580),
  (815, 1584),
  (2965, 1571),
  (2819, 1570),
  (1312, 1594),
  (2341, 1560),
  (3669, 1543),
  (934, 1527),
  (97, 1524),
  (635, 1515),
  (3344, 1515),
  (1649, 1498),
  (1441, 1534),
  (1807, 1456),
  (2799, 1461),
  (20, 1415),
  (1208, 1389),
  (665, 1395),
  (1786, 1383),
  (1917, 1376),
  (875, 1372),
  (750, 1364),
  (984, 1396),
  (2580, 1356),
  (3530, 1387),
  (236, 1352),
  (1657, 1373),
  (2277, 1311),
  (389, 1314),
  (2461, 1327),
  (1540, 1302),
  (3747, 1299),
  (3820, 1258),
  (65, 1259),
  (3328, 1284),
  (845, 1255),
  (1730, 1271),
  (1112, 1260),
  (1603, 1230),
  (3063, 1263),
  (1363, 1212),
  (298, 1193),
  (1231, 1193),
  (192, 1193),
  (2253, 1178),
  (2044, 1208),
  (574, 1161),
  (3608, 1139),
  (3754, 1132),
  (1427, 1128),
  (3073, 1138),
  (3223, 1127),
  (2261, 1090),
  (1278, 1096),
  (3696, 1069),
  (2058, 1069),
  (3353, 1052),
  (1860, 1042),
  (1152, 1034),
  (667, 1032),
  (20, 1015),
  (927, 1007),
  (272, 1013),
  (3482, 998),
  (790, 995),
  (1683, 986),
  (1008, 941),
  (2434, 948),
  (3663, 940),
  (576, 939),
  (3033, 919),
  (1908, 943),
  (3760, 950),
  (1554, 908),
  (1024, 889),
  (729, 896),
  (3383, 877),
  (3230, 880),
  (645, 856),
  (2419, 849),
  (2138, 827),
  (3149, 822),
  (910, 792),
  (37, 809),
  (167, 805),
  (1051, 773),
  (1220, 778),
  (3787, 756),
  (2383, 743),
  (851, 742),
  (2150, 738),
  (137, 710),
  (942, 718),
  (3393, 712),
  (3248, 697),
  (2667, 694),
  (2547, 681),
  (2273, 674),
  (2020, 676),
  (1155, 648),
  (3658, 630),
  (2422, 630),
  (3320, 599),
  (545, 613),
  (963, 611),
  (2751, 585),
  (49, 600),
  (1782, 606),
  (323, 542),
  (3739, 536),
  (2348, 528),
  (218, 511),
  (881, 453),
  (3560, 432),
  (159, 432),
  (2750, 426),
  (3785, 421),
  (2006, 406),
  (1813, 387),
  (2291, 408),
  (1709, 373),
  (2659, 360),
  (228, 355),
  (85, 333),
  (834, 315),
  (1159, 290),
  (1933, 276),
  (2114, 266),
  (2435, 293),
  (1715, 278),
  (241, 269),
  (2636, 247),
  (83, 257),
  (3342, 239),
  (1058, 247),
  (2017, 238),
  (2335, 218),
  (541, 213),
  (3634, 207),
  (3807, 188),
  (1242, 164),

In [47]:
tp_config

(0.25, 0.4)

In [48]:
import trackpy as tp

In [49]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [50]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

618
595
663
355
396
581
366
494
632
645
560
505
605
496
679
607
563
556
503
602
629
646
613
712
612
614
628
668
638
581
595
650
623
604
609
656
589
650
580
641
440
658
596
358
273
423
318
503
635
591
612
608
588
509
582
504
596
614
640
603
409
524
480
465
458
437
384
508
462
503
508
173
494
499
438
556
394
512
458
317
505
504
453
485

In [51]:
tp_list

[array([[1410.71598755,   63.06070905],
        [ 709.62706015,   93.14249054],
        [1010.71804703,   55.49054192],
        ...,
        [2034.56892418, 3750.14726586],
        [2698.26066336, 3777.33401698],
        [3684.32213121, 3778.60460844]]),
 array([[1978.33010468,   42.72815073],
        [2197.74021323,   54.21038496],
        [  85.98407938,   83.16435262],
        ...,
        [ 472.76550267, 3762.84470403],
        [1674.08774373, 3784.79294336],
        [2778.21281589, 3782.62998198]]),
 array([[ 288.54904646,   59.36613166],
        [ 923.0413086 ,   82.03322863],
        [2100.67181186,   55.22319706],
        ...,
        [1244.70853754, 3786.91668383],
        [2746.80252149, 3780.3339064 ],
        [3689.21310824, 3779.25910626]]),
 array([[1258.35277059,   67.9265044 ],
        [2248.0585921 ,   52.28242562],
        [1065.74275194,  134.77632002],
        [1748.31943948,   97.22520912],
        [2389.80184237,   93.71783009],
        [3447.88511568,  173.35820174],
        [3306.17734082,  195.26832453],
        [ 166.23753553,  160.1997388 ],
        [3225.82020901,  195.52318222],
        [2674.48874723,  178.5119204 ],
        [3012.49129282,  147.49302272],
        [2402.10512807,  232.43764632],
        [ 612.39467516,  212.09216753],
        [1777.0971098 ,  199.53001667],
        [2713.06698334,  286.09908339],
        [1028.07541074,  231.33136422],
        [ 382.11620058,  244.89757542],
        [1577.75312012,  253.5507427 ],
        [3589.32828866,  304.28068737],
        [ 737.03072234,  329.37269471],
        [2976.33205713,  284.04813127],
        [ 820.9932541 ,  280.43752008],
        [2528.3723804 ,  356.62610204],
        [1247.42949949,  313.31696013],
        [2362.68526731,  298.08891761],
        [2836.86338148,  311.42574919],
        [1368.62978309,  369.96409132],
        [1752.66607784,  347.63579266],
        [1849.75326359,  367.30353592],
        [3329.17487939,  330.89629294],
        [2403.23007796,  393.92303852],
        [1075.49957408,  366.99384051],
        [1953.20518075,  398.19206971],
        [3483.64437756,  355.4778132 ],
        [ 952.47997049,  433.18673032],
        [3766.60984024,  368.05958636],
        [1484.1926231 ,  443.83775236],
        [2273.5276393 ,  395.00678795],
        [1198.85286783,  410.69256683],
        [2830.55523555,  443.75464582],
        [ 752.95676365,  456.43955025],
        [2155.65842953,  493.75007681],
        [1865.87079616,  504.47453291],
        [ 306.14844253,  448.78186541],
        [2508.44535036,  506.47143243],
        [2630.26542688,  472.98474419],
        [2387.71177197,  445.97436204],
        [1348.08993469,  553.28048922],
        [ 944.369156  ,  501.72500091],
        [1573.70908529,  536.44471925],
        [2225.63698069,  556.92334699],
        [2055.99511784,  505.4725468 ],
        [2923.21684018,  544.67867756],
        [3196.75946805,  562.24172621],
        [ 777.05829499,  593.39958893],
        [3275.37357551,  571.3197375 ],
        [ 127.31496323,  620.43740547],
        [3067.9287514 ,  573.66216789],
        [1532.03466022,  575.15239996],
        [ 618.02207861,  579.7872691 ],
        [ 407.16578881,  662.36153212],
        [2499.12531628,  624.85071757],
        [2761.96318736,  681.85075543],
        [3200.84990136,  691.21255049],
        [1982.05619195,  639.78442249],
        [ 896.42452639,  652.08878851],
        [3725.45902435,  630.35118518],
        [  90.31262375,  653.8158927 ],
        [ 303.08705362,  670.16410908],
        [2577.239055  ,  675.93592242],
        [ 749.67170242,  674.60885057],
        [1044.92315649,  681.61102823],
        [1804.23661605,  704.84802345],
        [3246.36027179,  734.22531444],
        [3621.45198498,  728.79383789],
        [1553.3290488 ,  724.61733432],
        [3407.4347389 ,  769.98122119],
        [1317.43294386,  724.73555302],
        [2746.67819316,  746.77773325],
        [2694.36504515,  775.65557429],
        [2391.01798408,  778.76044925],
        [ 121.45513287,  884.62940017],
        [1587.23860427,  840.76548966],
        [1285.31722396,  825.09910657],
        [2199.64061534,  854.56562049],
        [1733.18738128,  839.14353175],
        [2825.56424069,  878.07871633],
        [3460.93275604,  863.76213648],
        [2891.10171816,  900.79228846],
        [1974.69342817,  851.49114175],
        [2518.46083713,  902.25133093],
        [ 931.7932192 ,  975.5782861 ],
        [ 775.15761759,  947.23511839],
        [ 279.97513226,  965.24931552],
        [1578.17375915,  986.16206913],
        [2228.47321906, 1001.29831052],
        [ 499.28063299,  979.69354189],
        [1994.43644333,  988.17414597],
        [3697.3916618 ,  971.95353836],
        [2641.22988851,  985.51356112],
        [2831.92182661,  990.29226537],
        [ 163.93989385, 1029.50657517],
        [3318.36377168, 1007.34531517],
        [1806.43664018, 1007.1904298 ],
        [2408.51075677, 1021.09296019],
        [2232.36080412, 1093.73790424],
        [1698.71873014, 1095.24556401],
        [1227.60806316, 1095.70889272],
        [1111.13452569, 1148.13383623],
        [  61.22133819, 1161.98700273],
        [1873.42521259, 1109.03052627],
        [1545.72999117, 1161.96821619],
        [3401.08084968, 1139.73922616],
        [3752.66396733, 1166.88498726],
        [ 893.34887223, 1147.84759924],
        [3047.52297658, 1156.10828639],
        [3584.68977397, 1256.59331388],
        [1227.90555752, 1208.97282033],
        [1043.80445041, 1231.50101718],
        [2621.12283039, 1284.48280967],
        [2061.03712265, 1266.62628275],
        [2938.59287594, 1244.8951044 ],
        [3485.06907024, 1228.70277215],
        [  94.96553649, 1250.55661248],
        [1983.61811506, 1302.21467724],
        [1333.32815945, 1262.58497222],
        [ 891.45447662, 1319.14640416],
        [2442.65769517, 1289.13768855],
        [2327.16629692, 1302.92187054],
        [2203.2616913 , 1358.03473064],
        [3346.730377  , 1319.34256467],
        [3694.16335271, 1337.07498725],
        [2559.09023341, 1371.19938202],
        [1220.14744227, 1368.62675128],
        [ 987.61903409, 1371.41818182],
        [3038.52254112, 1396.03431151],
        [ 860.46681202, 1396.36746162],
        [1453.1016444 , 1369.24719515],
        [ 191.98828923, 1389.59863006],
        [3226.92694119, 1409.77925371],
        [2309.7878189 , 1444.73140496],
        [1115.36549048, 1403.60888678],
        [2707.33147677, 1413.72216168],
        [2921.1541413 , 1487.40670615],
        [2218.17000304, 1439.35901024],
        [3559.76829487, 1470.04058225],
        [1292.80070318, 1475.72341628],
        [3635.5942988 , 1460.48300185],
        [ 347.16677987, 1511.30095842],
        [ 108.42954296, 1487.67137112],
        [1785.39704566, 1554.76309311],
        [ 876.95601255, 1514.53988049],
        [2361.3381389 , 1524.52549268],
        [3157.98217106, 1510.09037927],
        [1465.99532628, 1597.0989418 ],
        [ 288.65516175, 1562.6323581 ],
        [ 576.05496994, 1584.56938508],
        [2472.52808632, 1531.76926093],
        [1090.28217334, 1580.57739659],
        [2081.19620924, 1629.83194772],
        [ 685.48570921, 1634.1677557 ],
        [1278.5950422 , 1594.7911506 ],
        [3322.45327973, 1612.97293852],
        [3488.74156999, 1615.42429059],
        [2704.48382945, 1655.09112799],
        [ 287.65342682, 1664.72650923],
        [2949.3566612 , 1635.130551  ],
        [1765.09857852, 1707.55672042],
        [ 147.67917279, 1668.9440544 ],
        [1717.38635475, 1714.18934356],
        [ 737.12789905, 1684.62032742],
        [1134.97581659, 1709.75186445],
        [1409.34380495, 1708.74323471],
        [3643.2455274 , 1794.52144498],
        [ 291.00387618, 1801.68413704],
        [1303.22235425, 1736.74199937],
        [ 511.55276961, 1809.02481306],
        [2474.78716452, 1774.79245283],
        [2773.77439509, 1821.81173085],
        [1901.49542596, 1829.23220738],
        [2939.95644631, 1787.51373018],
        [3435.23903831, 1819.33771513],
        [3387.38391236, 1806.92808911],
        [2284.27678261, 1838.0892947 ],
        [1159.3942428 , 1831.71202465],
        [2121.34604651, 1809.8862254 ],
        [ 453.44097082, 1839.98143119],
        [1484.22742745, 1848.13523337],
        [ 623.12545132, 1847.69971825],
        [ 248.73235905, 1840.82283831],
        [3775.31069094, 1900.88667134],
        [2170.64087215, 1952.23976214],
        [3492.22764446, 1911.38669169],
        [2756.2805039 , 1918.90599897],
        [3592.70699654, 1906.09754266],
        [2013.81872487, 1920.86644457],
        [2379.72923738, 1939.90087968],
        [ 176.15624001, 1981.92857503],
        [ 410.74116128, 1981.5187563 ],
        [ 704.1065962 , 1982.43551376],
        [1326.38869946, 2018.67568689],
        [ 907.52365828, 2072.840215  ],
        [2742.77741402, 2028.97274232],
        [3288.40492719, 2073.06557345],
        [2561.40485975, 2055.68241915],
        [2138.47339637, 2042.08696207],
        [1584.71045675, 2094.76780731],
        [1869.16979279, 2114.3964647 ],
        [3456.8       , 2128.36603922],
        [2425.89761405, 2118.48911904],
        [1034.72990427, 2107.78725564],
        [1959.99428836, 2156.70687609],
        [1260.63003892, 2139.45609952],
        [ 188.20909951, 2123.21452839],
        [3206.42252533, 2135.61278254],
        [1151.66086304, 2163.12074103],
        [2564.4083256 , 2155.95530388],
        [3720.3493351 , 2153.81265843],
        [ 751.54618044, 2234.93019427],
        [ 434.24211465, 2237.221033  ],
        [1610.58040492, 2211.28590022],
        [3523.74504771, 2182.30969689],
        [3624.23247978, 2206.46799191],
        [ 857.5801718 , 2212.21259843],
        [2233.78291447, 2267.5621007 ],
        [3015.52390442, 2287.25160271],
        [1334.7295746 , 2279.54455526],
        [2374.23093117, 2287.68979757],
        [3785.1896687 , 2348.04212832],
        [2068.27403088, 2315.26467892],
        [ 760.20224533, 2312.42694395],
        [1026.13155129, 2286.10022011],
        [2465.19994393, 2320.15167516],
        [ 701.86349963, 2353.39469469],
        [1363.01891769, 2411.02270948],
        [1776.79485738, 2370.08166801],
        [2928.75227427, 2370.04954515],
        [1145.36714412, 2402.83514548],
        [2614.44125747, 2438.91139921],
        [ 167.87494167, 2421.81541231],
        [ 826.93047734, 2442.98042371],
        [3027.63750517, 2464.3267792 ],
        [ 220.79025972, 2566.45024661],
        [1717.18791572, 2564.16320464],
        [ 361.79795391, 2561.93642077],
        [1259.11211864, 2499.42623774],
        [ 572.80399949, 2545.6077426 ],
        [1127.44856444, 2541.82877851],
        [2883.85517241, 2530.5807777 ],
        [2337.43362504, 2546.74822011],
        [2576.1434444 , 2552.9624982 ],
        [ 470.9577656 , 2622.0835291 ],
        [ 689.99585936, 2595.25243877],
        [1464.58244749, 2638.02355642],
        [ 345.3965108 , 2634.34895445],
        [1716.87026648, 2631.31234222],
        [1861.25646722, 2660.35606431],
        [ 208.69674842, 2662.41642437],
        [2519.87207088, 2696.01352349],
        [2996.27325572, 2732.88030234],
        [3242.26080816, 2689.20571257],
        [1040.9497264 , 2723.86901505],
        [1288.63414955, 2706.93805951],
        [2448.56422869, 2774.79872591],
        [1807.05808145, 2752.99381932],
        [1996.68668968, 2743.44718067],
        [ 511.34423258, 2734.89204169],
        [1484.55842575, 2761.62967882],
        [3458.72971849, 2758.64415476],
        [2614.00368615, 2807.43443918],
        [3299.42040734, 2780.12625393],
        [1615.26326821, 2779.07311143],
        [ 214.33741539, 2781.3081176 ],
        [1728.61240894, 2887.3162522 ],
        [1498.78867944, 2881.80797046],
        [2641.71817784, 2890.28015769],
        [3468.82663003, 2877.74862094],
        [ 581.34157784, 2889.35171571],
        [ 940.89572299, 2865.26575742],
        [2589.14273319, 2886.32395977],
        [1659.73490287, 2964.89741703],
        [3644.9692655 , 2950.34076564],
        [2103.16572187, 2926.10510188],
        [2752.06468923, 3019.66817363],
        [1743.90202474, 2999.52703198],
        [3073.45603364, 2979.07448362],
        [ 305.707995  , 3062.3471268 ],
        [1356.51447379, 3000.70450349],
        [ 690.27400497, 3046.8875219 ],
        [3567.28859331, 3051.64578799],
        [1473.16809869, 3079.29200658],
        [2827.70525814, 3092.41922022],
        [3204.9846102 , 3068.30294142],
        [ 997.19124573, 3086.96913842],
        [2633.82021525, 3090.7558999 ],
        [ 349.9048418 , 3107.99864174],
        [2438.85500892, 3090.97177534],
        [3418.14158891, 3111.33791697],
        [2926.70252259, 3148.76808635],
        [ 150.75310778, 3125.54338818],
        [ 681.82953835, 3157.28306051],
        [ 793.31834529, 3138.01407301],
        [3125.45555032, 3233.83104415],
        [1134.44784697, 3177.68227905],
        [1882.26658493, 3235.53014844],
        [1381.11405344, 3209.04113007],
        [1237.58662559, 3184.19189681],
        [3240.58953887, 3200.79309058],
        [1982.0989553 , 3224.67606509],
        [2796.67218077, 3251.19442489],
        [ 441.05230226, 3290.95770915],
        [2986.73043236, 3252.18724919],
        [2545.08878513, 3313.05232612],
        [2154.57642074, 3343.65811128],
        [3165.09235704, 3336.40924676],
        [1616.61359498, 3319.75628835],
        [ 288.26103209, 3331.54367893],
        [ 533.86899563, 3370.28179307],
        [2830.43861833, 3400.56881648],
        [1083.54699715, 3431.11870879],
        [2461.56470522, 3438.02563667],
        [2617.38689127, 3445.69481968],
        [1254.78898415, 3462.55243088],
        [1618.27089074, 3533.38930804],
        [2244.26528743, 3540.68115991],
        [1849.45003058, 3493.63423086],
        [3199.97023049, 3532.31080255],
        [ 811.71486133, 3548.47384326],
        [ 333.5274554 , 3518.30295511],
        [2957.72304715, 3538.74656122],
        [ 678.97160123, 3542.20642176],
        [1746.14416219, 3587.43757536],
        [1138.91611293, 3597.28306799],
        [2651.17114484, 3610.29141976],
        [2544.99631439, 3611.30779121],
        [2090.8200426 , 3672.88450496],
        [ 919.23599471, 3614.0648033 ],
        [1316.78682736, 3606.17305302],
        [1880.9724406 , 3616.15272868],
        [ 160.79254371, 3613.83662158],
        [1496.36071117, 3632.28706783],
        [ 545.00495022, 3635.84233458],
        [2249.09132485, 3714.0746034 ],
        [1613.64739171, 3648.2963796 ],
        [2981.11721407, 3685.1756942 ],
        [1123.97182871, 3721.32348549],
        [ 712.41827819, 3686.8154268 ],
        [2815.12066478, 3729.7263081 ],
        [2603.9756382 , 3737.25742589],
        [ 358.16338938, 3758.64365128],
        [ 146.36501444, 3747.68573478],
        [2493.58066522, 3741.84830588],
        [1429.43431489, 3747.46072835],
        [2378.49987085, 3787.24711399],
        [1301.47125338, 3786.90731008]]),
 array([[1729.45952022,   50.28146011],
        [3010.17761523,   58.04295904],
        [2009.73703329,   95.33602966],
        [ 241.89246601,   66.01764057],
        [ 885.78697152,  152.96274093],
        [2309.58592533,   72.15636772],
        [2423.70574425,   69.1484322 ],
        [ 693.28432371,   92.60974679],
        [1605.18333437,  167.57040831],
        [ 119.48769354,  141.67159173],
        [ 564.50116331,  182.84883587],
        [2073.39554849,  185.38108108],
        [1302.4757303 ,  124.64065876],
        [1071.20377085,  131.82932296],
        [2912.37693117,  210.87088894],
        [2215.79682188,  208.84868369],
        [3286.22345694,  151.63232274],
        [3052.22446319,  145.56242331],
        [1961.82225761,  149.65733625],
        [ 372.42024826,  195.79419799],
        [1669.29772437,  218.04164438],
        [ 689.12831544,  267.73389769],
        [1833.47105343,  224.01935127],
        [2263.05101915,  280.5289685 ],
        [2756.95807135,  278.35346531],
        [1435.15267725,  328.82663231],
        [3197.35444818,  260.89293794],
        [3673.69063328,  257.46499502],
        [2389.59480565,  260.46552602],
        [1189.47000427,  304.67566013],
        [1611.773184  ,  296.12266359],
        [ 807.30497398,  286.4473056 ],
        [3040.03843426,  289.23514395],
        [2173.61992395,  368.0313676 ],
        [ 397.32128482,  421.52482046],
        [ 919.7732599 ,  356.6010424 ],
        [1751.95764399,  356.15088875],
        [1369.36988124,  407.14765902],
        [2124.85424079,  395.07730227],
        [2329.39077583,  378.51655345],
        [3383.02170738,  400.26639943],
        [2790.69460347,  429.81413633],
        [ 241.93754298,  474.26584685],
        [2468.46928204,  459.3030484 ],
        [1305.25142878,  533.09457616],
        [1130.24212103,  522.1520028 ],
        [2836.83421418,  557.15474328],
        [3590.86537944,  541.91987862],
        [1843.14904459,  512.28062945],
        [2607.94278831,  549.69069716],
        [1461.01198526,  512.69171049],
        [2342.60323376,  581.56090253],
        [2087.25490196,  512.65063881],
        [2253.266157  ,  530.30989681],
        [1964.48184015,  526.20206823],
        [3671.8706554 ,  538.76355332],
        [ 418.95434444,  570.78086611],
        [3184.87056965,  589.32706048],
        [3250.91662552,  603.26055267],
        [ 652.49175561,  639.14086508],
        [3376.61573702,  572.08335185],
        [3539.32901415,  615.00136178],
        [ 152.01008856,  590.96788602],
        [ 474.42007379,  617.3135127 ],
        [1195.29524461,  637.25940814],
        [1058.5294174 ,  688.85586592],
        [ 847.11516253,  648.15337702],
        [1527.65863675,  651.5826447 ],
        [2687.70864868,  660.47983339],
        [2929.98730327,  697.54781114],
        [3078.39179668,  737.59302131],
        [1262.26493277,  687.35190655],
        [ 530.35426818,  769.37057357],
        [3305.35171623,  716.02449462],
        [2086.40250801,  714.61112247],
        [2481.98964164,  777.56749499],
        [3615.58970947,  745.20754047],
        [2320.5590342 ,  723.6495869 ],
        [3475.56757776,  816.90611737],
        [ 417.06320682,  765.43075136],
        [1908.2603542 ,  835.12767706],
        [3693.75533888,  805.00651605],
        [2203.39527547,  858.02162717],
        [ 825.66195069,  813.65192086],
        [2792.34515788,  825.42613722],
        [3381.49695766,  860.48002733],
        [1998.27162995,  833.54081202],
        [3082.65339633,  830.6541868 ],
        [ 719.61663263,  844.43639447],
        [ 443.31005273,  893.95407549],
        [2691.98310896,  920.30376839],
        [3228.30195875,  849.48393136],
        [3609.50506512,  911.94871563],
        [1692.0027848 ,  856.31285039],
        [ 573.83645166,  882.21124839],
        [ 654.18987532,  972.69242902],
        [2407.28996028,  947.87336373],
        [1300.28912102,  918.01752457],
        [2148.08363469,  935.32329542],
        [ 853.79561666,  947.83772301],
        [3722.18463415,  943.09416527],
        [3164.96324297,  990.14788335],
        [1444.28895324, 1019.64223396],
        [2557.72498942,  963.37159588],
        [1811.92380952,  981.70937531],
        [3607.04581662, 1025.36033321],
        [ 133.69784956,  997.24025043],
        [ 447.13757284,  991.9973495 ],
        [3315.6372267 , 1010.38837745],
        [1004.73101885, 1001.4340991 ],
        [3136.92395732, 1034.56124943],
        [1944.73648811, 1101.2462853 ],
        [1267.82080402, 1070.95767674],
        [1510.31984739, 1094.04371672],
        [1650.09653673, 1082.81695916],
        [3606.02806931, 1091.11119764],
        [3317.86096864, 1124.29509194],
        [ 356.7231313 , 1173.3624072 ],
        [2743.07885312, 1131.87764505],
        [3714.3625    , 1148.2953125 ],
        [ 631.77274488, 1110.30016555],
        [2951.68799351, 1142.48335916],
        [  94.26570215, 1134.9693977 ],
        [1768.26359892, 1194.27378416],
        [1498.5143774 , 1216.52331215],

In [52]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [53]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [54]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1538.715988,191.060709,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,837.627060,221.142491,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1138.718047,183.490542,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3059.542685,188.432531,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,1469.926443,223.856439,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
45131,1623.702271,3861.517504,00480@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
45132,3369.809722,3911.192226,00481@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
45133,3449.998075,3855.981688,00482@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
45134,1527.914020,3905.324243,00483@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
45135,2610.550629,3894.195669,00484@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [55]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [56]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [57]:
nms_config

(0.5, 0.6)

In [58]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [59]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 659
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3476
Number of Particles: 613
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3482
Number of Particles: 699
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3211
Number of Particles: 463
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3262
Number of Particles: 449
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3447
Number of Particles: 629
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3129
Number of Particles: 454
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3434
Number of Particles: 527
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3478
Number of Particles: 662
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3485
Number of Particles: 667
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3299
Number of Particles: 613
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3448
Number of Particles: 522
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3484
Number of Particles: 630
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3410
Number of Particles: 519
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3489
Number of Particles: 714
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3481
Number of Particles: 645
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 595
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3171
Number of Particles: 597
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3184
Number of Particles: 554
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 638
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3483
Number of Particles: 663
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 679
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3347
Number of Particles: 656
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 763
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3461
Number of Particles: 651
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 656
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3481
Number of Particles: 659
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3482
Number of Particles: 706
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 699
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 616
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3477
Number of Particles: 642
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 713
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3483
Number of Particles: 657
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 647
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 640
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3484
Number of Particles: 691
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 622
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3490
Number of Particles: 675
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3346
Number of Particles: 607
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3456
Number of Particles: 672
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2964
Number of Particles: 525
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3477
Number of Particles: 704
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 617
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3208
Number of Particles: 431
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2956
Number of Particles: 510
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3373
Number of Particles: 475
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3231
Number of Particles: 480
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3408
Number of Particles: 526
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3488
Number of Particles: 666
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 633
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 635
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 617
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3453
Number of Particles: 518
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 614
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3374
Number of Particles: 530
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3463
Number of Particles: 636
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3442
Number of Particles: 659
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3411
Number of Particles: 717
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 674
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3269
Number of Particles: 482
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 557
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3420
Number of Particles: 522
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3410
Number of Particles: 479
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3406
Number of Particles: 489
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3389
Number of Particles: 471
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3261
Number of Particles: 460
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3449
Number of Particles: 549
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3389
Number of Particles: 516
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3405
Number of Particles: 534
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3359
Number of Particles: 562
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2467
Number of Particles: 559
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3438
Number of Particles: 538
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 532
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3326
Number of Particles: 500
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3470
Number of Particles: 582
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3288
Number of Particles: 460
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3424
Number of Particles: 563
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3420
Number of Particles: 493
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3073
Number of Particles: 481
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3428
Number of Particles: 557
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3338
Number of Particles: 562
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3324
Number of Particles: 518
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3389
Number of Particles: 569

In [60]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [61]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [62]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,347.8,2891.8,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,2302.4,3760.0,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,2800.0,3095.8,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,2457.0,359.0,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,1138.4,1795.2,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
49501,558.0,3903.8,00564@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49502,1449.0,3264.0,00565@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49503,2752.0,2504.0,00566@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49504,2048.0,3328.0,00567@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49505,511.0,909.0,00568@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [63]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')

In [64]:
# @markdown ---
# @markdown time used
end_time = time.time()
print(f"End time recorded: {end_time}")

elapsed_time = end_time - start_time
elapsed_time = elapsed_time


hours = int(elapsed_time // 3600)
remaining_seconds = elapsed_time % 3600

minutes = int(remaining_seconds // 60)
seconds = round(remaining_seconds % 60, 3)

print(f"Time spend : {hours} h, {minutes} m, {seconds} s")


gpu_used = "L4" # @param ["CPU high", "T4", "T4 high", "L4"]
per_unit_cost_dict = {"L4" : 1.71, "T4 high" : 1.41, "T4" : 1.19, "CPU high" :  0.24}
per_unit_cost = per_unit_cost_dict[gpu_used]
print(f"unit price per hr {per_unit_cost}")

cost_units = per_unit_cost * elapsed_time / 3600

per_unit_US = 10.49 / 100

cost_price_US = cost_units * per_unit_US

print(f"unit cost : {round(cost_units, 4)}")
print(f"unit price US: {cost_price_US}")
print(f"unit price NTD: {cost_price_US * 30.76}")

End time recorded: 1763016012.6490266
Time spend : 0 h, 20 m, 17.167 s
unit price per hr 1.71
unit cost : 0.5782
unit price US: 0.060648411468836066
unit price NTD: 1.8655451367813976