<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [ ]:
%pip install torchinfo -qq
%pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
%pip install starfile -qq
%pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for segmentation_models_pytorch (pyproject.toml) ... done
     \ 10.7 MB 8.8 MB/s 0:00:01
  Preparing metadata (setup.py) ... done
  Building wheel for trackpy (setup.py) ... done

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [ ]:
%pip install pycuda==2024.1
%pip install "numpy<2.0"
%pip install mrcfile -qq

Collecting pycuda==2024.1
  Downloading pycuda-2024.1.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 46.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytools>=2011.2 (from pycuda==2024.1)
  Downloading pytools-2025.2.4-py3-none-any.whl.metadata (2.9 kB)
Collecting appdirs>=1.4.0 (from pycuda==2024.1)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: mako in /usr/local/lib/python3.12/dist-packages (from pycuda==2024.1) (1.3.10)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.4.0)
Collecting siphash24>=1.6 (from pytools>=2011.2->pycuda==2024.1)
  Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: typing-extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.15.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from mako->pycuda==2024.1) (3.0.3)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading pytools-2025.2.4-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.4/99.4 kB 9.7 MB/s eta 0:00:00
Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 11.0 MB/s eta 0:00:00
Building wheels for collected packages: pycuda
  Building wheel for pycuda (pyproject.toml) ... done
  Created wheel for pycuda: filename=pycuda-2024.1-cp312-cp312-linux_x86_64.whl size=658547 sha256=47cb717dfaacbf638695a2fc53a52424ed2593a586400f73c91b33c42a6644ab
  Stored in directory: /root/.cache/pip/wheels/16/8d/d0/cf29b67ddc32f77bc3344b6b2b38dd9fe8595c726c33eabc03
Successfully built pycuda
Installing collected packages: appdirs, siphash24, pytools, pycuda
Successfully installed appdirs-1.4.4 pycuda-2024.1 pytools-2025.2.4 siphash24-1.8
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.6 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 137.2 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.5 MB/s eta 0:00:00

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [ ]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_output/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_output/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_output/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_output/results/10017_test/unet_eb5_dice_CDCRF" # @param {type:"string"}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
IMAGE_DIR = "/content/image_dir"

In [ ]:
!git clone https://github.com/phonchi/CryoParticleSegment.git

Cloning into 'CryoParticleSegment'...
remote: Enumerating objects: 270, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 270 (delta 141), reused 42 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (270/270), 32.01 MiB | 12.12 MiB/s, done.
Resolving deltas: 100% (141/141), done.

In [ ]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

> #### ⚠ Notice
>
> You need to restart the kernel after the compilation step. Additionally, if your GPU architecture differs, you may need to modify the file at `/content/CryoParticleSegment/Modeling/CRF_main/setup.py`. (We attempt to detect the GPU configuration automatically, so this step is usually not necessary.)
> Furthermore, depending on the number of classes and other parameters, you may encounter an error that requires adjusting the file at `/content/CryoParticleSegment/Modeling/CRF_main/src/PermutohedralFiltering/source/gpu/LatticeFilter.cu`:
>
> 1. Note the `pd` and `vd` values from the error message.
> 2. Add an `else if (pd == ? && vd == ?)` block.
> 3. Within that block, insert the following line, replacing `pd` and `vd` with the specific values:
>
>    ```cpp
>    latticeFilterGPU<pd, vd>(output_tensor, input_tensor, positions, num_super_pixels, backward);
>    ```
> 4. Recompile using `setup.py`.

In [ ]:
#%git clone https://github.com/netw0rkf10w/CRF.git
%cd CryoParticleSegment/Modeling/CRF_main
!python setup.py clean --all
!rm -rf build/
!python setup.py build_ext --inplace --force
!python setup.py install

/content/CryoParticleSegment/Modeling/CRF_main
running clean
'build/lib.linux-x86_64-cpython-312' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.12' does not exist -- can't clean it
running build_ext
W1005 12:15:29.151000 7265 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
W1005 12:15:29.225000 7265 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1005 12:15:29.226000 7265 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
building 'Permutohedral' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral -std=c++17
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp: In function ‘at::Tensor LatticeFilter_calculate(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool)’:
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:77:97: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
   77 |         at::Tensor positions = at::zeros({batch_size * num_super_pixels * pd}, input_tensor.type() );
      |                                                                                ~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/extension.h:5,
                 from src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:25:
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
creating build/lib.linux-x86_64-cpython-312
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so
building 'Permutohedral_gpu' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/cuda/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/gpu/LatticeFilter.cu -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -gencode=arch=compute_89,code=sm_89 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral_gpu -std=c++17
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu: In function ‘at::Tensor LatticeFilter_calculate_gpu(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool, bool)’:
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:202:91: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  202 |     at::Tensor positions = at::zeros(
      |                                                                                           ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:208:67: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  208 |     CHECK_INPUT(image_tensor);
      |                                                                   ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:209:64: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  209 |     CHECK_INPUT(positions);
      |                                                                ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:213:44: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  213 |         auto ref_ptr = &(image_tensor.data<float>()[b * num_super_pixels * n_reference_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:214:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  214 |         auto pos_ptr = &(positions.data<float>()[b * num_super_pixels * pd]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:215:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  215 |         auto in_ptr = &(input_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:216:45: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  216 |         auto out_ptr = &(output_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> src
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> src
running install
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating src/CRF.egg-info
writing src/CRF.egg-info/PKG-INFO
writing dependency_links to src/CRF.egg-info/dependency_links.txt
writing top-level names to src/CRF.egg-info/top_level.txt
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
W1005 12:17:15.756000 7760 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
reading manifest file 'src/CRF.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/PermutohedralFiltering.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/__init__.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/setup.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
creating build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/sparsemax.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/CRF.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/convcrf.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/crfs_cpu.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/__init__.py -> build/lib.linux-x86_64-cpython-312/CRF
running build_ext
W1005 12:17:15.807000 7760 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1005 12:17:15.808000 7760 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/PermutohedralFiltering.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/__init__.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/setup.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/sparsemax.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/CRF.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/convcrf.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/crfs_cpu.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/__init__.py -> build/bdist.linux-x86_64/egg/CRF
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/PermutohedralFiltering.py to PermutohedralFiltering.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/__init__.py to __init__.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/setup.py to setup.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/sparsemax.py to sparsemax.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/CRF.py to CRF.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/convcrf.py to convcrf.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/crfs_cpu.py to crfs_cpu.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/__init__.py to __init__.cpython-312.pyc
creating stub loader for Permutohedral.cpython-312-x86_64-linux-gnu.so
creating stub loader for Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral.py to Permutohedral.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral_gpu.py to Permutohedral_gpu.cpython-312.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
CRF.__pycache__.crfs_cpu.cpython-312: module references __file__
__pycache__.Permutohedral.cpython-312: module references __file__
__pycache__.Permutohedral_gpu.cpython-312: module references __file__
creating dist
creating 'dist/CRF-0.0.1-py3.12-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CRF-0.0.1-py3.12-linux-x86_64.egg
creating /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Extracting CRF-0.0.1-py3.12-linux-x86_64.egg to /usr/local/lib/python3.12/dist-packages
Adding CRF 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Processing dependencies for CRF==0.0.1
Finished processing dependencies for CRF==0.0.1

In [ ]:
%cd /content/

/content

### ✅ Packages Handling

In [ ]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [ ]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [ ]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 8
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [ ]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [ ]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

config.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/122M [00:00<?, ?B/s]

In [ ]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [ ]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [ ]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [ ]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [ ]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [ ]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:28<00:00,  2.99it/s]

In [ ]:
processed_micrographs.shape

(84, 3840, 3840)

In [ ]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [ ]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [ ]:
del model
torch.cuda.empty_cache()

In [ ]:
model = model_post

In [ ]:
RESULT_DIR

'/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_output/results/10017_test/unet_eb5_dice_CDCRF'

In [ ]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [ ]:
!cp {RESULT_DIR}/label_images.npy .

In [ ]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [ ]:
label_images.shape

(84, 3840, 3840)

In [ ]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [ ]:
!cp {RESULT_DIR}/best_config.txt .

In [ ]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [ ]:
radius = RADIUS

In [ ]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [ ]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

604 546
598 569
587 513
407 388
423 398
519 464
3 3
440 410
605 546
652 606
594 548
554 540
565 512
391 387
643 586
625 580
561 538
599 560
589 547
662 617
611 557
608 546
620 558
619 523
567 484
548 480
573 513
621 566
585 528
608 580
637 586
571 485
606 559
610 555
618 568
606 540
581 538
622 570
608 570
606 540
474 422
634 566
607 573
384 369
348 340
389 366
304 301
542 533
579 536
512 447
552 489
543 488
502 481
529 509
527 504
399 378
543 494
628 563
541 466
548 469
402 393
480 450
336 329
329 322
329 322
362 356
445 424
454 428
392 360
436 400
430 401
359 356
452 429
476 431
417 393
500 447
400 379
463 427
407 395
402 392
455 429
458 406
436 389
514 465

In [ ]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [ ]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,423,3950,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1509,3952,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1235,3948,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,248,3947,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3713,3946,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
39516,2363,185,00460@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
39517,1982,173,00461@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
39518,315,147,00462@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
39519,2858,155,00463@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
39520,3594,154,00464@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [ ]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [ ]:
cv_list

[[(295, 3822),
  (1381, 3824),
  (1107, 3820),
  (120, 3819),
  (3585, 3818),
  (626, 3815),
  (2412, 3817),
  (3039, 3812),
  (1188, 3793),
  (2823, 3788),
  (2698, 3788),
  (3685, 3770),
  (234, 3783),
  (1566, 3780),
  (799, 3786),
  (1701, 3765),
  (2953, 3762),
  (977, 3730),
  (1293, 3730),
  (25, 3692),
  (3423, 3689),
  (259, 3687),
  (3778, 3668),
  (2472, 3702),
  (468, 3685),
  (789, 3679),
  (1784, 3684),
  (3706, 3664),
  (365, 3672),
  (1532, 3661),
  (1436, 3668),
  (1137, 3652),
  (2767, 3658),
  (2279, 3643),
  (3053, 3646),
  (1958, 3626),
  (2288, 3612),
  (852, 3631),
  (2364, 3620),
  (2562, 3606),
  (1708, 3569),
  (3690, 3572),
  (995, 3595),
  (3089, 3561),
  (755, 3564),
  (3227, 3546),
  (1127, 3538),
  (3590, 3550),
  (1914, 3537),
  (42, 3532),
  (3536, 3505),
  (2023, 3548),
  (888, 3499),
  (675, 3519),
  (137, 3492),
  (2362, 3490),
  (3001, 3495),
  (1577, 3478),
  (2804, 3446),
  (2776, 3461),
  (604, 3468),
  (3778, 3461),
  (1768, 3449),
  (3380, 3447),
  (762, 3430),
  (1479, 3437),
  (1264, 3427),
  (2264, 3424),
  (3576, 3411),
  (1000, 3417),
  (16, 3410),
  (2530, 3449),
  (2934, 3406),
  (2645, 3411),
  (1921, 3399),
  (517, 3408),
  (2804, 3359),
  (672, 3348),
  (212, 3360),
  (884, 3370),
  (3045, 3351),
  (1598, 3339),
  (2139, 3332),
  (1981, 3324),
  (1299, 3329),
  (3374, 3317),
  (323, 3320),
  (2662, 3305),
  (1071, 3302),
  (3623, 3292),
  (901, 3283),
  (1876, 3267),
  (3068, 3249),
  (1633, 3236),
  (3168, 3229),
  (2810, 3220),
  (325, 3209),
  (1219, 3197),
  (2599, 3210),
  (1422, 3233),
  (505, 3200),
  (3542, 3195),
  (3746, 3194),
  (2696, 3186),
  (2262, 3226),
  (211, 3171),
  (1071, 3171),
  (634, 3213),
  (2146, 3149),
  (3154, 3135),
  (1950, 3167),
  (1599, 3124),
  (792, 3119),
  (283, 3122),
  (1270, 3109),
  (1421, 3110),
  (3559, 3090),
  (3450, 3092),
  (609, 3087),
  (2631, 3090),
  (2305, 3086),
  (1507, 3124),
  (2016, 3051),
  (376, 3047),
  (3647, 3044),
  (3367, 3036),
  (2564, 3032),
  (191, 3052),
  (1347, 3002),
  (3521, 3004),
  (354, 2974),
  (165, 2961),
  (1447, 2960),
  (3140, 2952),
  (3603, 2974),
  (24, 2954),
  (3439, 2963),
  (2313, 2965),
  (3824, 2930),
  (3284, 2947),
  (3749, 2932),
  (2082, 2943),
  (2910, 2943),
  (2787, 2936),
  (2581, 2936),
  (268, 2928),
  (890, 2914),
  (1141, 2880),
  (190, 2869),
  (3030, 2875),
  (3361, 2857),
  (1233, 2857),
  (92, 2853),
  (2702, 2826),
  (2513, 2824),
  (3597, 2819),
  (2299, 2789),
  (871, 2777),
  (45, 2756),
  (3036, 2747),
  (1037, 2753),
  (3397, 2741),
  (3250, 2743),
  (2875, 2750),
  (2174, 2766),
  (2588, 2741),
  (2509, 2730),
  (3696, 2708),
  (1992, 2686),
  (479, 2673),
  (2953, 2658),
  (2091, 2662),
  (3414, 2652),
  (3240, 2648),
  (3558, 2653),
  (1739, 2648),
  (1842, 2672),
  (972, 2635),
  (2272, 2658),
  (254, 2596),
  (35, 2603),
  (1641, 2602),
  (2675, 2596),
  (2524, 2573),
  (1330, 2567),
  (2141, 2588),
  (1547, 2591),
  (3237, 2551),
  (3343, 2552),
  (3801, 2533),
  (2334, 2547),
  (2826, 2534),
  (122, 2540),
  (3698, 2515),
  (1190, 2518),
  (2601, 2511),
  (2260, 2520),
  (399, 2489),
  (1889, 2479),
  (743, 2464),
  (1628, 2469),
  (3542, 2462),
  (1712, 2459),
  (2360, 2446),
  (1327, 2436),
  (2931, 2461),
  (3456, 2425),
  (3151, 2416),
  (125, 2400),
  (1562, 2405),
  (2447, 2406),
  (438, 2392),
  (597, 2404),
  (3740, 2388),
  (3039, 2382),
  (327, 2377),
  (3621, 2371),
  (1406, 2361),
  (2042, 2347),
  (1222, 2396),
  (2838, 2351),
  (1733, 2344),
  (1915, 2348),
  (195, 2335),
  (2650, 2309),
  (51, 2332),
  (3286, 2316),
  (1393, 2290),
  (1088, 2313),
  (1591, 2305),
  (3102, 2313),
  (2354, 2292),
  (359, 2278),
  (594, 2265),
  (994, 2269),
  (507, 2233),
  (3767, 2273),
  (1998, 2238),
  (2759, 2219),
  (1608, 2216),
  (2661, 2216),
  (917, 2212),
  (3250, 2190),
  (2462, 2193),
  (946, 2161),
  (443, 2184),
  (23, 2157),
  (772, 2166),
  (1601, 2137),
  (3004, 2185),
  (642, 2128),
  (3574, 2122),
  (2542, 2105),
  (2344, 2109),
  (3444, 2111),
  (69, 2091),
  (1053, 2087),
  (2156, 2078),
  (25, 2043),
  (2012, 2043),
  (2671, 2089),
  (915, 2045),
  (2573, 2033),
  (3585, 2033),
  (2279, 2002),
  (689, 2035),
  (319, 2025),
  (3778, 2035),
  (1329, 2013),
  (427, 2008),
  (219, 2002),
  (3190, 2015),
  (1447, 1974),
  (825, 1972),
  (3440, 1962),
  (1724, 1973),
  (2593, 1942),
  (3351, 1930),
  (2737, 1950),
  (3741, 1913),
  (1101, 1922),
  (904, 1914),
  (2884, 1904),
  (1298, 1898),
  (3216, 1889),
  (3443, 1872),
  (3654, 1874),
  (91, 1867),
  (670, 1861),
  (1496, 1827),
  (1095, 1818),
  (2754, 1846),
  (2137, 1810),
  (3005, 1811),
  (995, 1804),
  (1395, 1808),
  (2853, 1750),
  (485, 1770),
  (2579, 1777),
  (3087, 1735),
  (2120, 1730),
  (1105, 1727),
  (1582, 1731),
  (47, 1713),
  (831, 1707),
  (2795, 1693),
  (3423, 1688),
  (2652, 1684),
  (1409, 1680),
  (3618, 1684),
  (3814, 1648),
  (3309, 1653),
  (2228, 1659),
  (1937, 1654),
  (1854, 1648),
  (569, 1648),
  (2713, 1626),
  (663, 1640),
  (2989, 1621),
  (342, 1597),
  (3230, 1572),
  (3815, 1551),
  (1361, 1565),
  (156, 1558),
  (3086, 1549),
  (454, 1542),
  (1267, 1542),
  (1894, 1541),
  (2695, 1530),
  (2396, 1562),
  (968, 1521),
  (3711, 1498),
  (3614, 1503),
  (3167, 1497),
  (1460, 1482),
  (878, 1474),
  (207, 1472),
  (2454, 1452),
  (425, 1451),
  (763, 1453),
  (2573, 1396),
  (3736, 1415),
  (1189, 1409),
  (495, 1395),
  (2216, 1398),
  (1397, 1390),
  (1099, 1376),
  (2691, 1388),
  (2319, 1386),
  (2082, 1371),
  (3663, 1385),
  (3616, 1326),
  (788, 1332),
  (2450, 1316),
  (1264, 1321),
  (3290, 1350),
  (1962, 1327),
  (1764, 1338),
  (3176, 1309),
  (2829, 1288),
  (1059, 1292),
  (1446, 1285),
  (3521, 1281),
  (2079, 1275),
  (411, 1266),
  (915, 1257),
  (2609, 1255),
  (3013, 1244),
  (57, 1260),
  (1348, 1238),
  (2281, 1221),
  (1826, 1204),
  (1239, 1218),
  (566, 1212),
  (2526, 1192),
  (1434, 1185),
  (2737, 1177),
  (3822, 1149),
  (2855, 1148),
  (2076, 1157),
  (1521, 1152),
  (3320, 1166),
  (3479, 1137),
  (294, 1126),
  (614, 1124),
  (2996, 1107),
  (1800, 1085),
  (861, 1112),
  (1304, 1077),
  (3143, 1079),
  (495, 1100),
  (2647, 1065),
  (2433, 1062),
  (1062, 1069),
  (1937, 1039),
  (2817, 1023),
  (3226, 1018),
  (1495, 1019),
  (1348, 975),
  (1097, 984),
  (750, 988),
  (2245, 975),
  (63, 973),
  (3408, 962),
  (3070, 961),
  (477, 959),
  (1662, 992),
  (2050, 950),
  (1263, 944),
  (1462, 930),
  (1749, 915),
  (1851, 915),
  (3144, 898),
  (3699, 893),
  (1581, 888),
  (2194, 890),
  (1097, 882),
  (2104, 872),
  (2409, 863),
  (3436, 851),
  (1327, 847),
  (964, 857),
  (448, 829),
  (905, 801),
  (3069, 824),
  (1995, 869),
  (3789, 818),
  (1174, 811),
  (1871, 774),
  (353, 797),
  (3361, 792),
  (2956, 793),
  (2485, 781),
  (1279, 782),
  (2065, 784),
  (927, 766),
  (1656, 765),
  (36, 753),
  (1956, 746),
  (1419, 738),
  (3445, 715),
  (1610, 692),
  (3702, 704),
  (748, 678),
  (167, 675),
  (25, 665),
  (3229, 683),
  (1142, 652),
  (851, 656),
  (3300, 629),
  (539, 644),
  (1801, 643),
  (1032, 631),
  (1518, 618),
  (3152, 600),
  (2481, 612),
  (1327, 619),
  (1652, 602),
  (628, 581),
  (2298, 571),
  (457, 561),
  (3793, 553),
  (40, 558),
  (2617, 535),
  (1602, 545),
  (1978, 561),
  (2385, 538),
  (130, 524),
  (1727, 523),
  (1450, 519),
  (1350, 520),
  (3637, 513),
  (594, 502),
  (3131, 488),
  (3183, 510),
  (1138, 508),
  (2937, 502),
  (479, 481),
  (88, 443),
  (3811, 452),
  (3696, 458),
  (3446, 449),
  (2215, 454),
  (3102, 416),
  (237, 449),
  (2842, 465),
  (1441, 425),
  (348, 420),
  (2296, 404),
  (548, 378),
  (1226, 367),
  (3239, 343),
  (21, 354),
  (1584, 355),
  (1409, 342),
  (1504, 333),
  (957, 329),
  (1777, 309),
  (860, 315),
  (605, 342),
  (3734, 300),
  (178, 285),
  (1642, 294),
  (2107, 290),
  (1883, 272),
  (3536, 270),
  (335, 251),
  (3807, 244),
  (725, 235),
  (1320, 241),
  (1726, 236),
  (883, 214),
  (1620, 200),
  (1131, 212),
  (2934, 178),
  (781, 168),
  (1535, 152),
  (1445, 149),
  (3269, 144),
  (2020, 140),
  (2571, 133),
  (169, 118),
  (2179, 111),
  (597, 113),
  (2711, 100),
  (1800, 100),
  (340, 109),
  (1340, 91),
  (713, 95),
  (3487, 87),
  (1014, 69),
  (2934, 61),
  (2820, 82),
  (3216, 50),
  (3096, 27),
  (2996, 70),
  (1872, 35),
  (1195, 86),
  (799, 32),
  (122, 28),
  (2075, 30),
  (3323, 60),
  (3798, 18),
  (2309, 25),
  (1409, 55),
  (3452, 29)],
 [(3233, 3812),
  (3120, 3820),
  (2436, 3819),
  (88, 3814),
  (279, 3814),
  (3385, 3822),
  (729, 3817),
  (3010, 3809),
  (1742, 3805),
  (1456, 3808),
  (3764, 3809),
  (2579, 3805),
  (860, 3808),
  (959, 3801),
  (2167, 3802),
  (1186, 3793),
  (1881, 3790),
  (1655, 3784),
  (3602, 3789),
  (2782, 3787),
  (165, 3781),
  (2263, 3776),
  (505, 3766),
  (1313, 3752),
  (1987, 3732),
  (1578, 3751),
  (3156, 3737),
  (733, 3729),
  (2675, 3723),
  (353, 3722),
  (2427, 3728),
  (1126, 3704),
  (37, 3704),
  (1393, 3701),
  (2083, 3706),
  (969, 3699),
  (2956, 3691),
  (3059, 3664),
  (2761, 3665),
  (109, 3635),
  (2387, 3653),
  (400, 3644),
  (2015, 3641),
  (562, 3637),
  (2839, 3628),
  (1061, 3619),
  (2585, 3619),
  (3198, 3605),
  (3336, 3603),
  (1482, 3591),
  (1340, 3587),
  (249, 3613),
  (2250, 3566),
  (1643, 3561),
  (3626, 3577),
  (2885, 3554),
  (873, 3549),
  (3514, 3542),
  (3043, 3536),
  (758, 3537),
  (2153, 3530),
  (1745, 3522),
  (159, 3481),
  (3433, 3462),
  (2458, 3467),
  (484, 3479),
  (2541, 3468),
  (1861, 3444),
  (3615, 3450),
  (294, 3441),
  (2753, 3436),
  (2329, 3446),
  (1514, 3427),
  (837, 3432),
  (3508, 3421),
  (3302, 3418),
  (2949, 3421),
  (1765, 3415),
  (967, 3400),
  (3174, 3407),
  (1300, 3388),
  (1676, 3380),
  (181, 3365),
  (1227, 3352),
  (1124, 3349),
  (794, 3353),
  (3690, 3344),
  (1854, 3342),
  (2655, 3323),
  (1555, 3331),
  (1337, 3311),
  (964, 3302),
  (3442, 3286),
  (1658, 3262),
  (160, 3270),
  (43, 3255),
  (2574, 3273),
  (3589, 3277),
  (1233, 3246),
  (3780, 3246),
  (3032, 3257),
  (2362, 3269),
  (2166, 3235),
  (800, 3218),
  (2868, 3224),
  (606, 3221),
  (18, 3177),
  (2420, 3188),
  (2708, 3190),
  (1806, 3177),
  (943, 3171),
  (3611, 3166),
  (1309, 3166),
  (1416, 3131),
  (2627, 3123),
  (1013, 3100),
  (3340, 3086),
  (3257, 3104),
  (1123, 3088),
  (3439, 3092),
  (1905, 3090),
  (572, 3081),
  (2729, 3079),
  (312, 3090),
  (2120, 3061),
  (2882, 3075),
  (79, 3069),
  (893, 3020),
  (1218, 3020),
  (1453, 3017),
  (2261, 3018),
  (229, 3017),
  (3097, 3017),
  (2009, 3001),
  (3727, 2971),
  (3012, 2975),
  (792, 2963),
  (3275, 2944),
  (43, 2941),
  (1808, 2941),
  (1563, 2922),
  (2083, 2926),
  (2429, 2933),
  (1903, 2909),
  (3441, 2897),
  (2308, 2903),
  (1274, 2875),
  (3819, 2876),
  (3575, 2885),
  (565, 2871),
  (2173, 2867),
  (2919, 2868),
  (3171, 2852),
  (1368, 2844),
  (239, 2848),
  (856, 2856),
  (3653, 2827),
  (2105, 2812),
  (503, 2812),
  (3395, 2814),
  (2347, 2810),
  (1586, 2805),
  (52, 2795),
  (1467, 2796),
  (3814, 2771),
  (2477, 2762),
  (2930, 2767),
  (3233, 2753),
  (3033, 2733),
  (1956, 2745),
  (421, 2740),
  (160, 2720),
  (3726, 2702),
  (516, 2705),
  (1601, 2700),
  (2355, 2688),
  (1703, 2689),
  (3277, 2682),
  (2957, 2681),
  (785, 2648),
  (240, 2664),
  (3065, 2647),
  (46, 2671),
  (111, 2645),
  (1785, 2643),
  (1249, 2628),
  (3661, 2630),
  (1584, 2604),
  (476, 2618),
  (1893, 2597),
  (3498, 2583),
  (3367, 2587),
  (2515, 2582),
  (2733, 2568),
  (1447, 2557),
  (2011, 2574),
  (3243, 2552),
  (3632, 2548),
  (1328, 2523),
  (2900, 2509),
  (151, 2499),
  (1693, 2480),
  (1071, 2493),
  (2435, 2498),
  (1611, 2484),
  (828, 2473),
  (1426, 2466),
  (2752, 2463),
  (3100, 2448),
  (3422, 2453),
  (43, 2441),
  (1983, 2427),
  (3683, 2424),
  (1310, 2421),
  (3556, 2442),
  (3037, 2409),
  (2421, 2399),
  (2065, 2368),
  (1862, 2407),
  (1622, 2369),
  (349, 2354),
  (909, 2361),
  (1732, 2336),
  (2653, 2345),
  (2200, 2326),
  (3504, 2319),
  (809, 2326),
  (3644, 2324),
  (2980, 2307),
  (1128, 2318),
  (259, 2311),
  (149, 2278),
  (2492, 2290),
  (2379, 2280),
  (2608, 2279),
  (104, 2264),
  (2902, 2263),
  (375, 2262),
  (707, 2260),
  (18, 2254),
  (1644, 2254),
  (1317, 2257),
  (2028, 2232),
  (1842, 2233),
  (1821, 2211),
  (985, 2261),
  (3247, 2208),
  (3091, 2231),
  (2655, 2200),
  (1142, 2219),
  (2939, 2183),
  (156, 2189),
  (3448, 2189),
  (1454, 2165),
  (3333, 2159),
  (874, 2150),
  (365, 2138),
  (3207, 2141),
  (83, 2137),
  (2690, 2128),
  (2049, 2109),
  (2392, 2116),
  (3540, 2101),
  (2215, 2125),
  (964, 2110),
  (3644, 2114),
  (247, 2101),
  (706, 2071),
  (3154, 2061),
  (428, 2061),
  (2850, 2056),
  (1642, 2053),
  (3781, 2042),
  (45, 2028),
  (1175, 2034),
  (1530, 2011),
  (2207, 2015),
  (2080, 2015),
  (599, 2005),
  (179, 2026),
  (328, 1979),
  (3570, 1959),
  (2323, 1965),
  (3643, 1955),
  (1768, 1952),
  (2750, 1955),
  (3797, 1931),
  (1152, 1919),
  (3183, 1922),
  (1474, 1925),
  (2194, 1919),
  (3269, 1904),
  (2495, 1914),
  (1898, 1899),
  (813, 1876),
  (2841, 1839),
  (1966, 1835),
  (575, 1845),
  (2608, 1843),
  (1630, 1850),
  (948, 1854),
  (1814, 1811),
  (2155, 1807),
  (2736, 1799),
  (3418, 1778),
  (3314, 1757),
  (150, 1759),
  (2284, 1765),
  (2836, 1740),
  (2678, 1708),
  (3172, 1720),
  (1955, 1718),
  (597, 1728),
  (3010, 1752),
  (762, 1744),
  (2166, 1693),
  (1764, 1691),
  (3460, 1660),
  (22, 1663),
  (2321, 1653),
  (846, 1702),
  (1952, 1643),
  (111, 1642),
  (1615, 1644),
  (1019, 1629),
  (2702, 1621),
  (1412, 1609),
  (3245, 1602),
  (3167, 1586),
  (1722, 1578),
  (2267, 1572),
  (3019, 1559),
  (3667, 1552),
  (518, 1555),
  (1465, 1551),
  (3558, 1521),
  (73, 1545),
  (2666, 1532),
  (2517, 1537),
  (2111, 1524),
  (155, 1511),
  (1192, 1532),
  (3349, 1554),
  (3080, 1508),
  (2770, 1511),
  (1886, 1484),
  (2906, 1493),
  (1119, 1495),
  (421, 1483),
  (1011, 1477),
  (1314, 1478),
  (1724, 1472),
  (2197, 1457),
  (3007, 1438),
  (3671, 1437),
  (3506, 1460),
  (850, 1422),
  (3100, 1418),
  (238, 1400),
  (756, 1376),
  (989, 1392),
  (121, 1371),
  (3742, 1390),
  (1079, 1380),
  (1551, 1374),
  (1769, 1354),
  (2826, 1380),
  (16, 1339),
  (1649, 1362),
  (2232, 1321),
  (2556, 1297),
  (3363, 1301),
  (919, 1288),
  (377, 1288),
  (1196, 1282),
  (2948, 1254),
  (2108, 1258),
  (238, 1248),
  (2392, 1247),
  (1504, 1230),
  (2291, 1226),
  (3751, 1214),
  (2722, 1202),
  (1357, 1203),
  (1884, 1201),
  (112, 1224),
  (1058, 1203),
  (217, 1167),
  (1469, 1157),
  (3599, 1187),
  (2711, 1127),
  (469, 1134),
  (667, 1137),
  (2845, 1159),
  (805, 1118),
  (3087, 1112),
  (1654, 1113),
  (3215, 1151),
  (2256, 1144),
  (3767, 1099),
  (1165, 1071),
  (1958, 1065),
  (922, 1074),
  (557, 1067),
  (44, 1056),
  (367, 1051),
  (3604, 1051),
  (1897, 1018),
  (1385, 1019),
  (2064, 1029),
  (2950, 1020),
  (3723, 1001),
  (950, 984),
  (1801, 946),
  (3401, 947),
  (733, 974),
  (3032, 959),
  (2602, 945),
  (194, 945),
  (622, 959),
  (1605, 982),
  (3581, 952),
  (2354, 938),
  (2494, 914),
  (1358, 918),
  (3757, 925),
  (3132, 912),
  (2078, 895),
  (1110, 873),
  (3620, 854),
  (2902, 881),
  (1584, 859),
  (3039, 848),
  (294, 851),
  (2793, 835),
  (1286, 814),
  (2665, 808),
  (2544, 810),
  (3330, 812),
  (204, 802),
  (683, 826),
  (3157, 777),
  (356, 792),
  (961, 776),
  (45, 778),
  (1497, 809),
  (1087, 757),
  (3740, 773),
  (1796, 762),
  (1638, 760),
  (807, 759),
  (2429, 758),
  (3416, 749),
  (1390, 752),
  (3226, 736),
  (561, 736),
  (2511, 723),
  (2273, 722),
  (2684, 717),
  (157, 717),
  (1300, 715),
  (2124, 714),
  (3570, 700),
  (274, 689),
  (1730, 679),
  (2011, 689),
  (2534, 668),
  (1545, 678),
  (1033, 694),
  (726, 682),
  (47, 670),
  (1444, 652),
  (2389, 644),
  (1201, 659),
  (902, 664),
  (3477, 644),
  (1614, 608),
  (2157, 599),
  (3546, 605),
  (1926, 589),
  (1018, 588),
  (3819, 548),
  (2657, 567),
  (61, 544),
  (2274, 535),
  (2388, 542),
  (567, 536),
  (2019, 531),
  (1768, 533),
  (768, 532),
  (3364, 522),
  (2135, 499),
  (1623, 510),
  (1284, 510),
  (1860, 511),
  (1509, 502),
  (3259, 504),
  (1056, 500),
  (135, 491),
  (1160, 477),
  (374, 468),
  (65, 450),
  (2453, 442),
  (3382, 430),
  (1324, 416),
  (1613, 420),
  (3074, 418),
  (269, 406),
  (936, 412),
  (1856, 397),
  (2024, 377),
  (476, 375),
  (3163, 364),
  (2639, 374),
  (3462, 369),
  (2853, 352),
  (2299, 356),
  (2145, 332),
  (2235, 325),
  (3664, 315),
  (537, 304),
  (349, 305),
  (1634, 304),
  (1863, 292),
  (1276, 288),
  (3058, 289),
  (2390, 291),
  (2443, 259),
  (1770, 276),
  (57, 255),
  (199, 261),
  (1960, 264),
  (2182, 254),
  (3508, 251),
  (582, 207),
  (3738, 224),
  (2987, 199),
  (427, 216),
  (1439, 198),
  (2528, 196),
  (650, 188),
  (43, 174),
  (1814, 174),
  (199, 172),
  (3376, 165),
  (2108, 160),
  (782, 157),
  (877, 150),
  (1531, 140),
  (1182, 125),
  (694, 112),
  (1034, 88),
  (225, 85),
  (512, 80),
  (1694, 117),
  (3280, 69),
  (304, 50),
  (2200, 58),
  (3567, 58),
  (859, 44),
  (3683, 45),
  (1784, 66),
  (2564, 51),
  (1990, 28),
  (1710, 34),
  (584, 25),
  (2084, 47),
  (2722, 32),
  (1359, 18)],
 [(2899, 3817),
  (1712, 3819),
  (1303, 3818),
  (681, 3814),
  (39, 3812),
  (3430, 3815),
  (928, 3809),
  (1025, 3812),
  (2349, 3803),
  (492, 3800),
  (3285, 3802),
  (3558, 3795),
  (2761, 3797),
  (1240, 3787),
  (1481, 3785),
  (3697, 3785),
  (2689, 3756),
  (1338, 3736),
  (24, 3738),
  (807, 3745),
  (1123, 3735),
  (2921, 3729),
  (2307, 3725),
  (1433, 3697),
  (3741, 3690),
  (696, 3693),
  (2652, 3678),
  (946, 3672),
  (1231, 3665),
  (3438, 3636),
  (2417, 3666),
  (1840, 3664),
  (843, 3646),
  (2261, 3649),
  (3306, 3666),
  (3560, 3634),
  (1956, 3624),
  (1536, 3657),
  (1773, 3632),
  (2792, 3616),
  (3002, 3600),
  (53, 3620),
  (2351, 3621),
  (1390, 3621),
  (173, 3590),
  (484, 3561),
  (2561, 3626),
  (372, 3579),
  (3813, 3566),
  (3716, 3530),
  (3379, 3556),
  (2114, 3547),
  (3732, 3524),
  (2348, 3526),
  (1688, 3533),
  (230, 3525),
  (2783, 3544),
  (2627, 3510),
  (827, 3496),
  (3221, 3457),
  (2925, 3465),
  (1558, 3442),
  (3604, 3422),
  (1689, 3417),
  (1816, 3433),
  (2337, 3419),
  (3711, 3409),
  (2662, 3397),
  (331, 3371),
  (908, 3367),
  (3123, 3360),
  (2101, 3397),
  (604, 3352),
  (1531, 3329),
  (3225, 3315),
  (3613, 3305),
  (2191, 3317),
  (224, 3296),
  (449, 3311),
  (3819, 3263),
  (2547, 3290),
  (1700, 3253),
  (102, 3247),
  (2118, 3243),
  (534, 3257),
  (3535, 3255),
  (1928, 3243),
  (322, 3222),
  (1325, 3234),
  (954, 3224),
  (2003, 3200),
  (3620, 3190),
  (1162, 3183),
  (1791, 3157),
  (3077, 3161),
  (3757, 3153),
  (1478, 3193),
  (743, 3141),
  (398, 3140),
  (3469, 3127),
  (514, 3135),
  (2629, 3127),
  (2132, 3121),
  (3670, 3114),
  (3001, 3109),
  (2476, 3089),
  (1898, 3090),
  (660, 3067),
  (3785, 3071),
  (1231, 3070),
  (2381, 3072),
  (583, 3057),
  (2300, 3057),
  (37, 3056),
  (3322, 3020),
  (387, 3029),
  (272, 3017),
  (3473, 3020),
  (1025, 3043),
  (3688, 3019),
  (1688, 3062),
  (2629, 3008),
  (859, 3029),
  (2777, 2995),
  (1252, 2980),
  (1824, 2972),
  (667, 2955),
  (1948, 3000),
  (103, 3006),
  (2179, 2961),
  (429, 2942),
  (336, 2944),
  (1006, 2938),
  (1439, 2937),
  (3632, 2958),
  (909, 2903),
  (2327, 2907),
  (3237, 2903),
  (520, 2888),
  (1476, 2854),
  (1567, 2857),
  (735, 2872),
  (2177, 2829),
  (1149, 2816),
  (1734, 2815),
  (3434, 2811),
  (3214, 2806),
  (3766, 2817),
  (2889, 2786),
  (2088, 2777),
  (187, 2780),
  (466, 2759),
  (3055, 2762),
  (801, 2765),
  (3670, 2755),
  (2795, 2742),
  (991, 2744),
  (2687, 2712),
  (3290, 2731),
  (365, 2735),
  (2592, 2753),
  (643, 2713),
  (3555, 2713),
  (1227, 2710),
  (1282, 2729),
  (901, 2704),
  (1953, 2692),
  (1745, 2680),
  (23, 2673),
  (154, 2663),
  (3058, 2663),
  (2768, 2661),
  (3211, 2646),
  (575, 2650),
  (788, 2634),
  (373, 2631),
  (2204, 2611),
  (2853, 2621),
  (1453, 2609),
  (3132, 2606),

In [ ]:
tp_config

(0.25, 0.4)

In [ ]:
import trackpy as tp

In [ ]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [ ]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

635
583
661
386
421
558
5
443
631
645
608
512
592
365
681
636
546
602
608
656
627
661
668
733
648
613
609
646
630
593
640
658
619
613
621
659
573
647
591
655
517
661
602
360
333
377
289
496
604
568
602
575
493
526
518
389
572
680
647
637
372
480
314
322
319
340
444
465
423
456
435
327
452
488
419
535
395
466
402
385
449
483
460
515

In [ ]:
tp_list

[array([[ 709.13850416,   93.75147161],
        [1013.34715748,   64.36241948],
        [1331.93693101,   97.03992541],
        ...,
        [2704.70448522, 3776.9222718 ],
        [3205.56759887, 3743.17547498],
        [3683.51899047, 3764.18577261]]),
 array([[ 222.5782291 ,   86.19512074],
        [2197.43212353,   53.63513655],
        [ 694.42854033,  103.66535252],
        ...,
        [ 473.98147261, 3762.94897683],
        [3600.81408869, 3785.2392331 ],
        [2777.70298306, 3783.39204948]]),
 array([[ 280.7879602 ,   59.94425087],
        [2960.08878844,   97.11510211],
        [2098.31042815,   56.31669561],
        ...,
        [1244.80833275, 3788.12695299],
        [1962.23167308, 3765.30693069],
        [2749.72843044, 3781.69476281]]),
 array([[3564.48167334,   61.029668  ],
        [ 873.39732989,   50.35254091],
        [2920.74986719,   62.50766355],
        [1423.60586595,   86.70433607],
        [2248.13927659,   51.12307819],
        [1260.39599449,   62.39602849],
        [1067.6633286 ,  136.76092968],
        [1746.74580645,   95.48699491],
        [3448.63699111,  173.45501137],
        [2668.05946694,  176.37305237],
        [ 168.25110034,  158.69951511],
        [3225.9934661 ,  196.00812123],
        [1477.34313285,  184.36198384],
        [2406.27569541,  231.73696929],
        [ 620.67247451,  210.45768304],
        [3017.82148878,  180.12657243],
        [1579.79087755,  252.28437644],
        [1778.50591195,  195.24863732],
        [3302.05071151,  203.76588431],
        [1025.39000478,  230.65961263],
        [2717.92648115,  281.51395227],
        [ 382.688563  ,  243.53080393],
        [ 735.54604601,  327.37567912],
        [3589.36129708,  306.03748247],
        [2989.31380972,  287.04086337],
        [ 820.50014847,  280.37525983],
        [2839.76448643,  312.06620098],
        [2360.31664418,  294.32994816],
        [1247.98046057,  315.13134838],
        [1751.57764024,  346.06517367],
        [3325.14594474,  326.53319964],
        [1494.11955134,  357.70326464],
        [1851.95061493,  367.13318715],
        [2424.50033502,  358.25969178],
        [1076.27079835,  365.13693411],
        [3475.73672683,  351.23155351],
        [1954.77655708,  398.54700149],
        [2528.84998078,  357.44767397],
        [3756.96670564,  377.08002544],
        [ 958.59318967,  428.10584448],
        [2273.02204095,  395.18112957],
        [1203.06031375,  428.39471889],
        [1396.66112053,  400.6583606 ],
        [1494.97971653,  434.69338104],
        [2396.48938941,  442.36604612],
        [2831.31210878,  443.42628966],
        [1867.67242036,  500.39379254],
        [ 753.22484038,  454.78922165],
        [2157.08093584,  496.61042391],
        [ 307.17977265,  448.07156061],
        [2509.18563484,  505.40934754],
        [2631.421349  ,  471.61579907],
        [3002.12643787,  496.5444117 ],
        [ 945.82691787,  506.56907424],
        [1575.5038108 ,  534.22189047],
        [1348.94727366,  557.27256359],
        [2221.14187087,  555.38547374],
        [2056.70342088,  504.21578669],
        [2923.20694069,  543.54024016],
        [2334.28028504,  563.32541568],
        [3278.67586547,  567.85610447],
        [3074.31147296,  572.77367378],
        [ 131.00920458,  617.89730611],
        [1528.06873632,  575.26196434],
        [3724.37890754,  632.0037838 ],
        [ 406.36243445,  661.5664377 ],
        [ 617.27633771,  582.62686455],
        [1979.43651479,  640.84741662],
        [2499.98006934,  625.24184608],
        [3201.3185024 ,  690.75863459],
        [3322.52716018,  646.51631002],
        [ 896.41535688,  651.26551103],
        [1263.33761114,  671.15500755],
        [  86.92287452,  656.14605221],
        [ 304.75650646,  665.25527649],
        [ 749.87392797,  674.72043838],
        [2577.97939016,  675.411657  ],
        [1046.24896141,  679.10647854],
        [1804.29137684,  706.32020807],
        [3409.15066629,  768.87976562],
        [1555.99002565,  722.87589057],
        [3242.27292095,  735.11261446],
        [1320.26567875,  722.74822399],
        [2507.19166285,  799.43253319],
        [2751.14617034,  736.42407939],
        [3623.95158059,  741.40769414],
        [1282.08297261,  820.12794484],
        [2684.78233466,  775.0893482 ],
        [2391.7410252 ,  780.08837306],
        [1592.48075719,  846.53717821],
        [2202.62919672,  852.64561054],
        [2829.62114463,  875.83573035],
        [1737.85856843,  839.27490996],
        [3465.12923551,  868.63397224],
        [1973.51993565,  851.07939284],
        [2517.64399897,  903.03572346],
        [2882.08217103,  907.88547386],
        [ 121.45979871,  887.3485898 ],
        [3698.83497079,  970.04596408],
        [1575.85604341,  993.07050394],
        [ 771.94425521,  947.86407703],
        [ 283.71092373,  959.70264469],
        [2225.81344069, 1001.04515303],
        [1994.77807987,  990.05070442],
        [ 502.59285157,  982.57601575],
        [3322.88218391, 1005.40968801],
        [2646.17888255,  987.417693  ],
        [2833.54541855,  988.63625565],
        [ 646.70483522, 1007.86143854],
        [ 158.37361946, 1030.31776877],
        [1807.41989736, 1007.76735392],
        [ 918.38903532, 1022.88751977],
        [3630.08742625, 1033.8422971 ],
        [2318.045308  , 1020.23892017],
        [2423.60199542, 1033.74294574],
        [1701.4758458 , 1095.35027664],
        [1219.03930319, 1100.03591591],
        [3400.73398293, 1138.92374685],
        [1116.48277229, 1147.74126505],
        [2230.62263331, 1095.24754278],
        [ 454.11349427, 1116.48749566],
        [1874.2299676 , 1113.18048866],
        [  63.0604399 , 1162.39150376],
        [1546.86904694, 1161.2674474 ],
        [3744.77163775, 1160.80203197],
        [ 891.0890233 , 1150.62249105],
        [3045.7484226 , 1156.40535583],
        [1222.65281372, 1208.38482585],
        [1050.15583062, 1234.29420195],
        [2240.58393724, 1243.36017931],
        [2061.33290137, 1266.60700184],
        [2622.40531921, 1283.44349305],
        [2939.93863819, 1245.35968697],
        [3486.54838331, 1230.12972593],
        [  95.99463639, 1252.96321459],
        [1331.94042718, 1262.48975638],
        [1987.28473933, 1304.41392017],
        [ 882.64121262, 1316.91743821],
        [3583.83853562, 1259.20461116],
        [2446.31633719, 1290.39805515],
        [2328.02558728, 1304.12147411],
        [1545.13717499, 1326.60728228],
        [2199.57464934, 1348.33188304],
        [ 421.33278503, 1326.25228745],
        [3347.87186538, 1318.57467679],
        [3692.36725437, 1335.18882142],
        [ 985.8222641 , 1371.25168895],
        [1219.28165364, 1369.47350379],
        [2558.20574943, 1370.63326248],
        [3042.71350682, 1376.98428232],
        [ 192.5016299 , 1388.20189699],
        [ 863.6126928 , 1395.42343322],
        [1454.39130139, 1370.85185185],
        [2706.70128851, 1417.05810278],
        [2318.13758724, 1441.12626224],
        [3227.05138781, 1410.15149953],
        [1118.51337308, 1398.46473595],
        [2216.77348274, 1444.09676739],
        [2921.42394553, 1488.80762205],
        [3552.88989854, 1471.1126427 ],
        [3643.11354714, 1458.1695814 ],
        [1295.84101161, 1477.40024535],
        [ 358.95189059, 1509.85534996],
        [ 116.72565667, 1472.2894667 ],
        [2830.40667993, 1549.03564939],
        [ 880.07568278, 1512.66830596],
        [2360.92443026, 1525.14102097],
        [3153.86372967, 1507.52639189],
        [2967.17406771, 1564.63136017],
        [2068.52451762, 1598.4627599 ],
        [2784.50886772, 1583.67295046],
        [ 283.80041898, 1567.5846192 ],
        [ 574.50344355, 1584.19002632],
        [1471.92567225, 1597.47725351],
        [1769.48308821, 1544.85858074],
        [1684.8013293 , 1590.45145073],
        [2474.9845575 , 1550.57813243],
        [ 680.18172204, 1629.84324635],
        [1092.06598216, 1586.0755765 ],
        [1280.40838621, 1595.63544321],
        [3316.49357247, 1609.60182691],
        [2949.42545486, 1635.77948427],
        [ 287.96923315, 1665.14999806],
        [2699.81802216, 1657.31164541],
        [3534.19837452, 1661.80195721],
        [3703.54953398, 1712.09007452],
        [1802.33008391, 1715.23434284],
        [ 149.58194712, 1670.89811575],
        [1716.2571203 , 1713.70673949],
        [ 741.44466719, 1685.37610003],
        [1135.60285953, 1711.47120514],
        [2223.77831969, 1769.9929666 ],
        [1411.09356494, 1708.61019991],
        [ 293.35258457, 1801.26232048],
        [1304.9841129 , 1739.07008065],
        [ 521.71215792, 1804.91179901],
        [2962.79838467, 1778.29720325],
        [2774.78808532, 1820.58437461],
        [1903.79031212, 1838.96662653],
        [2476.60063069, 1782.58220042],
        [3385.56315073, 1808.96445987],
        [2120.40250277, 1809.97634581],
        [1160.09836654, 1831.36472606],
        [2285.33817448, 1837.5095043 ],
        [ 441.30206441, 1843.72122213],
        [3750.27757156, 1877.00824593],
        [1470.1660962 , 1847.8738966 ],
        [ 623.28864613, 1847.55484156],
        [ 251.19824536, 1837.76555588],
        [2381.32714142, 1937.39552061],
        [2174.79239936, 1945.09861514],
        [ 138.21896712, 1945.99835255],
        [2757.12363781, 1919.12242465],
        [2014.45592645, 1917.916487  ],
        [3492.90184468, 1898.39257986],
        [3593.64103483, 1906.74566021],
        [ 371.09094633, 1957.35185151],
        [3291.64503332, 2006.04381388],
        [2976.30127566, 1995.69174806],
        [ 422.91500864, 1982.33753816],
        [ 703.83870968, 1984.5003987 ],
        [1328.19740847, 2019.82825172],
        [ 910.01412237, 2071.29436309],
        [2745.95571702, 2028.72879201],
        [2557.81420676, 2052.66118736],
        [2137.69588366, 2045.69181729],
        [3290.99619075, 2066.10553486],
        [1588.10297578, 2094.8675828 ],
        [1871.40691871, 2115.50365214],
        [3458.72404171, 2131.38854038],
        [1261.07777406, 2144.7370721 ],
        [2422.13048524, 2121.49606349],
        [1035.04323301, 2109.67436238],
        [1963.25386331, 2157.1854389 ],
        [2959.94447877, 2146.64566086],
        [ 189.89609525, 2123.70337228],
        [ 910.08412227, 2175.67500353],
        [3131.17733436, 2158.8830097 ],
        [2565.95907928, 2156.96106849],
        [3721.71107813, 2157.29522335],
        [ 754.01720861, 2239.22262871],
        [2664.73812114, 2225.85479205],
        [1612.23752862, 2214.7363087 ],
        [3519.81332229, 2181.30879539],
        [2845.62242382, 2229.08095849],
        [1224.97382616, 2226.45922462],
        [3624.21205252, 2206.40969588],
        [1028.60078086, 2282.21283052],
        [2235.86401917, 2267.03286546],
        [ 436.30282064, 2237.18004117],
        [3017.81485508, 2287.49194888],
        [1326.97252713, 2261.8226541 ],
        [2377.19780858, 2287.78625384],
        [2470.90839332, 2318.44196456],
        [2070.03118394, 2315.03694737],
        [3786.05586449, 2348.59784809],
        [ 703.6626762 , 2353.64388151],
        [1146.2926691 , 2402.46097155],
        [2928.46880997, 2369.96426946],
        [1774.19652473, 2368.89225378],
        [1353.98432791, 2427.28035278],
        [3707.22513033, 2419.64314931],
        [ 170.77244465, 2420.89153535],
        [2618.51317183, 2439.73402076],
        [ 824.8934079 , 2450.80042931],
        [3027.51918036, 2465.74230084],
        [2149.271414  , 2485.80905846],
        [ 470.11195159, 2509.38376198],
        [ 226.12202689, 2561.90842635],
        [ 362.31228219, 2561.66204845],
        [1720.17056121, 2561.29251049],
        [1260.12604373, 2500.73856294],
        [2884.47630314, 2533.91075786],
        [1128.44844754, 2542.52848402],
        [ 697.05025769, 2591.06988806],
        [2340.78900369, 2544.35638376],
        [2046.18951637, 2574.30347764],
        [ 579.25560765, 2562.08608964],
        [2576.46604855, 2556.09402531],
        [ 468.68344393, 2617.99889065],
        [2443.52895341, 2622.29846247],
        [1466.35679284, 2639.8658476 ],
        [1719.55411392, 2634.65707772],
        [3244.03034421, 2679.98260397],
        [ 340.96846451, 2639.11601238],
        [1862.09865233, 2659.27172925],
        [2018.79435568, 2702.09129378],
        [ 208.5398897 , 2663.92977729],
        [2520.48526115, 2697.00486361],
        [1031.13262293, 2711.73158728],
        [ 509.01609512, 2737.07654661],
        [2995.08263398, 2733.69265592],
        [1289.94229145, 2706.64932257],
        [1811.71984116, 2753.42671961],
        [2614.33957122, 2804.77872144],
        [3460.00887658, 2759.26340649],
        [1490.81796019, 2759.63995162],
        [ 425.43627743, 2802.67063623],
        [2493.1952425 , 2813.80688713],
        [1614.53185813, 2777.83047559],
        [3298.43924562, 2780.06178716],
        [ 217.11750935, 2785.78194842],
        [1831.59353694, 2850.09984123],
        [1733.63142491, 2884.52700578],
        [1498.47683458, 2881.38069947],
        [3469.75591014, 2877.2977614 ],
        [ 581.95805973, 2888.66737273],
        [2643.20799236, 2891.27661696],
        [ 942.17941673, 2866.82295524],
        [2589.97216618, 2888.19335447],
        [1659.57039985, 2963.88732741],
        [2105.47331758, 2924.62758339],
        [3650.15517161, 2963.71063352],
        [1744.12240853, 2998.70262498],
        [2759.07598519, 3033.38166776],
        [3075.23578134, 2977.77638446],
        [1071.80708336, 3002.4378849 ],
        [1360.31878351, 3001.18069628],
        [ 303.63677273, 3058.59494122],
        [1474.36309341, 3075.16884151],
        [ 151.26683709, 3124.76510644],
        [ 788.33887332, 3137.38289053],
        [3205.07914908, 3075.1862934 ],
        [1935.22788518, 3080.08368901],
        [1117.08792933, 3109.24891033],
        [2829.93054151, 3094.43432913],
        [ 999.04436486, 3083.90030697],
        [2444.62869068, 3102.92386206],
        [2634.09395796, 3091.34861962],
        [1234.41949086, 3182.11227376],
        [ 680.45526872, 3157.51631442],
        [2926.28269983, 3147.89063162],
        [1377.88565449, 3208.64754501],
        [3239.64765371, 3199.42506779],
        [3129.51129188, 3249.8418067 ],
        [ 857.01075862, 3214.4245305 ],
        [1883.50137986, 3233.04798362],
        [1983.90366104, 3226.66746195],
        [2797.17549791, 3251.834056  ],
        [ 302.92297985, 3320.69563176],
        [1314.65722499, 3249.13730164],
        [ 443.7156458 , 3294.26750358],
        [2991.23061544, 3263.84231572],
        [2546.60056482, 3314.51073542],
        [3151.85478548, 3326.78705697],
        [1616.36252996, 3320.47302231],
        [2642.78915322, 3415.26439018],
        [ 529.89558577, 3360.94665097],
        [2159.49437122, 3361.80690555],
        [2832.70453798, 3398.46201907],
        [1088.6753523 , 3426.67113356],
        [2462.3355646 , 3437.96492204],
        [1256.24197475, 3461.68783009],
        [ 332.23118793, 3515.40371465],
        [1619.40068295, 3531.16672325],
        [2244.99374181, 3543.49243196],
        [1851.31379816, 3493.7992433 ],
        [ 678.18956848, 3542.81636023],
        [ 821.4491584 , 3547.75274768],
        [2956.45624435, 3538.09816905],
        [2656.39017427, 3602.94613295],
        [1118.59720167, 3579.56876443],
        [ 918.06231405, 3612.87966942],
        [1748.01470559, 3587.15943844],
        [1499.21656772, 3631.58739551],
        [2551.01972274, 3595.35391612],
        [1194.25365793, 3608.48855405],
        [2092.89169328, 3671.03937176],
        [1316.37506103, 3600.90223474],
        [ 561.70479762, 3616.91622531],
        [1882.21291888, 3617.00950299],
        [ 165.49121559, 3615.66057846],
        [ 471.3474445 , 3663.47295359],
        [1616.73607866, 3644.5684996 ],
        [2250.12112013, 3714.48047691],
        [2992.08306577, 3678.81777728],
        [1123.33885667, 3720.67995029],
        [2815.89523901, 3728.02291407],
        [ 719.30603076, 3683.48144308],
        [2610.02572326, 3733.64833857],
        [2492.78051477, 3720.11017349],
        [ 357.72832034, 3758.12087548],
        [ 148.71709965, 3745.64404808],
        [1301.02751271, 3787.9870478 ],
        [1427.98243672, 3736.79852889],
        [2379.72353806, 3788.59146822]]),
 array([[2012.38345805,   92.7923592 ],
        [2150.9312154 ,   73.48974201],
        [2312.47038797,   73.19403267],
        [3392.42036964,   72.03077074],
        [ 243.63689142,   67.3507257 ],
        [ 845.64535359,  154.95907155],
        [2425.05564613,   76.20103495],
        [ 689.9408605 ,   93.61265212],
        [1605.16362254,  167.3993961 ],
        [ 119.19074299,  142.18964555],
        [ 603.17052264,  148.80133505],
        [1304.9790851 ,  123.48104273],
        [1071.97915448,  128.26638231],
        [3270.56929611,  131.47170999],
        [2215.90843942,  208.6584605 ],
        [2340.05903323,  180.56656572],
        [3053.91345598,  145.33957864],
        [1961.90259433,  152.13992564],
        [ 373.05980312,  195.07534601],
        [1171.8405887 ,  195.61213775],
        [1660.5939408 ,  221.88600356],
        [1833.41528681,  223.13786221],
        [2914.87253287,  217.05934568],
        [3544.32179676,  253.10530191],
        [2063.65036639,  226.40637017],
        [3196.7384132 ,  260.14274492],
        [3672.97216284,  260.54203158],
        [ 795.87792627,  262.79853136],
        [2391.83311812,  261.55162317],
        [2307.09218867,  339.20432513],
        [ 722.91508786,  289.87431356],
        [1189.46781766,  302.220733  ],
        [3035.03862542,  279.55947349],
        [1623.71551801,  289.93205869],
        [2786.08320697,  306.21957298],
        [ 656.1280103 ,  305.06893052],
        [1754.43006949,  355.34780356],
        [1433.04011832,  351.5472873 ],
        [ 398.67309134,  420.87975158],
        [ 920.93108707,  357.2096471 ],
        [1377.01814467,  405.22157744],
        [2117.32055656,  396.67361723],
        [2336.53916979,  389.62110245],
        [2791.2269772 ,  427.97909637],
        [3382.47467537,  401.45462829],
        [ 164.95334227,  486.44764617],
        [1588.41830847,  478.03136886],
        [ 237.80482099,  476.93044662],
        [2469.39811645,  464.3731567 ],
        [1305.75795178,  534.24518782],
        [2837.54057116,  557.02573308],
        [1840.97172828,  512.97867286],
        [1462.12946251,  509.66460078],
        [1134.74599042,  527.35076472],
        [2086.60535874,  512.86267611],
        [1957.76437347,  527.41949392],
        [ 704.89713754,  559.30672562],
        [2256.96165803,  532.47918663],
        [1051.78553724,  575.42524365],
        [ 421.61892526,  574.15698991],
        [3180.61029505,  589.61743078],
        [3255.32854296,  603.95644385],
        [3376.23800872,  570.58611919],
        [2627.25159006,  578.11691037],
        [3768.68953287,  605.1807666 ],
        [3538.07992678,  614.85669616],
        [ 153.45588761,  590.02801921],
        [ 581.67917572,  617.25652811],
        [ 474.6040048 ,  617.56639879],
        [1193.85427534,  633.62049827],
        [1059.02875315,  687.95010628],
        [ 662.29868829,  644.15921774],
        [1528.24229484,  651.26163432],
        [2692.10884457,  659.62528543],
        [ 866.69879518,  659.40902253],
        [2931.13157119,  697.4408181 ],
        [3092.0968417 ,  736.49386691],
        [1264.23299364,  687.60979009],
        [ 531.62376319,  767.56267888],
        [3305.36264538,  716.81949761],
        [3617.55888041,  745.38748092],
        [2086.27736605,  717.20194319],
        [2188.08590546,  756.76857328],
        [2320.59618873,  726.1348823 ],
        [ 418.5621454 ,  765.81125704],
        [1905.09498045,  838.7944501 ],
        [2482.6506986 ,  777.88180781],
        [3477.00851412,  814.052149  ],
        [ 252.81828507,  827.04299505],
        [3691.87367097,  805.56753696],
        [ 825.28149519,  814.79733531],
        [2203.2629447 ,  860.61297992],
        [2792.56412417,  825.38481528],
        [3083.47977223,  832.79742454],

In [ ]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,837.138504,221.751472,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1141.347157,192.362419,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1459.936931,225.039925,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3138.759169,200.274010,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,2836.524205,228.752937,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
44065,187.873662,3822.278230,00510@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44066,1331.935215,3856.481984,00511@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44067,1524.811783,3910.980435,00512@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44068,3198.998513,3920.591354,00513@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44069,2611.496938,3892.574838,00514@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [ ]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [ ]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [ ]:
nms_config

(0.4, 0.6)

In [ ]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [ ]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5520
Number of Particles: 593
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5490
Number of Particles: 538
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5542
Number of Particles: 589
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5055
Number of Particles: 399
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5149
Number of Particles: 427
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5407
Number of Particles: 560
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 276
Number of Particles: 20
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5212
Number of Particles: 440
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5497
Number of Particles: 584
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5554
Number of Particles: 610
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5268
Number of Particles: 593
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5442
Number of Particles: 450
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5489
Number of Particles: 554
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4926
Number of Particles: 385
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5555
Number of Particles: 612
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5538
Number of Particles: 587
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5520
Number of Particles: 494
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5064
Number of Particles: 548
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5233
Number of Particles: 533
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5527
Number of Particles: 580
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5521
Number of Particles: 574
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5497
Number of Particles: 566
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5331
Number of Particles: 646
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5465
Number of Particles: 676
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5501
Number of Particles: 602
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5520
Number of Particles: 574
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5493
Number of Particles: 566
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5537
Number of Particles: 595
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5508
Number of Particles: 582
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5508
Number of Particles: 550
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5523
Number of Particles: 561
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5535
Number of Particles: 609
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5550
Number of Particles: 565
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5523
Number of Particles: 554
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5502
Number of Particles: 562
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5538
Number of Particles: 589
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5483
Number of Particles: 529
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5543
Number of Particles: 584
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5349
Number of Particles: 548
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5490
Number of Particles: 588
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4458
Number of Particles: 541
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5533
Number of Particles: 585
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5524
Number of Particles: 545
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4729
Number of Particles: 360
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4683
Number of Particles: 351
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4971
Number of Particles: 396
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4574
Number of Particles: 317
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4948
Number of Particles: 501
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5447
Number of Particles: 585
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5371
Number of Particles: 583
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5423
Number of Particles: 584
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5410
Number of Particles: 543
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5318
Number of Particles: 482
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5442
Number of Particles: 501
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5436
Number of Particles: 497
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4852
Number of Particles: 388
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5481
Number of Particles: 541
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5507
Number of Particles: 589
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5289
Number of Particles: 559
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5505
Number of Particles: 571
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4745
Number of Particles: 384
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5311
Number of Particles: 479
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4669
Number of Particles: 334
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4562
Number of Particles: 338
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4606
Number of Particles: 323
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4891
Number of Particles: 322
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5273
Number of Particles: 430
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5288
Number of Particles: 456
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5085
Number of Particles: 417
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5245
Number of Particles: 450
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5200
Number of Particles: 458
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4503
Number of Particles: 324
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5311
Number of Particles: 432
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5357
Number of Particles: 494
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5213
Number of Particles: 439
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5473
Number of Particles: 506
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5096
Number of Particles: 396
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5218
Number of Particles: 457
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5215
Number of Particles: 388
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 4629
Number of Particles: 388
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5196
Number of Particles: 434
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5127
Number of Particles: 471
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5069
Number of Particles: 450
get score gpu 16 16 240 240 51 128
get Max3 16 16 5 5 100 other :  51 3840 3840 76 5776
convert
Number of Particles before: 5321
Number of Particles: 495

In [ ]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,2303.4,3753.8,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,343.8,2343.2,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,2792.6,3103.4,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,633.2,1917.6,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3768.8,962.0,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
41795,2802.0,1552.0,00490@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
41796,3688.0,2939.0,00491@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
41797,2195.2,1810.2,00492@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
41798,3724.0,3026.0,00493@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
41799,3167.0,525.0,00494@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [ ]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')