In [ ]:
import time

start_time = time.time()
print(f"Start time recorded: {start_time}")

Start time recorded: 1761995594.3721714

In [ ]:
import time
start_time = 1761995594.3721714

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [1]:
%pip install torchinfo -qq
%pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
%pip install starfile -qq
%pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for segmentation_models_pytorch (pyproject.toml) ... done
     / 10.7 MB 16.4 MB/s 0:00:01
  Preparing metadata (setup.py) ... done
  Building wheel for trackpy (setup.py) ... done

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [2]:
%pip install pycuda==2024.1
%pip install "numpy<2.0"
%pip install mrcfile -qq

Collecting pycuda==2024.1
  Downloading pycuda-2024.1.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 15.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytools>=2011.2 (from pycuda==2024.1)
  Downloading pytools-2025.2.5-py3-none-any.whl.metadata (2.9 kB)
Collecting appdirs>=1.4.0 (from pycuda==2024.1)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: mako in /usr/local/lib/python3.12/dist-packages (from pycuda==2024.1) (1.3.10)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.5.0)
Collecting siphash24>=1.6 (from pytools>=2011.2->pycuda==2024.1)
  Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: typing-extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.15.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from mako->pycuda==2024.1) (3.0.3)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading pytools-2025.2.5-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.8/98.8 kB 13.1 MB/s eta 0:00:00
Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 13.6 MB/s eta 0:00:00
Building wheels for collected packages: pycuda
  Building wheel for pycuda (pyproject.toml) ... done
  Created wheel for pycuda: filename=pycuda-2024.1-cp312-cp312-linux_x86_64.whl size=658547 sha256=03fa3094761dd222a3d9d7727098acd00f19d36339af0206013b4c3824d4231c
  Stored in directory: /root/.cache/pip/wheels/16/8d/d0/cf29b67ddc32f77bc3344b6b2b38dd9fe8595c726c33eabc03
Successfully built pycuda
Installing collected packages: appdirs, siphash24, pytools, pycuda
Successfully installed appdirs-1.4.4 pycuda-2024.1 pytools-2025.2.5 siphash24-1.8
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.7 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 136.7 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.35.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.6 MB/s eta 0:00:00

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [1]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/time_test_output_tpz/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/time_test_output_tpz/results_50_CDF/10017/unet_eb5_dice_CRF" # @param {type:"string"}

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
IMAGE_DIR = "/content/image_dir"

In [5]:
!git clone https://github.com/phonchi/CryoParticleSegment.git

fatal: destination path 'CryoParticleSegment' already exists and is not an empty directory.

In [6]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

> #### ⚠ Notice
>
> You need to restart the kernel after the compilation step. Additionally, if your GPU architecture differs, you may need to modify the file at `/content/CryoParticleSegment/Modeling/CRF_main/setup.py`. (We attempt to detect the GPU configuration automatically, so this step is usually not necessary.)
> Furthermore, depending on the number of classes and other parameters, you may encounter an error that requires adjusting the file at `/content/CryoParticleSegment/Modeling/CRF_main/src/PermutohedralFiltering/source/gpu/LatticeFilter.cu`:
>
> 1. Note the `pd` and `vd` values from the error message.
> 2. Add an `else if (pd == ? && vd == ?)` block.
> 3. Within that block, insert the following line, replacing `pd` and `vd` with the specific values:
>
>    ```cpp
>    latticeFilterGPU<pd, vd>(output_tensor, input_tensor, positions, num_super_pixels, backward);
>    ```
> 4. Recompile using `setup.py`.

In [5]:
#%git clone https://github.com/netw0rkf10w/CRF.git
%cd CryoParticleSegment/Modeling/CRF_main
!python setup.py clean --all
!rm -rf build/
!python setup.py build_ext --inplace --force
!python setup.py install

/content/CryoParticleSegment/Modeling/CRF_main
running clean
'build/lib.linux-x86_64-cpython-312' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.12' does not exist -- can't clean it
running build_ext
W1108 13:52:01.043000 2075 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
W1108 13:52:01.111000 2075 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1108 13:52:01.111000 2075 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
building 'Permutohedral' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral -std=c++17
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp: In function ‘at::Tensor LatticeFilter_calculate(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool)’:
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:77:97: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
   77 |         at::Tensor positions = at::zeros({batch_size * num_super_pixels * pd}, input_tensor.type() );
      |                                                                                ~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/extension.h:5,
                 from src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:25:
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
creating build/lib.linux-x86_64-cpython-312
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so
building 'Permutohedral_gpu' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/cuda/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/gpu/LatticeFilter.cu -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -gencode=arch=compute_89,code=sm_89 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral_gpu -std=c++17
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu: In function ‘at::Tensor LatticeFilter_calculate_gpu(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool, bool)’:
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:202:91: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  202 |     at::Tensor positions = at::zeros(
      |                                                                                           ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:208:67: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  208 |     CHECK_INPUT(image_tensor);
      |                                                                   ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:209:64: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  209 |     CHECK_INPUT(positions);
      |                                                                ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:213:44: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  213 |         auto ref_ptr = &(image_tensor.data<float>()[b * num_super_pixels * n_reference_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:214:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  214 |         auto pos_ptr = &(positions.data<float>()[b * num_super_pixels * pd]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:215:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  215 |         auto in_ptr = &(input_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:216:45: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  216 |         auto out_ptr = &(output_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> src
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> src
running install
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating src/CRF.egg-info
writing src/CRF.egg-info/PKG-INFO
writing dependency_links to src/CRF.egg-info/dependency_links.txt
writing top-level names to src/CRF.egg-info/top_level.txt
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
W1108 13:53:46.101000 2565 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
reading manifest file 'src/CRF.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/PermutohedralFiltering.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/setup.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/__init__.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
creating build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/sparsemax.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/convcrf.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/crfs_cpu.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/CRF.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/__init__.py -> build/lib.linux-x86_64-cpython-312/CRF
running build_ext
W1108 13:53:46.151000 2565 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1108 13:53:46.152000 2565 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/PermutohedralFiltering.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/setup.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/__init__.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/sparsemax.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/convcrf.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/crfs_cpu.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/CRF.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/__init__.py -> build/bdist.linux-x86_64/egg/CRF
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/PermutohedralFiltering.py to PermutohedralFiltering.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/setup.py to setup.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/__init__.py to __init__.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/sparsemax.py to sparsemax.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/convcrf.py to convcrf.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/crfs_cpu.py to crfs_cpu.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/CRF.py to CRF.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/__init__.py to __init__.cpython-312.pyc
creating stub loader for Permutohedral.cpython-312-x86_64-linux-gnu.so
creating stub loader for Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral.py to Permutohedral.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral_gpu.py to Permutohedral_gpu.cpython-312.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
CRF.__pycache__.crfs_cpu.cpython-312: module references __file__
__pycache__.Permutohedral.cpython-312: module references __file__
__pycache__.Permutohedral_gpu.cpython-312: module references __file__
creating dist
creating 'dist/CRF-0.0.1-py3.12-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CRF-0.0.1-py3.12-linux-x86_64.egg
creating /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Extracting CRF-0.0.1-py3.12-linux-x86_64.egg to /usr/local/lib/python3.12/dist-packages
Adding CRF 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Processing dependencies for CRF==0.0.1
Finished processing dependencies for CRF==0.0.1

In [7]:
%cd /content/

/content

### ✅ Packages Handling

In [8]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [9]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [10]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 8
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [11]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [12]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [13]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

config.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/122M [00:00<?, ?B/s]

In [14]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [15]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [16]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [17]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [18]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [19]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:27<00:00,  3.04it/s]

In [20]:
processed_micrographs.shape

(84, 3840, 3840)

In [21]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [22]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [23]:
del model
torch.cuda.empty_cache()

In [25]:
model = model_post

In [24]:
RESULT_DIR

'/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/time_test_output_tpz/results_50_CDF/10017/unet_eb5_dice_CRF'

In [26]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [27]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [28]:
!cp {RESULT_DIR}/label_images.npy .

In [29]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [30]:
label_images.shape

(84, 3840, 3840)

In [31]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [32]:
!cp {RESULT_DIR}/best_config.txt .

In [33]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [34]:
radius = RADIUS

In [35]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [36]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

555 489
552 484
525 426
393 373
395 370
478 405
426 420
441 396
541 463
605 548
558 502
535 483
526 464
488 455
611 530
559 500
525 459
541 494
533 491
594 539
573 497
563 487
561 492
580 475
516 426
488 385
502 411
551 465
510 403
538 496
564 480
512 417
542 467
554 474
535 449
540 454
518 453
558 484
571 531
542 462
447 389
566 480
561 496
389 361
360 346
365 339
388 373
580 535
527 457
492 414
544 485
537 476
504 454
501 463
498 447
399 345
494 418
566 483
457 370
453 343
461 436
456 412
377 346
369 336
376 347
379 364
429 401
428 378
390 336
409 354
406 357
393 378
418 372
462 421
436 408
491 440
411 379
431 378
430 403
446 419
403 344
420 355
416 357
441 378

In [37]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [38]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [39]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [40]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1510,3952,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,594,3951,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,3528,3950,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,1236,3948,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,247,3948,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
36067,864,147,00373@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36068,316,148,00374@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36069,2857,155,00375@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36070,441,153,00376@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
36071,3605,161,00377@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [41]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [42]:
cv_list

[[(1382, 3824),
  (466, 3823),
  (3400, 3822),
  (1108, 3820),
  (119, 3820),
  (2412, 3818),
  (626, 3815),
  (3586, 3817),
  (3040, 3812),
  (1186, 3795),
  (2826, 3787),
  (1786, 3783),
  (2695, 3791),
  (1565, 3781),
  (3690, 3767),
  (804, 3787),
  (1701, 3767),
  (2952, 3762),
  (3199, 3740),
  (1295, 3732),
  (976, 3732),
  (3424, 3686),
  (468, 3686),
  (35, 3680),
  (1782, 3686),
  (362, 3668),
  (1136, 3653),
  (3257, 3659),
  (1529, 3657),
  (2768, 3656),
  (1438, 3667),
  (1952, 3624),
  (3054, 3646),
  (1019, 3625),
  (816, 3652),
  (2330, 3625),
  (1703, 3563),
  (997, 3565),
  (3590, 3556),
  (755, 3563),
  (3229, 3547),
  (1127, 3538),
  (3097, 3555),
  (42, 3530),
  (3521, 3518),
  (3157, 3489),
  (676, 3517),
  (2366, 3487),
  (3002, 3495),
  (137, 3485),
  (2777, 3460),
  (603, 3468),
  (3777, 3462),
  (3379, 3447),
  (1777, 3458),
  (762, 3428),
  (1479, 3436),
  (2261, 3423),
  (1267, 3427),
  (3581, 3416),
  (2533, 3446),
  (1000, 3413),
  (16, 3409),
  (2932, 3403),
  (2642, 3416),
  (516, 3408),
  (3147, 3375),
  (2806, 3360),
  (886, 3368),
  (672, 3347),
  (209, 3359),
  (3046, 3354),
  (1599, 3338),
  (2141, 3331),
  (1302, 3330),
  (3369, 3317),
  (329, 3319),
  (2661, 3303),
  (1069, 3302),
  (3815, 3284),
  (3659, 3288),
  (899, 3280),
  (3577, 3296),
  (1877, 3268),
  (3068, 3250),
  (3169, 3230),
  (2807, 3223),
  (327, 3209),
  (1221, 3198),
  (2599, 3209),
  (502, 3200),
  (3548, 3195),
  (2258, 3229),
  (2695, 3185),
  (3746, 3191),
  (1078, 3167),
  (633, 3214),
  (2144, 3148),
  (3155, 3137),
  (792, 3122),
  (1953, 3168),
  (1599, 3122),
  (234, 3137),
  (3823, 3088),
  (1270, 3109),
  (3564, 3094),
  (608, 3086),
  (3452, 3094),
  (2308, 3079),
  (1509, 3125),
  (2024, 3050),
  (2597, 3066),
  (3366, 3033),
  (1348, 3000),
  (377, 3009),
  (3622, 3010),
  (25, 2953),
  (2315, 2967),
  (3287, 2949),
  (2080, 2943),
  (1817, 2934),
  (2887, 2975),
  (2785, 2935),
  (3822, 2922),
  (2579, 2936),
  (268, 2926),
  (889, 2916),
  (1140, 2879),
  (3027, 2874),
  (3360, 2858),
  (1232, 2856),
  (92, 2855),
  (2718, 2823),
  (2511, 2825),
  (3793, 2824),
  (3601, 2816),
  (43, 2756),
  (1037, 2754),
  (3250, 2742),
  (2873, 2750),
  (893, 2758),
  (2509, 2731),
  (2589, 2741),
  (3403, 2735),
  (3808, 2709),
  (3697, 2708),
  (1992, 2683),
  (478, 2674),
  (2953, 2657),
  (690, 2659),
  (3412, 2652),
  (3601, 2648),
  (3238, 2646),
  (1738, 2647),
  (971, 2634),
  (2171, 2618),
  (598, 2608),
  (25, 2602),
  (254, 2595),
  (1638, 2601),
  (2101, 2559),
  (2677, 2595),
  (2524, 2573),
  (1331, 2567),
  (1546, 2590),
  (3342, 2552),
  (3238, 2550),
  (2827, 2540),
  (122, 2539),
  (3805, 2532),
  (2334, 2547),
  (3698, 2516),
  (2601, 2511),
  (1190, 2518),
  (2258, 2517),
  (399, 2488),
  (1890, 2479),
  (1628, 2469),
  (3539, 2463),
  (1713, 2458),
  (2360, 2447),
  (2939, 2463),
  (1337, 2432),
  (3455, 2422),
  (3153, 2411),
  (2664, 2410),
  (125, 2400),
  (2745, 2394),
  (1562, 2403),
  (2448, 2405),
  (437, 2393),
  (3741, 2389),
  (596, 2403),
  (3041, 2380),
  (323, 2374),
  (3621, 2372),
  (1406, 2360),
  (2040, 2349),
  (2837, 2353),
  (1733, 2344),
  (1913, 2348),
  (192, 2336),
  (2645, 2307),
  (3287, 2314),
  (1377, 2289),
  (1087, 2311),
  (1591, 2306),
  (3102, 2314),
  (53, 2324),
  (2355, 2291),
  (359, 2278),
  (612, 2262),
  (3739, 2247),
  (2758, 2225),
  (1997, 2238),
  (1607, 2216),
  (3249, 2190),
  (2463, 2193),
  (779, 2174),
  (481, 2208),
  (25, 2156),
  (1600, 2136),
  (3003, 2186),
  (643, 2125),
  (3575, 2122),
  (2344, 2110),
  (3445, 2123),
  (69, 2091),
  (1055, 2087),
  (2156, 2078),
  (27, 2043),
  (2012, 2040),
  (2667, 2089),
  (915, 2045),
  (2554, 2069),
  (3585, 2031),
  (690, 2034),
  (318, 2025),
  (3197, 2027),
  (3778, 2036),
  (1330, 2011),
  (426, 2008),
  (221, 2002),
  (1458, 2006),
  (827, 1973),
  (1535, 1974),
  (3442, 1964),
  (2068, 1970),
  (1725, 1972),
  (2736, 1949),
  (2598, 1932),
  (1105, 1924),
  (916, 1916),
  (1307, 1907),
  (3214, 1888),
  (3443, 1872),
  (3653, 1873),
  (669, 1862),
  (102, 1863),
  (2137, 1809),
  (1767, 1824),
  (3006, 1811),
  (1396, 1807),
  (1689, 1755),
  (2852, 1749),
  (2568, 1781),
  (481, 1769),
  (3084, 1733),
  (2121, 1731),
  (46, 1714),
  (1583, 1731),
  (831, 1708),
  (2793, 1693),
  (3423, 1687),
  (2654, 1685),
  (1405, 1677),
  (3618, 1684),
  (3818, 1647),
  (1937, 1657),
  (3309, 1652),
  (566, 1651),
  (2227, 1659),
  (1855, 1649),
  (2712, 1628),
  (2989, 1622),
  (343, 1595),
  (1554, 1585),
  (3247, 1574),
  (3817, 1552),
  (1360, 1565),
  (3088, 1549),
  (157, 1560),
  (457, 1536),
  (1267, 1540),
  (2697, 1533),
  (1897, 1536),
  (967, 1520),
  (3166, 1497),
  (3614, 1502),
  (3707, 1501),
  (1458, 1482),
  (877, 1474),
  (207, 1472),
  (424, 1450),
  (763, 1452),
  (1189, 1409),
  (494, 1395),
  (2216, 1399),
  (1399, 1388),
  (1100, 1374),
  (2693, 1389),
  (2320, 1386),
  (2083, 1371),
  (3620, 1328),
  (2449, 1316),
  (787, 1327),
  (3290, 1351),
  (1267, 1321),
  (1963, 1327),
  (1761, 1343),
  (3176, 1307),
  (1059, 1291),
  (2827, 1285),
  (1447, 1284),
  (3530, 1272),
  (2075, 1275),
  (410, 1267),
  (914, 1256),
  (2609, 1254),
  (3013, 1246),
  (58, 1256),
  (1348, 1238),
  (2280, 1221),
  (1824, 1204),
  (1238, 1214),
  (570, 1211),
  (1432, 1185),
  (2143, 1180),
  (2525, 1190),
  (2738, 1175),
  (3821, 1155),
  (2068, 1159),
  (1519, 1153),
  (3322, 1165),
  (3482, 1138),
  (828, 1134),
  (293, 1124),
  (612, 1121),
  (2998, 1108),
  (1802, 1081),
  (893, 1081),
  (3142, 1079),
  (506, 1108),
  (2648, 1069),
  (2434, 1062),
  (1060, 1071),
  (1937, 1040),
  (2816, 1023),
  (3221, 1015),
  (1350, 981),
  (1097, 983),
  (748, 986),
  (2246, 975),
  (63, 974),
  (3410, 961),
  (479, 961),
  (1659, 992),
  (2052, 944),
  (1261, 944),
  (1852, 914),
  (1752, 919),
  (3703, 901),
  (3148, 896),
  (1581, 887),
  (1097, 882),
  (2409, 863),
  (3436, 850),
  (961, 855),
  (2717, 824),
  (449, 831),
  (3067, 821),
  (3790, 817),
  (3652, 823),
  (1175, 811),
  (351, 797),
  (2955, 793),
  (2481, 782),
  (1294, 812),
  (3576, 783),
  (929, 767),
  (1656, 765),
  (36, 751),
  (1955, 745),
  (1425, 738),
  (3711, 724),
  (1609, 694),
  (748, 677),
  (167, 675),
  (24, 665),
  (1143, 651),
  (851, 658),
  (1807, 641),
  (1031, 631),
  (534, 640),
  (3150, 604),
  (1517, 617),
  (2484, 611),
  (1325, 619),
  (45, 578),
  (627, 585),
  (33, 539),
  (3802, 555),
  (2617, 534),
  (1622, 577),
  (1955, 542),
  (2384, 538),
  (1727, 517),
  (1451, 520),
  (221, 495),
  (1352, 519),
  (3634, 507),
  (589, 500),
  (1138, 508),
  (2935, 489),
  (76, 459),
  (478, 476),
  (3693, 460),
  (3811, 450),
  (3446, 449),
  (2212, 450),
  (2842, 466),
  (1440, 424),
  (227, 419),
  (1664, 417),
  (347, 419),
  (2297, 406),
  (543, 382),
  (1225, 367),
  (20, 357),
  (3239, 340),
  (1582, 355),
  (1409, 343),
  (956, 329),
  (1883, 294),
  (860, 315),
  (618, 338),
  (178, 288),
  (1645, 291),
  (2909, 286),
  (2108, 287),
  (3535, 271),
  (320, 251),
  (3763, 271),
  (725, 236),
  (1319, 242),
  (1723, 236),
  (884, 213),
  (2468, 196),
  (1134, 213),
  (2931, 176),
  (1437, 162),
  (781, 164),
  (3266, 146),
  (2021, 140),
  (2571, 135),
  (168, 117),
  (2180, 111),
  (600, 109),
  (2715, 101),
  (713, 94),
  (339, 108),
  (1342, 92),
  (1797, 99),
  (3488, 88),
  (1010, 66),
  (2822, 80),
  (2935, 60),
  (3217, 53),
  (3095, 27),
  (2999, 70),
  (1873, 33),
  (787, 31),
  (122, 26),
  (3802, 25),
  (2075, 30),
  (1194, 86),
  (2682, 18),
  (2309, 23),
  (1412, 45)],
 [(355, 3821),
  (3120, 3820),
  (2435, 3819),
  (278, 3815),
  (729, 3818),
  (3381, 3814),
  (1741, 3804),
  (1455, 3807),
  (3735, 3811),
  (3010, 3807),
  (859, 3807),
  (958, 3800),
  (2585, 3800),
  (1187, 3792),
  (2165, 3791),
  (3605, 3787),
  (2782, 3786),
  (1889, 3779),
  (2261, 3775),
  (163, 3774),
  (505, 3769),
  (1579, 3753),
  (2676, 3725),
  (739, 3728),
  (354, 3722),
  (2428, 3729),
  (3596, 3683),
  (1127, 3706),
  (37, 3707),
  (2956, 3691),
  (969, 3697),
  (3452, 3666),
  (2761, 3664),
  (3059, 3661),
  (1241, 3658),
  (3418, 3628),
  (109, 3635),
  (2385, 3650),
  (2014, 3641),
  (560, 3635),
  (2839, 3627),
  (2583, 3618),
  (3332, 3608),
  (3206, 3605),
  (1482, 3590),
  (250, 3618),
  (1925, 3579),
  (1339, 3584),
  (2251, 3568),
  (1643, 3562),
  (2887, 3552),
  (873, 3550),
  (758, 3535),
  (3038, 3535),
  (2154, 3529),
  (1742, 3521),
  (160, 3481),
  (483, 3478),
  (3509, 3444),
  (2448, 3484),
  (2538, 3467),
  (3433, 3452),
  (3614, 3448),
  (1876, 3439),
  (2757, 3438),
  (298, 3435),
  (2328, 3443),
  (1514, 3427),
  (3301, 3418),
  (2949, 3421),
  (1764, 3415),
  (967, 3401),
  (380, 3394),
  (3174, 3407),
  (1298, 3388),
  (1990, 3427),
  (1677, 3381),
  (184, 3362),
  (1229, 3350),
  (1123, 3345),
  (3691, 3346),
  (1847, 3342),
  (2655, 3322),
  (1554, 3331),
  (1338, 3311),
  (965, 3301),
  (3445, 3290),
  (160, 3268),
  (2574, 3272),
  (1855, 3250),
  (43, 3252),
  (3586, 3277),
  (1234, 3247),
  (3022, 3253),
  (3778, 3245),
  (2364, 3269),
  (798, 3217),
  (2165, 3235),
  (2867, 3224),
  (1090, 3187),
  (602, 3222),
  (2418, 3193),
  (2709, 3190),
  (1798, 3175),
  (941, 3170),
  (1307, 3166),
  (21, 3162),
  (3614, 3164),
  (1414, 3127),
  (2629, 3128),
  (1013, 3100),
  (3341, 3098),
  (3256, 3104),
  (3437, 3089),
  (1125, 3089),
  (1904, 3089),
  (2733, 3077),
  (573, 3083),
  (311, 3090),
  (2119, 3062),
  (3155, 3044),
  (2878, 3072),
  (893, 3021),
  (1219, 3022),
  (1453, 3018),
  (2261, 3018),
  (228, 3018),
  (3096, 3018),
  (3725, 2970),
  (3014, 2973),
  (792, 2962),
  (3273, 2943),
  (1807, 2941),
  (1565, 2922),
  (2428, 2931),
  (1898, 2907),
  (2307, 2903),
  (3820, 2877),
  (3579, 2883),
  (2173, 2868),
  (3170, 2853),
  (1369, 2841),
  (856, 2857),
  (241, 2847),
  (3666, 2829),
  (2105, 2811),
  (2348, 2812),
  (1583, 2809),
  (540, 2840),
  (57, 2797),
  (1463, 2793),
  (3813, 2771),
  (2476, 2758),
  (3030, 2732),
  (3232, 2760),
  (1954, 2746),
  (421, 2740),
  (160, 2715),
  (1365, 2697),
  (3725, 2702),
  (2353, 2690),
  (514, 2704),
  (1601, 2700),
  (3356, 2683),
  (1700, 2688),
  (3280, 2676),
  (237, 2664),
  (3080, 2661),
  (47, 2670),
  (782, 2636),
  (1784, 2643),
  (1242, 2639),
  (3663, 2630),
  (1584, 2603),
  (478, 2619),
  (1891, 2591),
  (3367, 2586),
  (75, 2601),
  (388, 2557),
  (2733, 2568),
  (1447, 2558),
  (2010, 2577),
  (3248, 2552),
  (1325, 2522),
  (2900, 2507),
  (150, 2501),
  (1073, 2487),
  (828, 2472),
  (1426, 2466),
  (2751, 2463),
  (3417, 2457),
  (42, 2440),
  (1981, 2427),
  (1312, 2417),
  (2065, 2369),
  (1886, 2368),
  (345, 2355),
  (1632, 2369),
  (907, 2361),
  (1734, 2339),
  (3504, 2318),
  (804, 2324),
  (2973, 2299),
  (1127, 2320),
  (260, 2313),
  (2491, 2288),
  (2378, 2279),
  (2032, 2251),
  (3060, 2261),
  (2900, 2259),
  (377, 2262),
  (708, 2261),
  (1643, 2254),
  (19, 2253),
  (1317, 2257),
  (983, 2265),
  (3246, 2210),
  (1834, 2222),
  (3120, 2210),
  (2938, 2183),
  (154, 2189),
  (1455, 2166),
  (3334, 2151),
  (873, 2151),
  (3453, 2175),
  (366, 2139),
  (3207, 2142),
  (83, 2135),
  (2693, 2124),
  (2049, 2111),
  (2394, 2125),
  (3644, 2116),
  (964, 2111),
  (251, 2103),
  (706, 2074),
  (3151, 2064),
  (425, 2059),
  (1644, 2054),
  (2855, 2056),
  (3782, 2038),
  (44, 2029),
  (1176, 2035),
  (1528, 2010),
  (2079, 2015),
  (568, 2029),
  (329, 1978),
  (178, 2023),
  (2319, 1975),
  (3622, 1952),
  (1766, 1953),
  (3054, 1987),
  (3797, 1931),
  (1153, 1916),
  (2747, 1940),
  (3182, 1925),
  (1474, 1925),
  (3269, 1903),
  (2491, 1915),
  (1895, 1895),
  (814, 1882),
  (2840, 1841),
  (2609, 1846),
  (1632, 1851),
  (1982, 1809),
  (946, 1853),
  (1808, 1808),
  (2155, 1805),
  (414, 1792),
  (2736, 1798),
  (3013, 1783),
  (3418, 1775),
  (3317, 1758),
  (2283, 1765),
  (841, 1749),
  (1952, 1722),
  (2835, 1739),
  (2678, 1706),
  (3170, 1719),
  (598, 1730),
  (3348, 1676),
  (2166, 1694),
  (1770, 1696),
  (22, 1664),
  (3464, 1657),
  (2320, 1654),
  (1951, 1640),
  (113, 1650),
  (1616, 1642),
  (1019, 1628),
  (3203, 1596),
  (1721, 1580),
  (2269, 1577),
  (514, 1554),
  (1437, 1573),
  (73, 1545),
  (2110, 1525),
  (2511, 1541),
  (2769, 1510),
  (149, 1500),
  (420, 1479),
  (1312, 1476),
  (1725, 1470),
  (2200, 1452),
  (3010, 1438),
  (3446, 1397),
  (851, 1425),
  (2714, 1388),
  (240, 1397),
  (111, 1385),
  (2076, 1382),
  (152, 1370),
  (3261, 1361),
  (1077, 1383),
  (1553, 1371),
  (2823, 1380),
  (1650, 1359),
  (2254, 1330),
  (18, 1328),
  (84, 1306),
  (2556, 1297),
  (3359, 1294),
  (918, 1287),
  (1788, 1324),
  (379, 1287),
  (1182, 1282),
  (2947, 1257),
  (2110, 1258),
  (2391, 1247),
  (1510, 1231),
  (3573, 1222),
  (2289, 1228),
  (3750, 1215),
  (2722, 1202),
  (1356, 1205),
  (1883, 1200),
  (104, 1226),
  (1058, 1202),
  (244, 1208),
  (1473, 1160),
  (3631, 1151),
  (468, 1134),
  (661, 1137),
  (3340, 1114),
  (809, 1122),
  (1653, 1112),
  (3087, 1110),
  (2258, 1148),
  (3766, 1100),
  (2786, 1098),
  (1016, 1077),
  (1167, 1068),
  (2690, 1084),
  (556, 1067),
  (44, 1056),
  (2077, 1045),
  (3607, 1049),
  (367, 1050),
  (2583, 1041),
  (1923, 1043),
  (1383, 1017),
  (732, 975),
  (522, 934),
  (191, 949),
  (2700, 928),
  (625, 955),
  (2497, 909),
  (2356, 937),
  (1830, 926),
  (345, 909),
  (3583, 952),
  (1359, 921),
  (18, 921),
  (3756, 924),
  (3133, 920),
  (2082, 889),
  (2899, 883),
  (3037, 848),
  (1587, 858),
  (2797, 833),
  (3330, 814),
  (677, 828),
  (330, 827),
  (31, 775),
  (963, 774),
  (1639, 759),
  (807, 760),
  (2428, 757),
  (3741, 763),
  (1794, 763),
  (1170, 746),
  (3415, 751),
  (1390, 750),
  (3201, 752),
  (565, 731),
  (2275, 720),
  (159, 758),
  (1300, 715),
  (2126, 715),
  (1730, 683),
  (687, 689),
  (51, 669),
  (1444, 652),
  (2389, 645),
  (1204, 658),
  (901, 664),
  (1611, 609),
  (2159, 597),
  (3819, 552),
  (2274, 536),
  (63, 546),
  (2389, 542),
  (569, 539),
  (2021, 529),
  (767, 532),
  (3364, 521),
  (1761, 528),
  (2136, 499),
  (1286, 512),
  (1519, 505),
  (3173, 503),
  (3263, 507),
  (3493, 488),
  (1164, 476),
  (378, 468),
  (100, 476),
  (2454, 440),
  (3383, 431),
  (1324, 417),
  (3080, 411),
  (272, 405),
  (900, 408),
  (1865, 387),
  (3821, 353),
  (3166, 365),
  (2025, 374),
  (2639, 374),
  (479, 372),
  (3462, 369),
  (2270, 342),
  (3666, 315),
  (1495, 312),
  (349, 303),
  (1878, 294),
  (1634, 307),
  (1275, 286),
  (3059, 294),
  (2389, 290),
  (1788, 276),
  (918, 278),
  (55, 252),
  (3508, 250),
  (1957, 263),
  (2155, 289),
  (2255, 215),
  (433, 212),
  (3739, 222),
  (621, 217),
  (53, 172),
  (3377, 166),
  (3174, 166),
  (203, 169),
  (2109, 162),
  (1356, 146),
  (878, 153),
  (1532, 140),
  (1182, 127),
  (693, 109),
  (524, 83),
  (108, 85),
  (3280, 69),
  (2203, 60),
  (3687, 46),
  (1991, 41),
  (1756, 55),
  (842, 41),
  (3796, 33),
  (2566, 52),
  (590, 24),
  (3567, 61),
  (2085, 47),
  (263, 62),
  (2724, 37),
  (442, 20),
  (1360, 19)],
 [(1173, 3822),
  (2899, 3818),
  (1304, 3816),
  (1711, 3818),
  (3151, 3808),
  (3430, 3815),
  (928, 3807),
  (1029, 3804),
  (2351, 3803),
  (494, 3800),
  (3286, 3802),
  (3558, 3795),
  (2760, 3797),
  (1241, 3783),
  (3699, 3783),
  (230, 3770),
  (912, 3734),
  (806, 3743),
  (20, 3731),
  (1126, 3732),
  (2307, 3726),
  (2922, 3729),
  (3736, 3690),
  (699, 3689),
  (3307, 3671),
  (2414, 3665),
  (1231, 3664),
  (2256, 3652),
  (1528, 3664),
  (1967, 3630),
  (1805, 3649),
  (2355, 3624),
  (1386, 3615),
  (183, 3590),
  (376, 3579),
  (3811, 3567),
  (3380, 3556),
  (2117, 3549),
  (2350, 3530),
  (1252, 3538),
  (233, 3525),
  (1688, 3532),
  (827, 3494),
  (2639, 3513),
  (3219, 3459),
  (2924, 3463),
  (3804, 3432),
  (1689, 3418),
  (1812, 3430),
  (2332, 3420),
  (2661, 3397),
  (329, 3372),
  (111, 3390),
  (3222, 3339),
  (905, 3369),
  (2099, 3397),
  (3126, 3358),
  (606, 3348),
  (1533, 3331),
  (248, 3318),
  (2192, 3319),
  (446, 3313),
  (3814, 3260),
  (2547, 3291),
  (1698, 3253),
  (103, 3247),
  (2118, 3241),
  (531, 3250),
  (3534, 3262),
  (1927, 3243),
  (696, 3238),
  (1325, 3235),
  (952, 3221),
  (673, 3169),
  (3617, 3193),
  (2004, 3197),
  (1162, 3183),
  (1789, 3156),
  (3756, 3153),
  (744, 3142),
  (403, 3142),
  (3468, 3128),
  (513, 3136),
  (2629, 3128),
  (2128, 3120),
  (2477, 3091),
  (1899, 3088),
  (3785, 3071),
  (1231, 3068),
  (2382, 3072),
  (587, 3050),
  (32, 3051),
  (2300, 3057),
  (289, 3001),
  (3477, 3019),
  (1024, 3042),
  (2629, 3008),
  (856, 3033),
  (2778, 2995),
  (1255, 2979),
  (1823, 2971),
  (1948, 3000),
  (103, 3007),
  (2177, 2959),
  (333, 2949),
  (1438, 2939),
  (1009, 2942),
  (908, 2903),
  (2328, 2907),
  (525, 2888),
  (1564, 2857),
  (2175, 2828),
  (1735, 2819),
  (1151, 2818),
  (3434, 2812),
  (185, 2782),
  (2889, 2785),
  (2087, 2773),
  (2615, 2782),
  (463, 2762),
  (3056, 2760),
  (3670, 2758),
  (994, 2745),
  (3291, 2730),
  (368, 2734),
  (2543, 2737),
  (2692, 2705),
  (640, 2712),
  (3554, 2714),
  (1952, 2692),
  (1743, 2677),
  (23, 2677),
  (153, 2663),
  (3060, 2662),
  (574, 2649),
  (373, 2632),
  (2853, 2626),
  (2203, 2614),
  (1455, 2608),
  (2513, 2599),
  (2084, 2583),
  (3340, 2568),
  (1001, 2612),
  (77, 2580),
  (1788, 2582),
  (1874, 2556),
  (896, 2518),
  (1150, 2520),
  (1364, 2509),
  (1257, 2495),
  (2941, 2511),
  (401, 2491),
  (661, 2495),
  (213, 2493),
  (1605, 2509),
  (1729, 2474),
  (3260, 2443),
  (1866, 2446),
  (3030, 2443),
  (90, 2440),
  (1459, 2469),
  (2730, 2413),
  (3364, 2410),
  (2661, 2372),
  (3598, 2370),
  (3706, 2381),
  (1691, 2359),
  (1942, 2357),
  (3214, 2357),
  (945, 2365),
  (340, 2354),
  (1837, 2354),
  (2082, 2352),
  (3028, 2336),
  (1046, 2325),
  (456, 2331),
  (3286, 2321),
  (3413, 2326),
  (1626, 2289),
  (1372, 2306),
  (1248, 2349),
  (2926, 2297),
  (323, 2256),
  (2770, 2277),
  (1162, 2270),
  (177, 2266),
  (2055, 2255),
  (3474, 2248),
  (759, 2240),
  (1821, 2236),
  (89, 2188),
  (340, 2187),
  (1156, 2167),
  (958, 2165),
  (2908, 2172),
  (1247, 2154),
  (3417, 2146),
  (1460, 2127),
  (3023, 2135),
  (2509, 2138),
  (3564, 2088),
  (176, 2114),
  (475, 2100),
  (3591, 2065),
  (1657, 2114),
  (820, 2128),
  (2810, 2069),
  (1202, 2064),
  (2440, 2019),
  (1342, 2023),
  (1082, 2014),
  (3087, 2004),
  (1686, 2003),
  (1530, 1992),
  (706, 1998),
  (3593, 1989),
  (2286, 1993),
  (2060, 1953),
  (3044, 1923),
  (97, 1924),
  (1414, 1928),
  (2183, 1889),
  (187, 1870),
  (511, 1885),
  (1371, 1810),
  (3263, 1835),
  (2038, 1815),
  (2308, 1803),
  (856, 1799),
  (2130, 1790),
  (278, 1788),
  (2521, 1786),
  (2944, 1806),
  (982, 1781),
  (414, 1758),
  (1144, 1765),
  (2225, 1754),
  (124, 1749),
  (18, 1736),
  (1226, 1711),
  (3509, 1701),
  (887, 1683),
  (602, 1702),
  (2888, 1693),
  (1843, 1675),
  (507, 1662),
  (3100, 1675),
  (101, 1656),
  (20, 1633),
  (1086, 1645),
  (310, 1657),
  (1586, 1623),
  (3655, 1653),
  (2576, 1613),
  (3266, 1609),
  (3164, 1589),
  (1739, 1576),
  (3538, 1577),
  (813, 1584),
  (2967, 1569),
  (2818, 1566),
  (1311, 1594),
  (3668, 1541),
  (934, 1526),
  (96, 1524),
  (635, 1513),
  (3344, 1515),
  (1651, 1499),
  (1440, 1538),
  (2207, 1498),
  (2796, 1457),
  (667, 1396),
  (1685, 1394),
  (1918, 1377),
  (1773, 1376),
  (875, 1372),
  (983, 1405),
  (748, 1366),
  (242, 1353),
  (2579, 1355),
  (3533, 1387),
  (2277, 1311),
  (1734, 1294),
  (1543, 1305),
  (2474, 1333),
  (3743, 1301),
  (387, 1307),
  (3185, 1261),
  (3330, 1288),
  (66, 1256),
  (844, 1254),
  (1111, 1260),
  (1609, 1226),
  (3061, 1238),
  (1244, 1199),
  (299, 1195),
  (2046, 1212),
  (2252, 1179),
  (2913, 1206),
  (183, 1178),
  (577, 1162),
  (3753, 1136),
  (1427, 1130),
  (3074, 1139),
  (2762, 1121),
  (3223, 1131),
  (2600, 1106),
  (2263, 1091),
  (1278, 1096),
  (3695, 1069),
  (2059, 1065),
  (3354, 1052),
  (1858, 1042),
  (1151, 1032),
  (2961, 1033),
  (20, 1016),
  (672, 1030),
  (265, 1019),
  (926, 1007),
  (789, 994),

In [43]:
tp_config

(0.25, 0.4)

In [44]:
import trackpy as tp

In [45]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [46]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

602
574
629
377
403
542
404
464
605
621
588
519
578
491
666
597
549
559
541
613
608
644
633
694
603
600
604
632
619
553
619
641
593
590
597
631
552
612
563
620
499
624
587
389
354
374
374
599
597
569
586
579
522
505
532
440
567
650
631
621
463
481
378
378
383
355
429
455
433
470
446
375
470
463
428
513
412
474
424
429
467
477
458
494

In [47]:
tp_list

[array([[1405.38500778,   57.88855265],
        [1009.75122388,   62.98364686],
        [ 708.06522105,   94.39617703],
        ...,
        [2700.17886152, 3777.71840424],
        [2825.36842105, 3781.25994305],
        [3687.85490721, 3766.60225751]]),
 array([[ 225.01415972,   82.54122502],
        [2399.10310667,   97.75157991],
        [ 107.02388878,   82.06412767],
        ...,
        [ 477.11730993, 3762.91242836],
        [2778.15696653, 3782.79677344],
        [2586.91453441, 3792.61428093]]),
 array([[2961.89501872,  101.53442541],
        [2097.95310704,   56.62301739],
        [ 922.62958809,   83.14387272],
        ...,
        [3690.18559264, 3780.31135144],
        [1245.1821166 , 3785.82671413],
        [2746.97816422, 3780.91639454]]),
 array([[2920.33498379,   62.50503874],
        [3565.24981748,   58.04234448],
        [2255.89045771,   50.54775207],
        [1422.04612737,   86.85404475],
        [1260.97207642,   63.04536554],
        [1068.19217684,  139.38710781],
        [1745.90575951,   96.59364193],
        [3448.43035076,  173.37704918],
        [3306.5435337 ,  198.84582878],
        [3229.09105248,  196.85520608],
        [ 167.59060303,  157.89722531],
        [2672.64443742,  178.47029077],
        [1479.19722931,  183.4832665 ],
        [2404.91212309,  232.15951897],
        [ 620.08136409,  210.58154268],
        [3018.57862182,  168.64348524],
        [1042.30515198,  186.0816383 ],
        [1776.76621829,  199.47309722],
        [2721.85598668,  278.180456  ],
        [ 381.05344643,  238.86683686],
        [1578.78822894,  253.06953739],
        [ 734.94528331,  327.29087171],
        [3588.21348336,  305.87898582],
        [ 820.46105762,  281.17752187],
        [2983.6419318 ,  286.3694037 ],
        [2839.06497667,  310.52305721],
        [1246.8079439 ,  314.02463315],
        [1366.23585688,  365.62620915],
        [1752.92316884,  347.49281077],
        [1492.54917846,  360.95088981],
        [1853.22264185,  367.55981253],
        [3331.4813762 ,  329.26953187],
        [1954.22428334,  397.92961648],
        [1077.08970167,  366.03585383],
        [2529.51673493,  357.82796413],
        [3758.18577435,  375.08976637],
        [ 957.05080869,  426.0288935 ],
        [2272.35893055,  391.52518221],
        [1199.10671854,  421.57686889],
        [2831.42979455,  443.39554713],
        [1867.11438553,  500.69267753],
        [ 309.79006752,  451.85548508],
        [2155.40827869,  490.932379  ],
        [2509.28446966,  506.39451996],
        [2630.73529899,  471.22834189],
        [ 751.96407042,  455.74497984],
        [2390.07130211,  441.92306454],
        [1490.59134542,  445.69052417],
        [ 945.68639466,  505.94151412],
        [1574.22485389,  537.19244994],
        [2222.41257919,  558.95384615],
        [1353.74341186,  553.31354884],
        [2056.05323702,  503.86860497],
        [2925.18991798,  543.67577516],
        [3072.86678855,  572.20323993],
        [2698.27090309,  588.39654405],
        [3277.3004066 ,  571.10444072],
        [ 129.84083071,  618.2955355 ],
        [1527.68970283,  576.88067266],
        [2319.55183246,  560.40122164],
        [3729.04019626,  633.27941121],
        [ 618.60427086,  583.67841949],
        [ 405.31789372,  662.03126336],
        [3201.78256398,  691.7475212 ],
        [2498.2820824 ,  622.20400272],
        [1264.12201006,  673.19663082],
        [ 896.66559584,  650.33566864],
        [3332.45608195,  659.08642766],
        [1979.82379351,  640.74271528],
        [  89.12655281,  654.03840352],
        [ 303.48199738,  667.15132329],
        [ 750.02857038,  674.95871946],
        [2585.3712514 ,  678.99727375],
        [1041.04178871,  681.9626253 ],
        [1803.3936067 ,  704.47340941],
        [1555.70644162,  723.14660115],
        [3405.70734867,  768.37067218],
        [3241.86273299,  733.84514769],
        [1321.7457003 ,  723.58900894],
        [3617.30462037,  731.83923584],
        [2507.7238694 ,  800.29486919],
        [2748.93088927,  733.81529698],
        [1280.03888187,  818.20518921],
        [2685.27046717,  775.25909592],
        [2390.85115871,  779.27487389],
        [1591.92219603,  845.2125689 ],
        [2828.41431992,  871.68185866],
        [2201.19670118,  853.04193718],
        [1735.7800428 ,  841.09347455],
        [3458.51039541,  861.7195143 ],
        [1972.75602108,  854.39569017],
        [ 120.731508  ,  886.90541108],
        [2882.2532847 ,  905.97917124],
        [2524.53675233,  904.82507262],
        [ 932.3678314 ,  969.92488285],
        [1575.16824405,  993.4488148 ],
        [1807.82257673, 1007.12280215],
        [3333.0649769 ,  999.86706783],
        [ 773.41102683,  947.61875677],
        [ 284.10609879,  959.06216252],
        [ 497.4736964 ,  979.73291134],
        [2225.39350553, 1000.16238415],
        [3696.93086127,  971.46245319],
        [1995.85859515,  989.50722861],
        [2644.50406848,  984.92480523],
        [2833.32774086,  991.33289037],
        [2419.83649928, 1031.21970641],
        [ 160.33133589, 1029.6636449 ],
        [ 911.96422955, 1038.72080742],
        [ 454.28779293, 1113.24225254],
        [1700.08526426, 1094.3445267 ],
        [1221.63431643, 1099.0990847 ],
        [1112.19534884, 1148.05960379],
        [2232.03184323, 1094.75463722],
        [3399.1130064 , 1136.61822367],
        [  61.29568311, 1161.67871172],
        [1876.22688894, 1110.29227105],
        [1547.18240791, 1160.63696038],
        [3749.72236318, 1165.41544038],
        [ 890.46702625, 1151.31787127],
        [3046.18524753, 1156.17750015],
        [1422.40064627, 1216.90092516],
        [3486.17449856, 1230.53810253],
        [1226.12481137, 1208.17023553],
        [1054.37210409, 1236.69038915],
        [2621.84046479, 1282.68132213],
        [2057.28128828, 1268.881473  ],
        [2938.9299934 , 1244.21971303],
        [3590.83276685, 1257.04517854],
        [  94.92461119, 1252.10016694],
        [1335.34164611, 1262.42139584],
        [1988.31955394, 1303.63680003],
        [2327.34343958, 1303.39437175],
        [ 889.52249226, 1320.20092647],
        [2443.13189849, 1291.67761002],
        [2204.06103296, 1361.73965227],
        [1544.29099995, 1327.39641699],
        [ 419.39165595, 1327.92225694],
        [3346.41807776, 1318.80181567],
        [3693.08991533, 1334.4394505 ],
        [1219.13342172, 1368.27561448],
        [ 984.040602  , 1370.32109485],
        [2558.45107091, 1370.27607933],
        [3044.13334171, 1377.35904684],
        [ 864.58876585, 1393.98994168],
        [1454.51175901, 1371.61827784],
        [ 191.70624695, 1387.42654295],
        [3641.91293563, 1460.20224069],
        [2305.7723362 , 1440.09891102],
        [1118.32024019, 1398.83424785],
        [2707.10019346, 1416.87740136],
        [3227.34270917, 1409.31550802],
        [2221.72650769, 1434.33457933],
        [2921.07908107, 1473.30516899],
        [3554.3287273 , 1471.29218612],
        [1295.50491159, 1476.92443706],
        [ 355.8266573 , 1511.81041618],
        [ 116.15642362, 1473.97545114],
        [ 882.29519022, 1511.25729722],
        [2361.98924119, 1525.14229057],
        [3152.83812324, 1506.46739696],
        [2972.02625926, 1565.6324186 ],
        [2470.00945778, 1520.07798661],
        [2830.61741808, 1549.0290939 ],
        [ 288.19975996, 1563.63001688],
        [ 573.70103423, 1584.25213345],
        [1470.4916077 , 1597.57191048],
        [1776.28085789, 1545.62926758],
        [1101.43404864, 1587.77796853],
        [1682.51127654, 1590.78876518],
        [ 675.89760213, 1626.14005329],
        [1279.39684969, 1595.2956839 ],
        [3320.13914148, 1608.02267625],
        [3497.95531468, 1619.44848626],
        [2081.37590702, 1617.28356771],
        [2953.94136477, 1630.3601443 ],
        [ 287.66093078, 1664.32342589],
        [2701.42239766, 1654.80885709],
        [3707.69767497, 1705.99421731],
        [ 148.24182982, 1670.28227364],
        [1303.52284691, 1737.72703801],
        [1427.04920737, 1697.18908256],
        [1793.76353727, 1715.87023099],
        [1716.48131458, 1713.32036637],
        [ 737.92976971, 1684.68607164],
        [1135.74304645, 1711.05665592],
        [2226.19128253, 1770.35726978],
        [ 294.33239177, 1797.93416729],
        [3643.11343296, 1797.73150286],
        [ 520.08091986, 1805.67173857],
        [2774.58247155, 1820.80646836],
        [1902.57979014, 1830.34014678],
        [2476.06669732, 1782.50125185],
        [3384.94565831, 1807.46490476],
        [1161.50171332, 1830.06044739],
        [3486.11938257, 1840.91631389],
        [2120.43669659, 1809.1037702 ],
        [2284.9896765 , 1837.03763575],
        [ 442.1529577 , 1842.793299  ],
        [1472.52975463, 1849.28297452],
        [ 622.24233472, 1845.59094538],
        [ 246.40681428, 1842.45160047],
        [2379.6822327 , 1939.68113149],
        [2173.97696012, 1945.45057803],
        [ 133.58590432, 1941.11452739],
        [2761.45469447, 1920.89072034],
        [3591.97233663, 1905.88577847],
        [2016.33942466, 1917.59385456],
        [ 415.83480768, 1980.31761237],
        [3292.00015701, 2005.9388444 ],
        [ 169.83560894, 1974.63532149],
        [ 703.88488257, 1984.11746977],
        [2751.96790754, 2024.98681733],
        [1327.85691152, 2019.5760476 ],
        [ 907.75855893, 2073.27950592],
        [2554.35236438, 2052.42740321],
        [2143.81822466, 2041.12996937],
        [1586.64343307, 2097.83350174],
        [1870.60944914, 2115.17268413],
        [3456.83520464, 2129.31441909],
        [1261.12512263, 2145.87019848],
        [1962.07678026, 2156.19332814],
        [1034.95316762, 2109.24606551],
        [2424.0968848 , 2116.92419931],
        [2978.1347936 , 2146.36394271],
        [ 188.70649733, 2124.22315479],
        [ 901.45098962, 2194.65642452],
        [3144.89440382, 2154.22104045],
        [2565.2938105 , 2157.2678636 ],
        [ 750.39791021, 2236.60782398],
        [2677.66971625, 2235.69451539],
        [1611.23123035, 2214.53783171],
        [3519.84503895, 2179.4767539 ],
        [1206.34406184, 2224.58327477],
        [2842.31166569, 2229.62626856],
        [3624.24574575, 2205.95487154],
        [1027.40119106, 2282.181646  ],
        [ 436.86239181, 2241.64035365],
        [ 957.20271456, 2255.66663099],
        [2229.80564545, 2271.20290316],
        [3016.81352834, 2288.28679159],
        [1326.50647966, 2259.59826115],
        [2377.47054164, 2285.36241597],
        [2557.7005878 , 2315.18690301],
        [3785.7298096 , 2347.4163043 ],
        [2068.65436967, 2313.79657259],
        [ 760.21255486, 2313.26038583],
        [2469.63000044, 2317.46794843],
        [ 705.42876943, 2351.97719038],
        [2930.02001078, 2368.83491111],
        [1777.7265025 , 2371.72382055],
        [1146.70968877, 2402.62594345],
        [ 169.87530066, 2418.73752902],
        [3697.97434955, 2410.23178919],
        [2616.8631459 , 2438.55870725],
        [1356.24000771, 2427.03437636],
        [ 823.36782424, 2453.41121348],
        [3028.03090652, 2464.5592774 ],
        [1718.80994224, 2564.39911942],
        [ 361.77598318, 2562.29484753],
        [1259.68460539, 2499.39219382],
        [ 221.73847877, 2571.32838877],
        [ 470.        , 2514.86619145],
        [1127.90095828, 2542.63734392],
        [2884.43333517, 2532.67361916],
        [2340.5667368 , 2542.50265309],
        [ 578.09730875, 2561.41029879],
        [2043.72450614, 2572.62441989],
        [2574.57500386, 2556.20091148],
        [2449.14976808, 2623.05157189],
        [ 468.44868082, 2618.47112291],
        [ 687.97005797, 2596.31022644],
        [1463.56735956, 2637.25864921],
        [1717.25899848, 2630.99623421],
        [ 343.01778276, 2638.49917267],
        [3240.98210473, 2691.83253756],
        [2017.8007943 , 2702.01891193],
        [1860.71938851, 2658.14273115],
        [ 208.18820993, 2662.91725396],
        [2522.02595865, 2697.4439606 ],
        [ 510.00666273, 2737.07478225],
        [1290.37000493, 2707.01580515],
        [2993.55780687, 2733.03322002],
        [1030.2394705 , 2726.19780458],
        [2449.30371888, 2773.68867944],
        [1809.94721383, 2752.27014348],
        [2611.80099266, 2808.2106913 ],
        [3459.39767097, 2757.28107615],
        [1486.35491616, 2756.69895823],
        [1614.70589791, 2778.07406848],
        [ 424.8453315 , 2802.7131911 ],
        [3299.69120924, 2779.06880713],
        [ 215.09589722, 2784.29042685],
        [1735.07618216, 2884.56351354],
        [1827.89152506, 2852.24890456],
        [3697.71473857, 2894.74694891],
        [3471.83215449, 2875.5603458 ],
        [1498.41837969, 2880.75994025],
        [ 575.96723898, 2886.58128264],
        [2642.92862857, 2890.80205482],
        [ 941.91301979, 2867.48922113],
        [2590.34757742, 2886.39398057],
        [1657.34667354, 2961.93320268],
        [1366.94069162, 2984.57715667],
        [2103.64083071, 2922.30643768],
        [1742.84414951, 3000.30721187],
        [2760.62160788, 3034.24381674],
        [3075.63935668, 2976.64622121],
        [ 302.43542322, 3053.30673011],
        [3204.31367814, 3079.81288433],
        [3571.72721039, 3048.45988571],
        [1942.97539184, 3081.81858106],
        [1472.56499873, 3079.03788125],
        [ 150.76410877, 3123.4411538 ],
        [ 789.83390331, 3138.00233173],
        [ 368.07807407, 3113.2314483 ],
        [2827.06638421, 3092.07331921],
        [ 999.0762486 , 3083.94184905],
        [2632.9929194 , 3089.60652789],
        [2442.55383966, 3096.37776968],
        [3420.0425283 , 3112.89156092],
        [1235.86706218, 3181.77404234],
        [2927.07219866, 3147.11174697],
        [ 682.38009889, 3157.06976205],
        [1139.77130432, 3182.01042433],
        [1379.52912438, 3208.87815061],
        [3127.31439989, 3238.94182008],
        [3239.64831072, 3199.03606582],
        [1881.83319231, 3230.49594072],
        [ 856.73608626, 3214.01454698],
        [1982.39134654, 3224.34888799],
        [1314.47207441, 3246.58433205],
        [2798.30579864, 3251.57909112],
        [ 299.84784693, 3323.30935787],
        [ 441.97052941, 3292.42703784],
        [2991.24427189, 3259.88622237],
        [2544.49683024, 3313.86303514],
        [3165.75754337, 3336.36830086],
        [1616.02455448, 3322.41653335],
        [2157.72533161, 3343.98018441],
        [2645.24453961, 3412.47984093],
        [ 529.11631747, 3361.37929611],
        [1087.44073346, 3427.47547651],
        [2832.20264095, 3402.5697118 ],
        [2462.21230577, 3437.31944523],
        [1254.90645474, 3462.25214189],
        [1617.93716995, 3533.13926685],
        [1851.29674061, 3493.52301192],
        [ 677.81293784, 3542.73990162],
        [ 828.86846769, 3547.48329371],
        [ 332.74316032, 3517.14356017],
        [2956.30929814, 3536.81295741],
        [1119.21510952, 3580.14391893],
        [2245.42231788, 3544.21293805],
        [1747.92061348, 3586.28051494],
        [2550.90597186, 3596.38884193],
        [2656.91175075, 3597.24987192],
        [ 916.61552957, 3614.03600762],
        [1191.03325017, 3607.3726228 ],
        [2092.1600255 , 3669.56232069],
        [1316.03751586, 3601.44296302],
        [ 561.50338292, 3616.25004387],
        [1882.24628458, 3616.64523423],
        [ 165.75469875, 3616.52357947],
        [1499.02830066, 3629.30736783],
        [ 493.66013599, 3654.74399396],
        [2249.61030861, 3713.03501895],
        [1121.66980893, 3721.47838476],
        [2605.90228713, 3731.76470167],
        [2815.44237086, 3729.29369667],
        [ 718.65108566, 3681.59160343],
        [2992.4204592 , 3680.39391009],
        [2490.00398767, 3716.13577867],
        [ 147.34795984, 3744.54099659],
        [1428.48409907, 3739.88534695],
        [ 356.83393776, 3758.64324871],
        [2378.91006433, 3788.11861382]]),
 array([[3015.02500049,   56.20694962],
        [2013.19218788,   91.5659684 ],
        [2153.30928648,   77.19985658],
        [ 241.92722073,   67.7119571 ],
        [ 893.89493263,  153.60557193],
        [ 686.97382308,   94.47174004],
        [2425.27378519,   80.99896909],
        [1605.68874306,  168.14647385],
        [1071.42260311,  131.91280129],
        [ 121.11607458,  142.1383317 ],
        [ 620.33123016,  146.94420863],
        [1302.27954933,  126.78153336],
        [3053.77750175,  145.40664545],
        [2216.48553048,  207.3706248 ],
        [3283.08605319,  144.44170142],
        [1962.20943151,  154.30784383],
        [ 371.69465823,  194.84370952],
        [1169.71670309,  201.13229114],
        [1663.94774796,  220.43543366],
        [ 690.2349308 ,  267.93030615],
        [1834.2284172 ,  224.59266851],
        [2914.55264189,  213.67963332],
        [2062.42168409,  228.94015899],
        [3539.35214239,  241.98677227],
        [3196.12703878,  260.41378093],
        [2268.39117775,  298.90518424],
        [1439.10369783,  329.69183582],
        [3672.63350367,  255.51061981],
        [2391.08748972,  259.45319361],
        [3035.47547045,  275.12834197],
        [1189.34677493,  302.97662253],
        [1615.76321588,  292.3489918 ],
        [ 803.88092931,  287.74088638],
        [2790.05065615,  307.18821351],
        [ 645.02664385,  310.24528344],
        [1754.74083207,  356.00662275],
        [2180.90213969,  371.85092848],
        [ 398.43855976,  421.41084698],
        [ 920.90075429,  359.83884498],
        [1374.4017    ,  404.94084165],
        [2124.26674469,  390.87996879],
        [2331.16342941,  381.80268037],
        [3383.52880221,  400.50813271],
        [2792.59990625,  428.13634574],
        [3675.17937198,  514.95141975],
        [ 166.02145281,  485.7478347 ],
        [1588.93908118,  476.9585649 ],
        [2469.95531224,  457.45052191],
        [ 235.11105384,  476.01163369],
        [1304.78563387,  535.96012638],
        [1840.72198208,  512.88737653],
        [1461.92303922,  509.33473389],
        [1133.22647831,  529.57076881],
        [ 705.04455712,  559.5472075 ],
        [2083.02151681,  510.20679048],
        [2255.456909  ,  531.13545875],
        [1957.97833689,  528.97797773],
        [ 419.58876091,  573.79700485],
        [1051.86126378,  574.76764478],
        [2823.9644021 ,  579.43493092],
        [3177.70255594,  587.31055235],
        [3254.19341392,  603.80175073],
        [3377.93538314,  571.19926193],
        [2336.34733916,  574.19417476],
        [2625.97696594,  574.41529412],
        [3535.76531638,  613.85948948],
        [3770.40715234,  593.79887156],
        [ 151.98565805,  590.78678047],
        [ 474.54463305,  617.30149848],
        [1196.09682949,  634.96767531],
        [1058.57281491,  687.90949085],
        [ 661.54953836,  643.96455927],
        [1528.75835313,  651.84850712],
        [2688.05818288,  660.02240041],
        [ 865.97142737,  662.43460182],
        [2929.56997342,  697.1139376 ],
        [3074.1201373 ,  736.43742299],
        [1265.98573376,  690.47887324],
        [ 530.73385352,  766.52355709],
        [ 804.65948532,  777.72474688],
        [3308.5003202 ,  715.96016044],
        [3620.66280772,  739.83504133],
        [2086.46842725,  715.72641575],
        [2187.67413194,  755.45859375],
        [2321.75042328,  724.27000577],
        [3476.04901569,  816.96801769],
        [2483.3787896 ,  777.2261051 ],
        [ 418.35631738,  766.06445358],
        [1905.35788155,  840.28662601],
        [3693.35524425,  804.06461717],
        [ 251.71957139,  828.38425285],
        [2202.8320801 ,  859.81163612],
        [2793.5709591 ,  825.18556718],
        [ 719.56795596,  840.3214669 ],
        [3085.26369703,  829.67127129],
        [1997.61291156,  833.42595223],
        [3384.70379846,  863.04516827],
        [ 440.68402639,  891.94942651],
        [1693.18006982,  853.55397251],
        [3228.12388474,  849.41260787],
        [2696.78298901,  920.68063308],
        [ 574.05849691,  881.4397878 ],
        [3609.88606517,  912.3373224 ],

In [48]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [49]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [50]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1533.385008,185.888553,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1137.751224,190.983647,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,836.065221,222.396177,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,1468.909306,222.621017,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3139.607780,203.263351,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
44279,187.596708,3822.751979,00489@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44280,3118.995883,3832.416690,00490@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44281,1520.634516,3910.051350,00491@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44282,3442.556439,3863.055085,00492@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44283,2607.636085,3894.444668,00493@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [51]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [52]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [53]:
nms_config

(0.5, 0.6)

In [54]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [55]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3471
Number of Particles: 654
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 605
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 673
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3238
Number of Particles: 450
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3280
Number of Particles: 460
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3419
Number of Particles: 612
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3174
Number of Particles: 453
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3390
Number of Particles: 502
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3453
Number of Particles: 646
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3484
Number of Particles: 660
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3343
Number of Particles: 617
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 533
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 621
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3422
Number of Particles: 527
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 696
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 625
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 577
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3206
Number of Particles: 583
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3285
Number of Particles: 567
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 642
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 644
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 673
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3357
Number of Particles: 679
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3435
Number of Particles: 738
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 638
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 651
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3484
Number of Particles: 662
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 664
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 576
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 665
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3463
Number of Particles: 693
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 621
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3466
Number of Particles: 639
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 678
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 602
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3482
Number of Particles: 654
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3365
Number of Particles: 604
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3454
Number of Particles: 655
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2982
Number of Particles: 571
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3464
Number of Particles: 685
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 612
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3245
Number of Particles: 450
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3130
Number of Particles: 457
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3241
Number of Particles: 456
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3281
Number of Particles: 458
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 635
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3432
Number of Particles: 627
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 630
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 623
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3426
Number of Particles: 557
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3447
Number of Particles: 548
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3444
Number of Particles: 571
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3227
Number of Particles: 486
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3464
Number of Particles: 616
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 711
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3375
Number of Particles: 701
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 686
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3289
Number of Particles: 508
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3364
Number of Particles: 519
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3292
Number of Particles: 473
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3211
Number of Particles: 472
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3230
Number of Particles: 447
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3203
Number of Particles: 423
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3336
Number of Particles: 480
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3394
Number of Particles: 518
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3318
Number of Particles: 506
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3344
Number of Particles: 520
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3336
Number of Particles: 513
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3026
Number of Particles: 462
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3387
Number of Particles: 514
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3388
Number of Particles: 510
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3340
Number of Particles: 499
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3453
Number of Particles: 552
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3310
Number of Particles: 477
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3357
Number of Particles: 536
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3376
Number of Particles: 464
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3281
Number of Particles: 487
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3355
Number of Particles: 515
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3315
Number of Particles: 552
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3253
Number of Particles: 517
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3357
Number of Particles: 570

In [56]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [57]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [58]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,2301.6,3761.6,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,3466.0,727.0,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,2799.2,3099.0,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,341.4,2346.6,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,1139.2,1790.4,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
48471,2609.8,3897.6,00565@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
48472,3354.0,620.0,00566@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
48473,3840.0,1791.0,00567@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
48474,3503.0,2047.0,00568@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
48475,3150.0,2175.2,00569@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [59]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')

In [60]:
# @markdown ---
# @markdown time used
end_time = time.time()
print(f"End time recorded: {end_time}")

elapsed_time = end_time - start_time
elapsed_time = elapsed_time


hours = int(elapsed_time // 3600)
remaining_seconds = elapsed_time % 3600

minutes = int(remaining_seconds // 60)
seconds = round(remaining_seconds % 60, 3)

print(f"Time spend : {hours} h, {minutes} m, {seconds} s")


gpu_used = "L4" # @param ["CPU high", "T4", "T4 high", "L4"]
per_unit_cost_dict = {"L4" : 1.71, "T4 high" : 1.41, "T4" : 1.19, "CPU high" :  0.24}
per_unit_cost = per_unit_cost_dict[gpu_used]
print(f"unit price per hr {per_unit_cost}")

cost_units = per_unit_cost * elapsed_time / 3600

per_unit_US = 10.49 / 100

cost_price_US = cost_units * per_unit_US

print(f"unit cost : {round(cost_units, 4)}")
print(f"unit price US: {cost_price_US}")
print(f"unit price NTD: {cost_price_US * 30.76}")

NameError: name 'time' is not defined