<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [2]:
%pip install torchinfo -qq
%pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
%pip install starfile -qq
%pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for segmentation_models_pytorch (pyproject.toml) ... done
     / 10.7 MB 16.2 MB/s 0:00:01
  Preparing metadata (setup.py) ... done
  Building wheel for trackpy (setup.py) ... done

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [3]:
%pip install pycuda==2024.1
%pip install "numpy<2.0"
%pip install mrcfile -qq

Collecting pycuda==2024.1
  Downloading pycuda-2024.1.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 31.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytools>=2011.2 (from pycuda==2024.1)
  Downloading pytools-2025.2.5-py3-none-any.whl.metadata (2.9 kB)
Collecting appdirs>=1.4.0 (from pycuda==2024.1)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: mako in /usr/local/lib/python3.12/dist-packages (from pycuda==2024.1) (1.3.10)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.5.0)
Collecting siphash24>=1.6 (from pytools>=2011.2->pycuda==2024.1)
  Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: typing-extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.15.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from mako->pycuda==2024.1) (3.0.3)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading pytools-2025.2.5-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.8/98.8 kB 10.3 MB/s eta 0:00:00
Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 10.4 MB/s eta 0:00:00
Building wheels for collected packages: pycuda
  Building wheel for pycuda (pyproject.toml) ... done
  Created wheel for pycuda: filename=pycuda-2024.1-cp312-cp312-linux_x86_64.whl size=658547 sha256=2961836722e8360b4bd9540aef51043b723e3aa65c984d06009f44ec245b1973
  Stored in directory: /root/.cache/pip/wheels/16/8d/d0/cf29b67ddc32f77bc3344b6b2b38dd9fe8595c726c33eabc03
Successfully built pycuda
Installing collected packages: appdirs, siphash24, pytools, pycuda
Successfully installed appdirs-1.4.4 pycuda-2024.1 pytools-2025.2.5 siphash24-1.8
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.1 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 116.2 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.9 MB/s eta 0:00:00

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [1]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C-CSN-D_float-u_output/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C-CSN-D_float-u_output/results/10017_test/unet_eb5_dice_CDCRF" # @param {type:"string"}

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
IMAGE_DIR = "/content/image_dir"

In [8]:
!git clone https://github.com/phonchi/CryoParticleSegment.git

Cloning into 'CryoParticleSegment'...
remote: Enumerating objects: 270, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 270 (delta 141), reused 42 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (270/270), 32.01 MiB | 16.73 MiB/s, done.
Resolving deltas: 100% (141/141), done.

In [3]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

> #### ⚠ Notice
>
> You need to restart the kernel after the compilation step. Additionally, if your GPU architecture differs, you may need to modify the file at `/content/CryoParticleSegment/Modeling/CRF_main/setup.py`. (We attempt to detect the GPU configuration automatically, so this step is usually not necessary.)
> Furthermore, depending on the number of classes and other parameters, you may encounter an error that requires adjusting the file at `/content/CryoParticleSegment/Modeling/CRF_main/src/PermutohedralFiltering/source/gpu/LatticeFilter.cu`:
>
> 1. Note the `pd` and `vd` values from the error message.
> 2. Add an `else if (pd == ? && vd == ?)` block.
> 3. Within that block, insert the following line, replacing `pd` and `vd` with the specific values:
>
>    ```cpp
>    latticeFilterGPU<pd, vd>(output_tensor, input_tensor, positions, num_super_pixels, backward);
>    ```
> 4. Recompile using `setup.py`.

In [10]:
#%git clone https://github.com/netw0rkf10w/CRF.git
%cd CryoParticleSegment/Modeling/CRF_main
!python setup.py clean --all
!rm -rf build/
!python setup.py build_ext --inplace --force
!python setup.py install

/content/CryoParticleSegment/Modeling/CRF_main
running clean
'build/lib.linux-x86_64-cpython-312' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.12' does not exist -- can't clean it
running build_ext
W1015 04:40:41.856000 3990 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
W1015 04:40:41.926000 3990 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1015 04:40:41.927000 3990 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
building 'Permutohedral' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral -std=c++17
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp: In function ‘at::Tensor LatticeFilter_calculate(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool)’:
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:77:97: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
   77 |         at::Tensor positions = at::zeros({batch_size * num_super_pixels * pd}, input_tensor.type() );
      |                                                                                ~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/extension.h:5,
                 from src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:25:
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
creating build/lib.linux-x86_64-cpython-312
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so
building 'Permutohedral_gpu' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/cuda/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/gpu/LatticeFilter.cu -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -gencode=arch=compute_89,code=sm_89 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral_gpu -std=c++17
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu: In function ‘at::Tensor LatticeFilter_calculate_gpu(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool, bool)’:
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:202:91: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  202 |     at::Tensor positions = at::zeros(
      |                                                                                           ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:208:67: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  208 |     CHECK_INPUT(image_tensor);
      |                                                                   ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:209:64: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  209 |     CHECK_INPUT(positions);
      |                                                                ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:213:44: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  213 |         auto ref_ptr = &(image_tensor.data<float>()[b * num_super_pixels * n_reference_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:214:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  214 |         auto pos_ptr = &(positions.data<float>()[b * num_super_pixels * pd]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:215:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  215 |         auto in_ptr = &(input_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:216:45: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  216 |         auto out_ptr = &(output_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> src
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> src
running install
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating src/CRF.egg-info
writing src/CRF.egg-info/PKG-INFO
writing dependency_links to src/CRF.egg-info/dependency_links.txt
writing top-level names to src/CRF.egg-info/top_level.txt
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
W1015 04:42:31.135000 4502 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
reading manifest file 'src/CRF.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/CRF.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/sparsemax.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/__init__.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/convcrf.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/crfs_cpu.py -> build/lib.linux-x86_64-cpython-312/CRF
creating build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/PermutohedralFiltering.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/setup.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/__init__.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
running build_ext
W1015 04:42:31.186000 4502 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1015 04:42:31.186000 4502 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/CRF.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/sparsemax.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/__init__.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/convcrf.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/crfs_cpu.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/PermutohedralFiltering.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/setup.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/__init__.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/CRF/CRF.py to CRF.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/sparsemax.py to sparsemax.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/__init__.py to __init__.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/convcrf.py to convcrf.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/crfs_cpu.py to crfs_cpu.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/PermutohedralFiltering.py to PermutohedralFiltering.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/setup.py to setup.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/__init__.py to __init__.cpython-312.pyc
creating stub loader for Permutohedral.cpython-312-x86_64-linux-gnu.so
creating stub loader for Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral.py to Permutohedral.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral_gpu.py to Permutohedral_gpu.cpython-312.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
CRF.__pycache__.crfs_cpu.cpython-312: module references __file__
__pycache__.Permutohedral.cpython-312: module references __file__
__pycache__.Permutohedral_gpu.cpython-312: module references __file__
creating dist
creating 'dist/CRF-0.0.1-py3.12-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CRF-0.0.1-py3.12-linux-x86_64.egg
creating /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Extracting CRF-0.0.1-py3.12-linux-x86_64.egg to /usr/local/lib/python3.12/dist-packages
Adding CRF 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Processing dependencies for CRF==0.0.1
Finished processing dependencies for CRF==0.0.1

In [4]:
%cd /content/

/content

### ✅ Packages Handling

In [5]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [6]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [7]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 8
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [8]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [9]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [10]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

config.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/122M [00:00<?, ?B/s]

In [11]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [12]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [13]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [14]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [15]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [16]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:28<00:00,  2.98it/s]

In [17]:
processed_micrographs.shape

(84, 3840, 3840)

In [18]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [19]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [20]:
del model
torch.cuda.empty_cache()

In [21]:
model = model_post

In [22]:
RESULT_DIR

'/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/C-CSN-D_float-u_output/results/10017_test/unet_eb5_dice_CDCRF'

In [23]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [24]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [25]:
!cp {RESULT_DIR}/label_images.npy .

In [26]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [27]:
label_images.shape

(84, 3840, 3840)

In [28]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [29]:
!cp {RESULT_DIR}/best_config.txt .

In [30]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [31]:
radius = RADIUS

In [32]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [33]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

549 472
542 471
481 373
394 386
404 380
490 416
335 332
458 411
534 450
584 503
522 459
518 474
537 467
478 449
573 484
539 474
519 458
532 472
498 454
561 494
551 462
533 447
530 463
533 416
482 385
488 394
505 399
544 436
524 423
561 507
536 462
492 383
535 448
539 457
526 447
532 439
514 434
544 447
544 496
526 441
429 385
543 450
562 501
388 375
285 283
399 359
325 320
524 506
569 489
497 421
522 448
522 444
541 471
563 551
563 509
492 448
517 436
585 527
446 349
503 421
446 438
479 425
492 453
478 446
455 424
460 431
406 385
458 402
393 341
431 377
455 402
162 162
453 400
475 435
424 392
488 426
454 437
458 404
465 432
359 356
433 370
455 398
407 351
430 375

In [34]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [35]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [36]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [37]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1508,3951,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1235,3949,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,248,3948,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,753,3944,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3712,3944,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
35815,1982,172,00370@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35816,2355,187,00371@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35817,316,148,00372@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35818,2855,154,00373@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35819,3602,161,00374@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [38]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [39]:
cv_list

[[(1380, 3823),
  (1107, 3821),
  (120, 3820),
  (625, 3816),
  (3584, 3816),
  (2410, 3815),
  (3041, 3808),
  (1187, 3803),
  (2823, 3783),
  (2695, 3789),
  (3684, 3767),
  (1565, 3780),
  (2950, 3760),
  (3822, 3734),
  (3200, 3748),
  (975, 3732),
  (1295, 3730),
  (467, 3684),
  (1789, 3680),
  (365, 3669),
  (1136, 3652),
  (3713, 3661),
  (1530, 3657),
  (3257, 3631),
  (2767, 3658),
  (2985, 3628),
  (1439, 3667),
  (3053, 3647),
  (3809, 3622),
  (3689, 3570),
  (997, 3591),
  (755, 3564),
  (3089, 3557),
  (3226, 3548),
  (1127, 3538),
  (1908, 3538),
  (3808, 3527),
  (39, 3530),
  (2016, 3546),
  (874, 3502),
  (674, 3518),
  (2363, 3491),
  (3000, 3493),
  (137, 3485),
  (1577, 3475),
  (3476, 3496),
  (2777, 3458),
  (601, 3470),
  (1774, 3463),
  (3783, 3458),
  (764, 3428),
  (1480, 3437),
  (2267, 3423),
  (999, 3411),
  (16, 3408),
  (2930, 3403),
  (2640, 3413),
  (513, 3409),
  (3148, 3374),
  (2807, 3360),
  (882, 3378),
  (672, 3350),
  (210, 3358),
  (1597, 3340),
  (2143, 3338),
  (3371, 3319),
  (331, 3321),
  (2662, 3302),
  (3816, 3285),
  (1070, 3301),
  (3620, 3288),
  (897, 3280),
  (1875, 3265),
  (3169, 3229),
  (2806, 3222),
  (327, 3211),
  (1219, 3191),
  (2600, 3206),
  (500, 3203),
  (3545, 3192),
  (2692, 3185),
  (3744, 3190),
  (1075, 3168),
  (630, 3213),
  (2143, 3150),
  (3156, 3137),
  (793, 3123),
  (1950, 3167),
  (1598, 3121),
  (235, 3139),
  (3822, 3086),
  (1272, 3109),
  (3303, 3103),
  (3558, 3093),
  (607, 3085),
  (3450, 3091),
  (2305, 3083),
  (3645, 3043),
  (3365, 3031),
  (3243, 3026),
  (3823, 2995),
  (1347, 2998),
  (378, 3010),
  (24, 2954),
  (2316, 2966),
  (3284, 2949),
  (2078, 2942),
  (2903, 2941),
  (2786, 2934),
  (3821, 2921),
  (2579, 2938),
  (266, 2929),
  (891, 2915),
  (1140, 2880),
  (3029, 2873),
  (3359, 2852),
  (1234, 2855),
  (2511, 2824),
  (2698, 2820),
  (3598, 2817),
  (29, 2756),
  (869, 2772),
  (2785, 2727),
  (3247, 2744),
  (2872, 2750),
  (1040, 2747),
  (3026, 2724),
  (2506, 2727),
  (2588, 2740),
  (3692, 2705),
  (1989, 2684),
  (478, 2672),
  (2953, 2658),
  (3555, 2653),
  (684, 2652),
  (3238, 2646),
  (1737, 2646),
  (967, 2635),
  (31, 2604),
  (591, 2612),
  (252, 2596),
  (1637, 2602),
  (2676, 2581),
  (2522, 2573),
  (1332, 2565),
  (1546, 2590),
  (2138, 2587),
  (3237, 2549),
  (122, 2542),
  (3803, 2532),
  (2336, 2547),
  (3345, 2545),
  (3700, 2515),
  (2601, 2509),
  (2259, 2515),
  (394, 2488),
  (1886, 2478),
  (744, 2459),
  (1625, 2472),
  (3538, 2462),
  (1712, 2458),
  (2358, 2444),
  (1337, 2433),
  (3453, 2421),
  (3157, 2413),
  (120, 2398),
  (3815, 2402),
  (1560, 2404),
  (439, 2394),
  (3740, 2388),
  (597, 2401),
  (3040, 2379),
  (324, 2376),
  (3620, 2371),
  (1405, 2361),
  (2838, 2351),
  (2041, 2348),
  (1730, 2343),
  (1914, 2345),
  (2657, 2316),
  (193, 2333),
  (51, 2330),
  (1088, 2313),
  (1590, 2306),
  (3100, 2313),
  (22, 2263),
  (2354, 2288),
  (79, 2257),
  (361, 2277),
  (3276, 2293),
  (593, 2268),
  (2633, 2220),
  (3764, 2277),
  (1995, 2238),
  (509, 2233),
  (2752, 2220),
  (3821, 2214),
  (1605, 2216),
  (3249, 2190),
  (2463, 2190),
  (460, 2154),
  (775, 2169),
  (1600, 2136),
  (3003, 2185),
  (642, 2125),
  (3575, 2121),
  (3396, 2120),
  (2346, 2109),
  (2537, 2105),
  (3485, 2107),
  (58, 2128),
  (1054, 2086),
  (2155, 2078),
  (2012, 2049),
  (27, 2043),
  (2667, 2088),
  (915, 2044),
  (2570, 2036),
  (3583, 2031),
  (690, 2035),
  (321, 2025),
  (3780, 2037),
  (425, 2008),
  (1330, 2011),
  (220, 2005),
  (3191, 2013),
  (1728, 1972),
  (822, 1966),
  (3344, 1921),
  (2596, 1935),
  (2735, 1949),
  (1101, 1921),
  (910, 1914),
  (2880, 1900),
  (1308, 1904),
  (3217, 1888),
  (3442, 1917),
  (3654, 1874),
  (1032, 1839),
  (93, 1863),
  (670, 1858),
  (2754, 1841),
  (2136, 1810),
  (3820, 1818),
  (3004, 1810),
  (1395, 1805),
  (990, 1786),
  (2849, 1749),
  (494, 1773),
  (2567, 1779),
  (2120, 1729),
  (1096, 1762),
  (46, 1712),
  (1581, 1729),
  (2793, 1693),
  (3427, 1685),
  (2647, 1681),
  (1408, 1678),
  (3621, 1681),
  (1935, 1671),
  (3816, 1646),
  (568, 1654),
  (3311, 1650),
  (2229, 1657),
  (1853, 1646),
  (2713, 1625),
  (2988, 1623),
  (342, 1594),
  (1552, 1587),
  (3813, 1550),
  (3248, 1563),
  (1360, 1564),
  (3088, 1551),
  (155, 1557),
  (452, 1541),
  (1892, 1543),
  (1269, 1538),
  (2696, 1531),
  (968, 1519),
  (3610, 1508),
  (3711, 1497),
  (3166, 1501),
  (1457, 1481),
  (877, 1476),
  (207, 1472),
  (3252, 1446),
  (424, 1450),
  (764, 1452),
  (3735, 1414),
  (1186, 1408),
  (495, 1392),
  (2216, 1398),
  (3413, 1358),
  (1400, 1387),
  (1090, 1389),
  (2693, 1389),
  (2318, 1385),
  (3663, 1381),
  (787, 1330),
  (3291, 1351),
  (1263, 1319),
  (2448, 1316),
  (1963, 1327),
  (1756, 1349),
  (3176, 1306),
  (1058, 1292),
  (1448, 1285),
  (2828, 1283),
  (3525, 1275),
  (411, 1267),
  (909, 1255),
  (2610, 1253),
  (3014, 1244),
  (58, 1254),
  (1349, 1240),
  (2282, 1220),
  (1830, 1206),
  (1241, 1213),
  (570, 1215),
  (1434, 1183),
  (2740, 1176),
  (2521, 1185),
  (2152, 1178),
  (3821, 1147),
  (2067, 1153),
  (1521, 1151),
  (3318, 1165),
  (3483, 1135),
  (2996, 1107),
  (1799, 1084),
  (1307, 1075),
  (869, 1115),
  (2648, 1066),
  (2430, 1065),
  (1061, 1069),
  (1935, 1036),
  (1827, 1001),
  (2818, 1021),
  (1350, 977),
  (1094, 985),
  (749, 984),
  (2246, 975),
  (65, 973),
  (3411, 960),
  (479, 962),
  (2050, 945),
  (3818, 912),
  (1260, 942),
  (1372, 906),
  (1850, 917),
  (1748, 915),
  (3143, 898),
  (1095, 883),
  (965, 867),
  (2410, 863),
  (3434, 849),
  (449, 831),
  (3067, 823),
  (2710, 822),
  (3789, 816),
  (3178, 810),
  (1174, 810),
  (1875, 783),
  (353, 798),
  (1369, 795),
  (2954, 792),
  (3361, 791),
  (1826, 761),
  (2483, 781),
  (1276, 784),
  (922, 780),
  (37, 751),
  (1955, 743),
  (1427, 735),
  (3701, 713),
  (940, 690),
  (749, 678),
  (168, 672),
  (21, 659),
  (1142, 653),
  (852, 659),
  (537, 647),
  (1802, 641),
  (1032, 631),
  (1518, 617),
  (2482, 610),
  (1332, 615),
  (3152, 595),
  (625, 585),
  (33, 560),
  (458, 559),
  (2297, 555),
  (2616, 535),
  (1631, 571),
  (2382, 538),
  (123, 524),
  (3362, 501),
  (1726, 525),
  (1449, 518),
  (3621, 519),
  (598, 505),
  (1346, 518),
  (3179, 507),
  (1132, 506),
  (2940, 505),
  (1061, 477),
  (2836, 494),
  (481, 479),
  (3300, 457),
  (76, 455),
  (3696, 456),
  (3810, 448),
  (3444, 450),
  (232, 440),
  (1441, 423),
  (1653, 413),
  (348, 417),
  (2289, 401),
  (1228, 370),
  (3238, 343),
  (20, 354),
  (1582, 355),
  (1409, 342),
  (461, 308),
  (954, 325),
  (860, 314),
  (1775, 304),
  (2541, 336),
  (178, 283),
  (1639, 296),
  (3532, 271),
  (1883, 274),
  (3185, 259),
  (3764, 275),
  (301, 263),
  (1315, 237),
  (723, 232),
  (1728, 236),
  (882, 214),
  (2468, 194),
  (1132, 209),
  (2335, 224),
  (2932, 177),
  (782, 163),
  (3268, 144),
  (2020, 139),
  (2563, 136),
  (168, 117),
  (2180, 111),
  (595, 110),
  (3148, 88),
  (2715, 102),
  (338, 109),
  (1529, 81),
  (1341, 95),
  (708, 94),
  (1799, 94),
  (1010, 59),
  (2825, 76),
  (2935, 58),
  (3217, 50),
  (3000, 70),
  (1873, 35),
  (127, 26),
  (3095, 25),
  (2076, 27),
  (1195, 87),
  (805, 34),
  (208, 20),
  (2309, 23),
  (3464, 63),
  (2691, 21)],
 [(276, 3814),
  (2460, 3816),
  (730, 3817),
  (3003, 3805),
  (1743, 3805),
  (3767, 3803),
  (1455, 3809),
  (861, 3808),
  (959, 3797),
  (2589, 3802),
  (2164, 3792),
  (1185, 3794),
  (3606, 3788),
  (2785, 3786),
  (1876, 3774),
  (1653, 3776),
  (2259, 3777),
  (505, 3766),
  (1307, 3755),
  (1580, 3752),
  (163, 3758),
  (2672, 3721),
  (734, 3733),
  (353, 3725),
  (2427, 3726),
  (1124, 3702),
  (35, 3709),
  (1394, 3701),
  (965, 3698),
  (2955, 3690),
  (2760, 3670),
  (2400, 3645),
  (3400, 3674),
  (401, 3645),
  (1071, 3612),
  (561, 3635),
  (2585, 3619),
  (1103, 3586),
  (3337, 3606),
  (3204, 3601),
  (1483, 3592),
  (1341, 3589),
  (245, 3614),
  (2249, 3569),
  (1642, 3563),
  (2875, 3585),
  (874, 3550),
  (3039, 3536),
  (2157, 3530),
  (760, 3534),
  (1742, 3521),
  (161, 3481),
  (483, 3476),
  (2259, 3461),
  (2439, 3481),
  (3412, 3452),
  (2539, 3465),
  (3613, 3452),
  (2328, 3444),
  (294, 3438),
  (2756, 3435),
  (1523, 3428),
  (3303, 3419),
  (2954, 3415),
  (67, 3406),
  (963, 3400),
  (3174, 3406),
  (1674, 3379),
  (2967, 3339),
  (182, 3361),
  (1221, 3351),
  (1124, 3348),
  (2655, 3325),
  (1557, 3332),
  (1319, 3348),
  (964, 3301),
  (3443, 3287),
  (3340, 3250),
  (2574, 3273),
  (160, 3268),
  (1657, 3261),
  (42, 3250),
  (1237, 3246),
  (3029, 3261),
  (2363, 3270),
  (799, 3220),
  (2163, 3234),
  (2868, 3223),
  (600, 3222),
  (2417, 3192),
  (2711, 3190),
  (1039, 3162),
  (1069, 3154),
  (22, 3172),
  (1305, 3168),
  (942, 3172),
  (3611, 3166),
  (1416, 3129),
  (2631, 3128),
  (3258, 3103),
  (1903, 3091),
  (573, 3085),
  (312, 3089),
  (1118, 3088),
  (2729, 3074),
  (2120, 3060),
  (1218, 3021),
  (1456, 3016),
  (3477, 2985),
  (2262, 3019),
  (227, 3014),
  (3723, 2969),
  (793, 2963),
  (3274, 2943),
  (1811, 2940),
  (1899, 2903),
  (3438, 2891),
  (3820, 2874),
  (3572, 2886),
  (2917, 2860),
  (569, 2871),
  (2173, 2868),
  (3176, 2855),
  (1369, 2843),
  (239, 2847),
  (3654, 2831),
  (2986, 2813),
  (499, 2812),
  (2105, 2813),
  (3394, 2815),
  (2348, 2808),
  (1582, 2810),
  (57, 2796),
  (1461, 2792),
  (3815, 2767),
  (2476, 2770),
  (3224, 2762),
  (3037, 2713),
  (422, 2740),
  (1957, 2743),
  (517, 2705),
  (3724, 2702),
  (2357, 2687),
  (1599, 2700),
  (1701, 2691),
  (3278, 2674),
  (45, 2671),
  (239, 2660),
  (3084, 2655),
  (1785, 2643),
  (1244, 2636),
  (3660, 2629),
  (3507, 2586),
  (1582, 2604),
  (474, 2610),
  (1887, 2596),
  (3490, 2564),
  (3368, 2586),
  (1146, 2625),
  (2514, 2580),
  (2013, 2580),
  (2733, 2567),
  (1436, 2552),
  (3241, 2551),
  (3627, 2545),
  (1805, 2519),
  (1337, 2519),
  (2900, 2506),
  (149, 2498),
  (1070, 2491),
  (3579, 2481),
  (1651, 2487),
  (1419, 2476),
  (827, 2471),
  (2752, 2465),
  (3107, 2446),
  (3416, 2453),
  (40, 2440),
  (1983, 2426),
  (1312, 2422),
  (3530, 2411),
  (3035, 2407),
  (1607, 2366),
  (2065, 2368),
  (1860, 2409),
  (346, 2355),
  (905, 2360),
  (1732, 2338),
  (2651, 2344),
  (3186, 2307),
  (45, 2317),
  (3505, 2318),
  (520, 2351),
  (805, 2321),
  (1130, 2318),
  (2494, 2289),
  (257, 2305),
  (160, 2264),
  (2607, 2273),
  (2375, 2273),
  (589, 2271),
  (3060, 2264),
  (2900, 2265),
  (375, 2265),
  (1643, 2254),
  (704, 2258),
  (21, 2252),
  (1313, 2259),
  (985, 2263),
  (482, 2229),
  (1837, 2229),
  (2658, 2199),
  (2937, 2183),
  (151, 2187),
  (1454, 2164),
  (3347, 2152),
  (3439, 2168),
  (872, 2143),
  (365, 2136),
  (84, 2135),
  (2694, 2122),
  (2051, 2107),
  (2395, 2121),
  (965, 2111),
  (2214, 2120),
  (3645, 2112),
  (700, 2067),
  (2856, 2056),
  (1643, 2055),
  (428, 2059),
  (3780, 2036),
  (530, 2043),
  (45, 2027),
  (1528, 2011),
  (2077, 2014),
  (603, 2004),
  (329, 1981),
  (2316, 1957),
  (3606, 1962),
  (1769, 1954),
  (3797, 1931),
  (1154, 1921),
  (2747, 1943),
  (3180, 1925),
  (1469, 1927),
  (2492, 1912),
  (3267, 1905),
  (1898, 1900),
  (813, 1879),
  (43, 1837),
  (2840, 1841),
  (3536, 1820),
  (2607, 1835),
  (569, 1837),
  (1975, 1822),
  (1628, 1849),
  (948, 1854),
  (1813, 1811),
  (2156, 1803),
  (2737, 1800),
  (3316, 1755),
  (2279, 1764),
  (2838, 1743),
  (2696, 1712),
  (3171, 1716),
  (597, 1730),
  (1954, 1717),
  (760, 1744),
  (3009, 1749),
  (3348, 1674),
  (834, 1722),
  (2168, 1693),
  (1763, 1691),
  (3456, 1671),
  (2323, 1653),
  (1951, 1639),
  (1615, 1643),
  (80, 1656),
  (1021, 1627),
  (1411, 1609),
  (3202, 1597),
  (1721, 1579),
  (2263, 1573),
  (3660, 1557),
  (520, 1553),
  (1465, 1551),
  (72, 1544),
  (2110, 1523),
  (2509, 1537),
  (3350, 1550),
  (154, 1508),
  (2772, 1512),
  (420, 1485),
  (1313, 1478),
  (2277, 1460),
  (1728, 1466),
  (2201, 1452),
  (3006, 1440),
  (3669, 1439),
  (842, 1423),
  (237, 1398),
  (3740, 1400),
  (2074, 1396),
  (3306, 1358),
  (109, 1374),
  (1079, 1382),
  (1554, 1377),
  (1768, 1356),
  (2820, 1380),
  (17, 1339),
  (1649, 1358),
  (2238, 1322),
  (2555, 1294),
  (3358, 1294),
  (921, 1288),
  (379, 1285),
  (1810, 1272),
  (2946, 1253),
  (2108, 1260),
  (2393, 1250),
  (466, 1219),
  (1511, 1232),
  (2294, 1228),
  (3575, 1219),
  (3751, 1218),
  (1886, 1206),
  (1359, 1200),
  (106, 1225),
  (1055, 1199),
  (241, 1206),
  (1468, 1160),
  (3636, 1144),
  (467, 1130),
  (664, 1134),
  (2256, 1146),
  (1653, 1117),
  (807, 1116),
  (3086, 1114),
  (3769, 1097),
  (2699, 1085),
  (1166, 1079),
  (556, 1065),
  (1956, 1063),
  (45, 1055),
  (2072, 1042),
  (365, 1051),
  (2598, 1040),
  (1383, 1017),
  (732, 974),
  (3383, 936),
  (325, 948),
  (1606, 983),
  (2357, 936),
  (623, 953),
  (193, 943),
  (18, 918),
  (1357, 915),
  (3708, 941),
  (2497, 911),
  (1835, 922),
  (3134, 901),
  (1093, 863),
  (2900, 878),
  (3039, 848),
  (1584, 858),
  (2793, 831),
  (2148, 798),
  (3325, 812),
  (219, 791),
  (679, 829),
  (960, 776),
  (3747, 772),
  (1801, 766),
  (1639, 766),
  (2430, 757),
  (808, 759),
  (3417, 751),
  (1392, 748),
  (3201, 752),
  (565, 732),
  (2271, 718),
  (157, 720),
  (2667, 757),
  (1300, 713),
  (2131, 725),
  (3577, 700),
  (1729, 680),
  (686, 689),
  (1443, 653),
  (1196, 653),
  (863, 660),
  (2388, 645),
  (2285, 625),
  (3473, 643),
  (1616, 608),
  (2166, 595),
  (3546, 606),
  (1925, 589),
  (3823, 540),
  (572, 539),
  (2273, 536),
  (2386, 543),
  (3363, 521),
  (772, 530),
  (1764, 528),
  (1621, 512),
  (1281, 506),
  (1859, 511),
  (3177, 495),
  (3259, 507),
  (1167, 476),
  (3481, 476),
  (371, 466),
  (2453, 443),
  (3382, 431),
  (1323, 418),
  (3078, 415),
  (283, 387),
  (1858, 392),
  (3816, 377),
  (481, 376),
  (2023, 376),
  (3162, 364),
  (2640, 373),
  (3457, 368),
  (2949, 326),
  (2269, 342),
  (3667, 315),
  (1486, 313),
  (347, 304),
  (1633, 306),
  (3058, 293),
  (919, 268),
  (54, 255),
  (3507, 251),
  (2163, 287),
  (2266, 232),
  (279, 230),
  (3733, 225),
  (432, 215),
  (2987, 191),
  (1436, 188),
  (557, 210),
  (651, 188),
  (51, 178),
  (3176, 165),
  (3376, 169),
  (2107, 159),
  (779, 159),
  (1356, 142),
  (890, 156),
  (684, 121),
  (1526, 141),
  (1184, 129),
  (945, 96),
  (715, 96),
  (75, 71),
  (3281, 68),
  (3704, 63),
  (1987, 43),
  (848, 39),
  (3793, 33),
  (2561, 52),
  (2198, 57),
  (2082, 47),
  (1751, 45),
  (582, 23),
  (3569, 61),
  (260, 51),
  (2725, 36),
  (1360, 17)],
 [(25, 3814),
  (2897, 3819),
  (1708, 3820),
  (3429, 3815),
  (2354, 3805),
  (489, 3797),
  (3286, 3803),
  (3557, 3796),
  (1272, 3799),
  (3696, 3784),
  (803, 3738),
  (1126, 3734),
  (1360, 3722),
  (21, 3729),
  (2918, 3727),
  (2307, 3721),
  (178, 3687),
  (3736, 3689),
  (690, 3682),
  (3304, 3676),
  (3392, 3642),
  (1226, 3665),
  (2415, 3662),
  (1970, 3630),
  (1534, 3656),
  (1808, 3648),
  (52, 3619),
  (162, 3592),
  (376, 3584),
  (3811, 3566),
  (3095, 3555),
  (3380, 3555),
  (2114, 3548),
  (2360, 3519),
  (1683, 3535),
  (227, 3524),
  (830, 3494),
  (3218, 3460),
  (2924, 3461),
  (3776, 3433),
  (3811, 3431),
  (3622, 3417),
  (2343, 3419),
  (3709, 3412),
  (2662, 3395),
  (337, 3371),
  (3223, 3339),
  (901, 3367),
  (2097, 3394),
  (3125, 3356),
  (1532, 3332),
  (2191, 3317),
  (3634, 3285),
  (222, 3289),
  (444, 3315),
  (3818, 3260),
  (2547, 3292),
  (1698, 3252),
  (99, 3243),
  (3548, 3269),
  (529, 3251),
  (2117, 3239),
  (1926, 3243),
  (1321, 3232),
  (951, 3222),
  (2004, 3200),
  (3619, 3189),
  (1159, 3177),
  (3077, 3163),
  (1789, 3159),
  (3756, 3153),
  (397, 3139),
  (3466, 3132),
  (512, 3135),
  (2628, 3129),
  (2129, 3121),
  (2476, 3090),
  (1896, 3089),
  (3785, 3071),
  (1230, 3070),
  (2333, 3068),
  (611, 3054),
  (3473, 3019),
  (2632, 3006),
  (859, 3028),
  (2780, 2996),
  (1253, 2983),
  (1828, 2975),
  (1946, 3001),
  (103, 3006),
  (2178, 2957),
  (332, 2941),
  (2912, 2938),
  (185, 2930),
  (3635, 2962),
  (908, 2902),
  (2324, 2905),
  (1564, 2857),
  (2174, 2829),
  (1741, 2819),
  (1146, 2814),
  (3433, 2810),
  (185, 2780),
  (469, 2765),
  (2088, 2777),
  (3671, 2759),
  (3056, 2758),
  (995, 2743),
  (3292, 2729),
  (371, 2735),
  (2585, 2755),
  (2683, 2706),
  (3550, 2713),
  (1953, 2694),
  (1743, 2681),
  (33, 2664),
  (535, 2670),
  (3061, 2664),
  (630, 2670),
  (373, 2629),
  (791, 2631),
  (2842, 2617),
  (1456, 2607),
  (2085, 2583),
  (3340, 2567),
  (2495, 2590),
  (1001, 2610),
  (64, 2575),
  (3552, 2573),
  (3113, 2521),
  (1152, 2524),
  (800, 2524),
  (210, 2493),
  (401, 2492),
  (1732, 2480),
  (1602, 2510),
  (3682, 2477),
  (3257, 2443),
  (1456, 2472),
  (93, 2437),
  (3364, 2412),
  (3707, 2383),
  (3598, 2370),
  (1940, 2358),
  (2086, 2349),
  (335, 2353),
  (1044, 2328),
  (3021, 2331),
  (457, 2328),
  (3248, 2347),
  (3414, 2324),
  (1371, 2305),
  (493, 2287),
  (1246, 2348),
  (2925, 2302),
  (25, 2262),
  (2210, 2252),
  (1158, 2270),
  (171, 2268),
  (2054, 2254),
  (3476, 2247),
  (759, 2240),
  (1821, 2236),
  (343, 2218),
  (939, 2176),
  (1976, 2190),
  (3586, 2181),
  (1203, 2158),
  (1684, 2143),
  (1461, 2124),
  (3025, 2134),
  (2509, 2138),
  (909, 2097),
  (176, 2111),
  (475, 2099),
  (820, 2129),
  (1617, 2088),
  (3583, 2087),
  (2812, 2069),
  (1199, 2066),
  (2958, 2038),
  (1082, 2016),
  (1699, 2009),
  (3089, 2004),
  (706, 2006),
  (1529, 1990),
  (2277, 1995),
  (966, 1967),
  (89, 1924),
  (3036, 1915),
  (3351, 1885),
  (841, 1927),
  (2175, 1890),
  (185, 1869),
  (924, 1831),
  (516, 1887),
  (2128, 1819),
  (3263, 1833),
  (2038, 1816),
  (861, 1803),
  (2518, 1786),
  (281, 1787),
  (2942, 1802),
  (980, 1780),
  (413, 1758),
  (2258, 1776),
  (3768, 1789),
  (130, 1749),
  (21, 1741),
  (1227, 1712),
  (3511, 1700),
  (2887, 1695),
  (601, 1700),
  (3064, 1672),
  (498, 1660),
  (19, 1633),
  (1083, 1647),
  (1586, 1621),
  (3655, 1652),
  (2576, 1608),
  (3265, 1607),
  (3169, 1590),
  (1743, 1569),
  (3540, 1580),
  (815, 1583),
  (2965, 1571),
  (2820, 1570),
  (2736, 1542),
  (1312, 1593),
  (3669, 1542),
  (934, 1530),
  (96, 1523),
  (636, 1512),
  (3343, 1514),
  (1437, 1534),
  (1650, 1498),
  (1807, 1456),
  (2794, 1460),
  (22, 1414),
  (665, 1394),
  (1917, 1376),
  (875, 1372),
  (1364, 1395),
  (747, 1364),
  (2578, 1354),
  (241, 1353),
  (3530, 1387),
  (2277, 1311),
  (2455, 1323),
  (393, 1313),
  (3743, 1299),
  (3817, 1258),
  (65, 1256),
  (3329, 1284),
  (843, 1254),
  (1111, 1257),
  (3064, 1236),
  (1362, 1214),
  (1234, 1197),
  (297, 1193),
  (195, 1197),
  (2044, 1211),
  (573, 1163),
  (3610, 1141),
  (3075, 1140),
  (3751, 1134),
  (1428, 1130),
  (3223, 1129),
  (2265, 1132),
  (1280, 1095),
  (3698, 1075),
  (2058, 1068),
  (3353, 1051),
  (1858, 1041),
  (1155, 1034),
  (667, 1031),
  (20, 1016),
  (927, 1006),
  (264, 1016),
  (3482, 999),
  (1683, 991),
  (2435, 944),
  (3663, 934),
  (1908, 942),
  (577, 936),
  (3758, 949),
  (80, 937),
  (2636, 953),
  (1556, 906),
  (1024, 891),
  (728, 896),
  (472, 891),
  (145, 921),
  (3381, 876),
  (3228, 874),
  (2611, 841),
  (646, 855),
  (2531, 848),
  (2416, 850),
  (3144, 823),
  (910, 794),
  (35, 808),
  (1051, 773),
  (1230, 770),
  (3786, 754),
  (2383, 743),
  (850, 742),
  (2151, 736),
  (139, 712),
  (943, 719),
  (3391, 715),
  (3250, 696),
  (2862, 686),
  (2666, 693),
  (2547, 681),
  (2275, 670),
  (1158, 651),
  (3659, 627),
  (2422, 630),
  (3320, 599),
  (543, 613),
  (2540, 594),
  (960, 608),
  (2748, 583),
  (1361, 582),
  (2632, 581),
  (49, 601),
  (321, 542),
  (3739, 536),
  (219, 510),
  (2973, 460),
  (888, 456),
  (3566, 441),
  (2748, 426),
  (2007, 407),
  (1805, 385),
  (1712, 373),
  (2658, 361),
  (3135, 355),
  (81, 340),
  (3052, 319),
  (1159, 293),
  (1922, 263),
  (1712, 278),
  (2434, 288),
  (3340, 239),
  (2637, 252),
  (83, 251),
  (1058, 249),
  (2017, 238),
  (2322, 214),
  (3633, 207),
  (542, 216),
  (3498, 196),
  (2737, 146),
  (1751, 163),

In [40]:
tp_config

(0.25, 0.4)

In [41]:
import trackpy as tp

In [42]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [43]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

617
578
628
354
391
564
307
473
611
635
573
501
582
482
667
593
548
558
520
601
609
647
605
693
604
603
626
657
631
586
575
653
595
587
599
632
572
639
563
621
443
633
577
358
241
417
290
480
624
582
596
587
573
526
583
497
584
603
636
595
388
500
470
445
451
440
391
498
434
474
497
132
477
462
431
525
418
487
439
309
493
499
445
474

In [44]:
tp_list

[array([[1008.15981535,   59.07580883],
        [1531.18396358,  109.10529889],
        [1337.6066628 ,   95.79841915],
        ...,
        [2031.1929988 , 3746.56552955],
        [3200.10854964, 3744.10976213],
        [3682.91655054, 3765.02032954]]),
 array([[ 225.71250198,   78.946104  ],
        [1978.90775616,   41.3108959 ],
        [1779.18996387,   52.06089887],
        ...,
        [ 470.03747113, 3762.25454229],
        [2589.86142876, 3790.7481053 ],
        [2778.31194238, 3782.86582823]]),
 array([[3723.09324041,   41.55350042],
        [2100.00955285,   55.08145644],
        [2961.20820096,  100.94514339],
        ...,
        [ 799.10276498, 3740.53559472],
        [2746.17143929, 3780.34190342],
        [3689.3751791 , 3778.92205931]]),
 array([[1436.26279029,   71.98690414],
        [1254.99855659,   67.94219328],
        [1787.41822869,  149.19705944],
        [2385.19616491,  101.7071908 ],
        [3446.74953172,  172.8563598 ],
        [3219.74694561,  191.83732218],
        [3313.33502168,  194.08618242],
        [ 164.86514077,  159.70275104],
        [1066.01807153,  136.36237211],
        [2671.63624178,  175.84761027],
        [3013.47032901,  145.49889003],
        [2403.23677051,  228.6458305 ],
        [ 620.62202313,  211.0103377 ],
        [2709.48796188,  282.64153152],
        [ 820.48894073,  278.46053234],
        [ 380.36254119,  242.84917396],
        [1578.35949688,  251.83063101],
        [2972.91001512,  282.0023685 ],
        [3586.03289575,  305.24362934],
        [2527.781631  ,  357.59914336],
        [1247.6539184 ,  312.80805659],
        [2419.52464796,  357.19228832],
        [2833.41941876,  311.19778365],
        [1368.78827285,  369.38771328],
        [ 736.94424297,  328.47026292],
        [1754.28447054,  347.85684072],
        [1850.08596265,  366.91992731],
        [3335.81373847,  334.96907447],
        [1953.84191045,  397.58591045],
        [1073.04992959,  365.10440471],
        [ 953.38345731,  432.83559752],
        [1482.35550857,  439.03851908],
        [2273.92767025,  393.35726854],
        [1194.88765993,  418.30037144],
        [2830.26353597,  442.79082234],
        [ 752.64462546,  455.79595911],
        [1864.15903657,  504.14132649],
        [ 308.20660457,  446.64000521],
        [2155.38807066,  491.57596516],
        [2629.7815668 ,  472.31118367],
        [2387.19593116,  443.27430362],
        [ 678.2402633 ,  512.97092704],
        [2508.08508833,  504.91629022],
        [ 941.52216767,  506.81251137],
        [1351.73850682,  550.11750931],
        [2224.17866871,  557.84729316],
        [1572.67886078,  536.0621325 ],
        [2054.47540065,  503.89786694],
        [2924.11463583,  543.2003953 ],
        [3241.56922386,  565.88106389],
        [1529.82358511,  575.14323807],
        [3073.37481749,  571.5931461 ],
        [ 126.43141585,  620.64784844],
        [3732.64779425,  637.02127495],
        [ 617.11592509,  581.5853105 ],
        [1977.91474096,  636.29900756],
        [2621.81038085,  600.1418113 ],
        [2761.66309196,  680.71154978],
        [2497.9609936 ,  621.72970215],
        [3201.25131594,  691.62800169],
        [1282.47428621,  685.70365843],
        [ 897.16382979,  652.21673759],
        [ 405.64417999,  660.98438081],
        [1047.72953328,  677.32792655],
        [ 750.12850417,  675.1758783 ],
        [3245.15865968,  735.06156104],
        [1804.85726753,  706.48527792],
        [3625.85323541,  724.0031612 ],
        [1553.87869732,  722.98153257],
        [3406.59735029,  769.34665429],
        [1315.54686995,  722.02277437],
        [2746.44940909,  751.14185873],
        [2698.16475146,  775.87082288],
        [2390.38889697,  778.09254948],
        [1587.72852435,  838.95928231],
        [1284.59383643,  823.19083366],
        [2199.30544482,  854.05531636],
        [1733.64927643,  838.62298887],
        [2825.88648009,  877.57948083],
        [3458.01741599,  863.7532607 ],
        [1972.18793829,  853.29086991],
        [2892.82083669,  904.0839099 ],
        [2517.89106657,  901.17746728],
        [ 119.62626205,  883.20056708],
        [ 938.13175633,  972.82501817],
        [ 772.14736697,  947.95401266],
        [1803.25168046, 1010.22040614],
        [ 282.13990118,  960.10775609],
        [2228.93352954, 1000.02152617],
        [ 499.60678406,  981.04427213],
        [2364.86741231,  999.39277676],
        [ 634.80998081, 1009.32037052],
        [3697.27394418,  972.39999278],
        [1994.41832093,  988.32678678],
        [2832.65863454,  988.67380181],
        [1574.61041459,  981.57870647],
        [3324.24945244, 1004.98811255],
        [ 160.27639535, 1029.87897059],
        [2993.21985489, 1068.03178625],
        [ 330.93640842, 1072.14778325],
        [1697.86213438, 1095.2812869 ],
        [1224.13055825, 1096.52115461],
        [1110.81953055, 1149.05955791],
        [2232.90032232, 1093.34238517],
        [3396.11093849, 1134.18884861],
        [3745.97028528, 1164.62079265],
        [  61.55883607, 1164.12776413],
        [1873.47581885, 1108.01245484],
        [1544.85135551, 1161.21819162],
        [3052.15428934, 1154.75807591],
        [ 885.8453415 , 1148.63588545],
        [1435.84745064, 1218.30727157],
        [1231.64320936, 1206.73606352],
        [1050.11180644, 1233.45871617],
        [2444.47107609, 1280.49570169],
        [2621.04840275, 1284.58083298],
        [2055.97885505, 1269.02833343],
        [2936.53206155, 1242.97388644],
        [3482.18825273, 1231.52143784],
        [  94.85244263, 1250.79518291],
        [1331.4909203 , 1263.15969272],
        [2327.59569771, 1301.15116774],
        [1986.74923279, 1301.16191729],
        [ 893.07361762, 1317.15982114],
        [3583.54731714, 1261.99706283],
        [2203.6544194 , 1355.16527587],
        [3345.90566439, 1318.64031407],
        [1448.31959539, 1349.93228557],
        [2558.59106459, 1370.78067067],
        [ 987.96869627, 1370.59538821],
        [1218.33627217, 1368.87235764],
        [ 854.21636603, 1400.07422022],
        [ 192.24747704, 1394.53856294],
        [2307.71224542, 1440.40775797],
        [1115.53866307, 1402.69593522],
        [2707.7992126 , 1413.22951918],
        [3225.13564794, 1409.06125844],
        [3141.13074584, 1485.16358433],
        [2218.0408672 , 1439.2254819 ],
        [3557.62212907, 1469.59820103],
        [2939.59889703, 1528.70984375],
        [1295.92350445, 1475.65353892],
        [3634.76129537, 1459.60641285],
        [2831.13557688, 1547.27169859],
        [ 340.70568013, 1519.60356278],
        [ 877.43965367, 1513.49286038],
        [2359.58065337, 1523.98871447],
        [ 575.02749159, 1584.10080837],
        [1468.90181239, 1572.37004581],
        [1772.57039824, 1545.32572907],
        [3495.71435468, 1615.69207345],
        [1685.09446224, 1587.36466819],
        [1090.53907986, 1581.51425901],
        [ 684.33101349, 1634.29292635],
        [1277.61941289, 1593.94556719],
        [3317.64828729, 1608.6223558 ],
        [2079.77237484, 1622.33738553],
        [ 288.29322288, 1663.0864729 ],
        [2701.03759587, 1656.24766589],
        [2947.08870863, 1640.53181798],
        [1781.01650229, 1707.26908828],
        [ 738.4450906 , 1679.81765315],
        [1717.3643162 , 1713.14553072],
        [3700.88839674, 1706.02694508],
        [1134.66197715, 1710.16724428],
        [1410.01523124, 1706.68002623],
        [2210.16871921, 1753.60221675],
        [ 295.42288791, 1799.02441508],
        [1302.68032689, 1735.31943392],
        [ 510.96807162, 1808.63841395],
        [2474.61973717, 1774.94515753],
        [2773.6876902 , 1821.04047474],
        [2956.61828109, 1780.63695754],
        [1901.01515128, 1834.06539618],
        [3635.87111192, 1814.22552395],
        [3386.35963633, 1807.52663179],
        [1161.16461605, 1829.75724967],
        [2285.63671741, 1836.96684598],
        [2118.93183468, 1809.34283641],
        [ 624.88292304, 1840.30391293],
        [ 453.31707608, 1838.76137245],
        [1488.35713349, 1846.75510472],
        [ 258.03257729, 1840.08531563],
        [3779.42064519, 1895.99335759],
        [2170.36597659, 1948.82436671],
        [2756.80485126, 1919.16805492],
        [3489.77037519, 1898.60045129],
        [3592.25313703, 1905.79892569],
        [2011.72345233, 1917.59138686],
        [ 369.63689396, 1957.76274321],
        [2379.551652  , 1939.77593421],
        [2971.56918487, 1988.24250963],
        [ 176.26490201, 1982.76068318],
        [ 705.22634594, 1984.23364054],
        [1326.45205555, 2017.78745574],
        [2740.04010627, 2027.07071369],
        [ 907.24882591, 2072.86437473],
        [3289.10447823, 2071.38573538],
        [2554.59384507, 2054.10180403],
        [2135.29920275, 2044.3253284 ],
        [1869.38331586, 2114.03406461],
        [1585.4548165 , 2092.5460858 ],
        [3457.22039962, 2128.13155274],
        [1259.47486866, 2137.9119679 ],
        [2422.03976655, 2119.39310022],
        [1034.68308813, 2108.25011146],
        [1144.72580645, 2155.21863799],
        [1959.55969287, 2155.37260568],
        [2979.11637568, 2139.03912873],
        [3153.92931693, 2149.10515009],
        [ 187.2008507 , 2124.84109785],
        [2564.38163686, 2155.46961683],
        [3718.12855767, 2151.81752359],
        [1610.44529187, 2210.7475066 ],
        [3518.8999046 , 2177.13698521],
        [2847.38242698, 2222.4239521 ],
        [3622.65610089, 2205.82447171],
        [1209.90611168, 2228.98833844],
        [ 857.75446808, 2214.20129855],
        [ 751.03672697, 2238.42863898],
        [1026.13141969, 2284.95935558],
        [ 433.77532358, 2245.05423467],
        [3014.28727811, 2286.82107988],
        [2234.78108964, 2268.13400298],
        [1331.93337163, 2265.53622056],
        [2373.56649051, 2286.86329377],
        [2466.22661822, 2317.8402189 ],
        [3785.14737916, 2346.38888773],
        [2066.23101509, 2315.73289639],
        [1777.68029319, 2370.65177659],
        [ 703.02399588, 2354.74839231],
        [3439.72070681, 2393.95625322],
        [2928.18976358, 2368.83372182],
        [1145.11624765, 2402.12998124],
        [3704.60495273, 2412.62185225],
        [ 167.71428047, 2423.13616436],
        [2616.62385643, 2440.43526664],
        [ 825.78296575, 2443.45834678],
        [ 469.26164284, 2512.10748728],
        [2145.84558843, 2484.28759997],
        [3026.32711392, 2464.85855218],
        [1717.81988351, 2561.75456919],
        [ 220.17365247, 2567.54178536],
        [ 361.86395022, 2561.54999574],
        [1258.30578572, 2500.0720513 ],
        [1128.58752485, 2541.11212494],
        [2883.65298008, 2529.21434359],
        [2338.50310906, 2543.56305804],
        [1929.10100363, 2572.59748025],
        [ 576.69667408, 2559.8014429 ],
        [2575.56160754, 2552.84035036],
        [2043.51224069, 2572.12162133],
        [ 467.55512967, 2618.66388918],
        [ 689.71331248, 2594.68981987],
        [ 342.6971286 , 2637.576405  ],
        [1717.35142868, 2630.69089975],
        [3240.00514259, 2689.36824061],
        [1861.04346827, 2660.35540911],
        [ 208.52431344, 2662.08088771],
        [2519.8460009 , 2695.352502  ],
        [3590.4440197 , 2730.46063368],
        [1290.39916954, 2709.41368446],
        [1487.4375    , 2730.80709135],
        [1997.33907077, 2741.6030703 ],
        [2995.22709177, 2731.46249563],
        [2452.9242492 , 2778.96168724],
        [1034.67861253, 2727.97811498],
        [1806.89509877, 2753.05470632],
        [ 510.59659772, 2733.24093225],
        [3457.54332276, 2757.77671263],
        [1614.4513021 , 2777.60611266],
        [ 424.44534747, 2795.2171967 ],
        [2613.14535419, 2808.34480221],
        [ 215.39682946, 2783.23301798],
        [3300.6394052 , 2781.64447822],
        [3697.21423053, 2890.44692984],
        [1499.39158508, 2880.86500333],
        [ 579.22019965, 2888.03480489],
        [3484.44689007, 2876.38283665],
        [2641.9061624 , 2889.85467247],
        [ 941.40362747, 2865.24070942],
        [2587.95044176, 2883.95442267],
        [1362.61861843, 2992.42846284],
        [3637.41478392, 2959.0575134 ],
        [1659.437108  , 2963.06095358],
        [2102.4366823 , 2925.53044272],
        [2753.6186927 , 3026.22858319],
        [1745.81282799, 2999.94835485],
        [3073.34481221, 2979.83495112],
        [3564.76791584, 3049.56402951],
        [ 305.87019953, 3060.61714224],
        [1472.53255883, 3066.54675072],
        [ 790.64775199, 3137.41580132],
        [2827.94437495, 3091.42550217],
        [3204.14893382, 3070.17117814],
        [ 997.78039331, 3084.51684315],
        [2436.3629712 , 3089.05311861],
        [2632.90151369, 3088.38711755],
        [3414.73407165, 3108.95851265],
        [2925.87445417, 3147.14007809],
        [ 150.67684397, 3123.61671682],
        [ 681.97267552, 3156.74049336],
        [3126.06661258, 3234.73449251],
        [1381.56945154, 3208.50017376],
        [1236.0145627 , 3183.74962842],
        [3239.08088649, 3200.23294709],
        [ 856.56161254, 3214.82293393],
        [1882.69050132, 3233.93087071],
        [1983.25660645, 3227.22371223],
        [2796.56266439, 3249.93324195],
        [ 441.88717075, 3290.75589789],
        [2983.58155239, 3247.10206545],
        [2543.58612572, 3311.50914227],
        [3168.20347601, 3337.69916935],
        [1617.22355688, 3318.63958816],
        [2156.69498343, 3344.46576796],
        [ 291.88937221, 3330.04243258],
        [ 534.01614698, 3370.96595707],
        [2829.97717189, 3399.66967225],
        [1079.74017862, 3434.13078799],
        [2460.39890449, 3437.53126616],
        [2617.79341768, 3444.33348396],
        [1254.25113868, 3462.20837383],
        [1616.99540498, 3533.63419003],
        [1848.95484712, 3492.78144781],
        [ 677.72204271, 3541.08322658],
        [ 810.74869924, 3549.13758515],
        [ 334.03522946, 3518.25844333],
        [2958.06273896, 3538.19673271],
        [1118.25920089, 3578.10521925],
        [2244.85776563, 3542.90094454],
        [1745.48145767, 3586.95712966],
        [2550.48747372, 3595.9903644 ],
        [2656.12597261, 3603.01213819],
        [1880.8       , 3615.14275362],
        [2090.39446367, 3670.88048211],
        [ 917.612553  , 3613.60558822],
        [1315.19137176, 3603.43715455],
        [ 161.10772388, 3612.53370405],
        [ 559.98184047, 3619.2494828 ],
        [1495.49533797, 3631.54208956],
        [2249.27452179, 3712.79351908],
        [2989.45545564, 3678.94754797],
        [1612.34645019, 3647.4232251 ],
        [1124.34094559, 3718.27675238],
        [ 709.65050261, 3685.75589684],
        [2813.89115544, 3728.17997742],
        [2507.66338935, 3712.98945299],
        [2605.32846715, 3729.61113059],
        [ 146.77713878, 3746.83179312],
        [ 363.21361424, 3740.87927767],
        [1425.31156398, 3744.63766734],
        [1299.89513468, 3786.16009759],
        [2378.18680764, 3787.1200791 ]]),
 array([[3008.90039109,   57.40929045],
        [3571.57923217,   67.99450673],
        [2011.34725055,   93.97122622],
        [ 242.0579592 ,   64.8353423 ],
        [2148.69837191,   72.54917391],
        [2303.46031058,   75.91420144],
        [2421.80522291,   71.34360121],
        [ 894.31208933,  152.57370903],
        [ 693.16715727,   92.45031936],
        [1603.29079851,  164.53169299],
        [ 119.59909919,  141.17625669],
        [1069.9235492 ,  133.46408409],
        [ 570.22356598,  178.34024728],
        [1302.26068037,  126.03909515],
        [2912.94780669,  212.17982186],
        [3281.00530743,  141.49435726],
        [2215.52631229,  208.60488324],
        [3050.86373953,  145.1969946 ],
        [1961.4275279 ,  149.67298263],
        [ 372.16226078,  194.75247598],
        [1673.2137937 ,  219.68761839],
        [2056.58466359,  244.15624338],
        [ 692.70540815,  267.19617258],
        [1833.00508147,  224.23790665],
        [2510.0354248 ,  263.96774885],
        [2283.91437397,  302.12503891],
        [1436.10737217,  324.45300534],
        [3196.04839033,  260.31672051],
        [3672.48191424,  256.4187026 ],
        [2389.33305998,  258.74581578],
        [1190.01435858,  303.07227408],
        [1609.22424108,  294.97828495],
        [3037.72160845,  285.31704051],
        [ 807.13603751,  286.37377473],
        [2790.80443534,  309.64751519],
        [3518.98696998,  302.52457974],
        [ 611.18083891,  331.14933899],
        [ 399.04963297,  421.93593594],
        [ 920.73153263,  354.12853823],
        [1751.4268995 ,  354.76387474],
        [2184.01397787,  359.01835674],
        [1369.8661313 ,  407.36103982],
        [2328.2711735 ,  372.27507528],
        [3382.80751758,  399.9151524 ],
        [2791.14124944,  431.62730521],
        [2467.4300205 ,  459.41946017],
        [ 236.11566795,  475.1160711 ],
        [1304.94153568,  533.44332617],
        [1840.6508364 ,  512.00872435],
        [3597.28433568,  537.97617026],
        [2610.27115682,  549.03253344],
        [1461.15948001,  512.08481624],
        [1131.65499779,  527.4167437 ],
        [2086.86212891,  510.00095436],
        [2255.06413545,  530.10236018],
        [ 414.17557824,  566.25826388],
        [3671.24515348,  536.8171636 ],
        [3180.10887522,  588.28776245],
        [2823.74028727,  578.35868516],
        [3255.30854753,  603.67987222],
        [3373.98376015,  573.71071652],
        [2340.88553956,  583.13710956],
        [ 152.3359251 ,  588.85663281],
        [3533.73401072,  615.82714512],
        [2686.39722344,  661.00131581],
        [ 845.69824537,  647.30268173],
        [ 478.8352264 ,  618.07388456],
        [1195.86286218,  636.17829679],
        [1007.31175276,  677.34258215],
        [1058.48878251,  688.70315371],
        [1529.15506464,  651.03558744],
        [ 660.91165354,  641.28992126],
        [2929.22237117,  696.97427923],
        [3103.73525261,  733.01360429],
        [1262.05736372,  684.92404138],
        [3304.52595697,  714.77455528],
        [2084.37984069,  715.26403113],
        [3615.80473139,  741.44494825],
        [2186.7206691 ,  754.41181091],
        [2318.84846487,  723.11767102],
        [ 530.62670891,  762.82591901],
        [1906.54106889,  827.58560618],
        [ 417.04471375,  764.7602173 ],
        [2482.86941089,  777.63722066],
        [3694.48294456,  804.63728093],
        [ 250.33718215,  820.60003198],
        [3475.25133813,  814.68794923],
        [ 825.13908354,  810.63660711],
        [2203.88967986,  858.74434869],
        [2790.3359375 ,  824.1286169 ],
        [ 719.00935604,  840.86269386],
        [3381.00098823,  860.1217321 ],
        [1996.66817196,  833.6156196 ],
        [3081.03000839,  829.1927812 ],
        [1689.03569682,  848.99535452],
        [ 444.10957611,  891.91719581],
        [2690.41802068,  922.37478179],
        [3226.99106642,  848.92318618],
        [ 574.19643557,  880.54455538],
        [3607.80897562,  911.51696383],
        [ 654.24863518,  968.42370524],
        [1300.18438623,  917.61757349],
        [2408.36763361,  944.39977431],
        [ 852.92460185,  947.54018636],
        [2150.85908788,  940.54829298],
        [2557.41127918,  963.1599114 ],
        [3721.26310511,  943.51737705],
        [1007.64087392,  977.54665453],
        [1445.39901994, 1020.08647079],
        [1818.3370007 ,  981.1269096 ],
        [2914.4384519 ,  989.28922481],
        [3606.29002012, 1024.69075652],
        [ 131.20038217,  998.75677066],
        [ 448.86664158,  992.69351399],
        [3316.42328397, 1009.42691627],
        [1642.52127894, 1073.32291699],
        [3140.25083573, 1021.66003125],
        [1269.28009583, 1068.82930725],
        [1510.13169425, 1093.18520672],
        [3317.40532261, 1123.38970792],
        [1944.16488822, 1101.48712924],
        [2742.17508739, 1133.51653264],
        [ 350.88878126, 1186.93499844],
        [ 632.16423312, 1109.56381594],
        [3609.17815982, 1117.80706781],
        [  93.43060695, 1135.48574317],

In [45]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [46]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [47]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1136.159815,187.075809,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1659.183964,237.105299,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1465.606663,223.798419,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3141.530302,202.549092,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3610.554923,199.886462,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
44079,1620.113750,3862.186700,00469@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44080,1531.633428,3905.345010,00470@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44081,3369.605005,3909.355045,00471@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44082,3447.613768,3857.282884,00472@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
44083,2636.591622,3885.684692,00473@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [48]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [49]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [50]:
nms_config

(0.5, 0.6)

In [51]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [52]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3470
Number of Particles: 656
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 602
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 686
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3263
Number of Particles: 440
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3261
Number of Particles: 451
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3426
Number of Particles: 625
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3001
Number of Particles: 482
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3407
Number of Particles: 514
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 660
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3488
Number of Particles: 669
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3422
Number of Particles: 615
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3425
Number of Particles: 522
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 616
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3413
Number of Particles: 518
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3488
Number of Particles: 714
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 632
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 584
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3363
Number of Particles: 597
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3286
Number of Particles: 554
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 640
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3483
Number of Particles: 647
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 683
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 654
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 768
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3450
Number of Particles: 650
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 642
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 657
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3483
Number of Particles: 700
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 680
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 613
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 633
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 694
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3478
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 642
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3470
Number of Particles: 629
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3484
Number of Particles: 673
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 615
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 674
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3404
Number of Particles: 596
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3454
Number of Particles: 665
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3202
Number of Particles: 516
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3471
Number of Particles: 688
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 609
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3170
Number of Particles: 435
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2888
Number of Particles: 514
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3312
Number of Particles: 476
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3098
Number of Particles: 527
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3388
Number of Particles: 505
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 672
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3438
Number of Particles: 632
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 626
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3480
Number of Particles: 617
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3444
Number of Particles: 612
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3438
Number of Particles: 523
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3459
Number of Particles: 623
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3349
Number of Particles: 530
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 630
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3434
Number of Particles: 644
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3419
Number of Particles: 709
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 673
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3214
Number of Particles: 474
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3428
Number of Particles: 532
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3366
Number of Particles: 516
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3367
Number of Particles: 482
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3400
Number of Particles: 482
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3365
Number of Particles: 479
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3256
Number of Particles: 463
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3404
Number of Particles: 540
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3337
Number of Particles: 501
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3370
Number of Particles: 521
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3341
Number of Particles: 563
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2158
Number of Particles: 589
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3405
Number of Particles: 523
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3425
Number of Particles: 506
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3331
Number of Particles: 493
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 557
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3351
Number of Particles: 464
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3390
Number of Particles: 549
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3404
Number of Particles: 483
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3079
Number of Particles: 464
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3381
Number of Particles: 537
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3321
Number of Particles: 555
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3266
Number of Particles: 511
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3337
Number of Particles: 564

In [53]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [54]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [55]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,2458.0,359.0,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,2301.6,3759.2,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,351.0,2891.8,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,1137.6,1788.8,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,2255.0,577.0,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
49037,2688.0,1535.0,00559@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49038,3840.0,1791.0,00560@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49039,2048.0,3328.0,00561@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49040,2687.0,3712.0,00562@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
49041,558.0,3904.0,00563@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [56]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')