<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [1]:
%pip install torchinfo -qq
%pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
%pip install starfile -qq
%pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for segmentation_models_pytorch (pyproject.toml) ... done
     / 10.7 MB 10.1 MB/s 0:00:01
  Preparing metadata (setup.py) ... done
  Building wheel for trackpy (setup.py) ... done

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [2]:
%pip install pycuda==2024.1
%pip install "numpy<2.0"
%pip install mrcfile -qq

Collecting pycuda==2024.1
  Downloading pycuda-2024.1.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 57.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytools>=2011.2 (from pycuda==2024.1)
  Downloading pytools-2025.2.5-py3-none-any.whl.metadata (2.9 kB)
Collecting appdirs>=1.4.0 (from pycuda==2024.1)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: mako in /usr/local/lib/python3.12/dist-packages (from pycuda==2024.1) (1.3.10)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.5.0)
Collecting siphash24>=1.6 (from pytools>=2011.2->pycuda==2024.1)
  Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: typing-extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.15.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from mako->pycuda==2024.1) (3.0.3)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading pytools-2025.2.5-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.8/98.8 kB 14.7 MB/s eta 0:00:00
Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 14.2 MB/s eta 0:00:00
Building wheels for collected packages: pycuda
  Building wheel for pycuda (pyproject.toml) ... done
  Created wheel for pycuda: filename=pycuda-2024.1-cp312-cp312-linux_x86_64.whl size=658547 sha256=767d83147c175704e9bea9408f2c9703a2c37fa2c09d322d518247142dc7a8f0
  Stored in directory: /root/.cache/pip/wheels/16/8d/d0/cf29b67ddc32f77bc3344b6b2b38dd9fe8595c726c33eabc03
Successfully built pycuda
Installing collected packages: appdirs, siphash24, pytools, pycuda
Successfully installed appdirs-1.4.4 pycuda-2024.1 pytools-2025.2.5 siphash24-1.8
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.3 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 130.4 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 5.9 MB/s eta 0:00:00

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [1]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_default_output/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/raw_user_output/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_default_output/results/10017_test/unet_eb5_dice_CDCRF" # @param {type:"string"}

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
IMAGE_DIR = "/content/image_dir"

In [7]:
!git clone https://github.com/phonchi/CryoParticleSegment.git

Cloning into 'CryoParticleSegment'...
remote: Enumerating objects: 270, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 270 (delta 141), reused 42 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (270/270), 32.01 MiB | 12.07 MiB/s, done.
Resolving deltas: 100% (141/141), done.

In [3]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

> #### ⚠ Notice
>
> You need to restart the kernel after the compilation step. Additionally, if your GPU architecture differs, you may need to modify the file at `/content/CryoParticleSegment/Modeling/CRF_main/setup.py`. (We attempt to detect the GPU configuration automatically, so this step is usually not necessary.)
> Furthermore, depending on the number of classes and other parameters, you may encounter an error that requires adjusting the file at `/content/CryoParticleSegment/Modeling/CRF_main/src/PermutohedralFiltering/source/gpu/LatticeFilter.cu`:
>
> 1. Note the `pd` and `vd` values from the error message.
> 2. Add an `else if (pd == ? && vd == ?)` block.
> 3. Within that block, insert the following line, replacing `pd` and `vd` with the specific values:
>
>    ```cpp
>    latticeFilterGPU<pd, vd>(output_tensor, input_tensor, positions, num_super_pixels, backward);
>    ```
> 4. Recompile using `setup.py`.

In [9]:
#%git clone https://github.com/netw0rkf10w/CRF.git
%cd CryoParticleSegment/Modeling/CRF_main
!python setup.py clean --all
!rm -rf build/
!python setup.py build_ext --inplace --force
!python setup.py install

/content/CryoParticleSegment/Modeling/CRF_main
running clean
'build/lib.linux-x86_64-cpython-312' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.12' does not exist -- can't clean it
running build_ext
W1014 17:51:26.158000 5448 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
W1014 17:51:26.226000 5448 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1014 17:51:26.226000 5448 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
building 'Permutohedral' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral -std=c++17
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp: In function ‘at::Tensor LatticeFilter_calculate(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool)’:
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:77:97: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
   77 |         at::Tensor positions = at::zeros({batch_size * num_super_pixels * pd}, input_tensor.type() );
      |                                                                                ~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/ATen/Tensor.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.12/dist-packages/torch/include/torch/extension.h:5,
                 from src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:25:
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
creating build/lib.linux-x86_64-cpython-312
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so
building 'Permutohedral_gpu' extension
creating build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.12/dist-packages/torch/include -I/usr/local/lib/python3.12/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/cuda/include -I/usr/include/python3.12 -c src/PermutohedralFiltering/source/gpu/LatticeFilter.cu -o build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -gencode=arch=compute_89,code=sm_89 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1018\" -DTORCH_EXTENSION_NAME=Permutohedral_gpu -std=c++17
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu: In function ‘at::Tensor LatticeFilter_calculate_gpu(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool, bool)’:
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:202:91: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  202 |     at::Tensor positions = at::zeros(
      |                                                                                           ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:208:67: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  208 |     CHECK_INPUT(image_tensor);
      |                                                                   ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:209:64: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  209 |     CHECK_INPUT(positions);
      |                                                                ^
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:213:44: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  213 |         auto ref_ptr = &(image_tensor.data<float>()[b * num_super_pixels * n_reference_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:214:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  214 |         auto pos_ptr = &(positions.data<float>()[b * num_super_pixels * pd]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:215:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  215 |         auto in_ptr = &(input_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:216:45: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  216 |         auto out_ptr = &(output_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.12/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -L/usr/local/lib/python3.12/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> src
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> src
running install
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating src/CRF.egg-info
writing src/CRF.egg-info/PKG-INFO
writing dependency_links to src/CRF.egg-info/dependency_links.txt
writing top-level names to src/CRF.egg-info/top_level.txt
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
W1014 17:53:08.926000 5933 torch/utils/cpp_extension.py:615] Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
reading manifest file 'src/CRF.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/CRF.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/sparsemax.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/__init__.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/convcrf.py -> build/lib.linux-x86_64-cpython-312/CRF
copying src/CRF/crfs_cpu.py -> build/lib.linux-x86_64-cpython-312/CRF
creating build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/PermutohedralFiltering.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/setup.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
copying src/PermutohedralFiltering/__init__.py -> build/lib.linux-x86_64-cpython-312/PermutohedralFiltering
running build_ext
W1014 17:53:08.977000 5933 torch/utils/cpp_extension.py:507] The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
W1014 17:53:08.977000 5933 torch/utils/cpp_extension.py:517] There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/CRF.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/sparsemax.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/__init__.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/convcrf.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/CRF/crfs_cpu.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-312/Permutohedral.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/PermutohedralFiltering.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/setup.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/PermutohedralFiltering/__init__.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-312/Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/CRF/CRF.py to CRF.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/sparsemax.py to sparsemax.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/__init__.py to __init__.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/convcrf.py to convcrf.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/crfs_cpu.py to crfs_cpu.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/PermutohedralFiltering.py to PermutohedralFiltering.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/setup.py to setup.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/__init__.py to __init__.cpython-312.pyc
creating stub loader for Permutohedral.cpython-312-x86_64-linux-gnu.so
creating stub loader for Permutohedral_gpu.cpython-312-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral.py to Permutohedral.cpython-312.pyc
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral_gpu.py to Permutohedral_gpu.cpython-312.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
CRF.__pycache__.crfs_cpu.cpython-312: module references __file__
__pycache__.Permutohedral.cpython-312: module references __file__
__pycache__.Permutohedral_gpu.cpython-312: module references __file__
creating dist
creating 'dist/CRF-0.0.1-py3.12-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CRF-0.0.1-py3.12-linux-x86_64.egg
creating /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Extracting CRF-0.0.1-py3.12-linux-x86_64.egg to /usr/local/lib/python3.12/dist-packages
Adding CRF 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg
Processing dependencies for CRF==0.0.1
Finished processing dependencies for CRF==0.0.1

In [4]:
%cd /content/

/content

### ✅ Packages Handling

In [5]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [6]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [7]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 8
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [8]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [9]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [10]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

config.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/122M [00:00<?, ?B/s]

In [11]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [12]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [13]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [14]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [15]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [16]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:27<00:00,  3.04it/s]

In [18]:
processed_micrographs.shape

(84, 3840, 3840)

In [19]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [20]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [21]:
del model
torch.cuda.empty_cache()

In [22]:
model = model_post

In [23]:
RESULT_DIR

'/content/drive/MyDrive/cryo_project/Test_on_10017/Test_0_9-8_9-30_EM_10017/TpzD_default_output/results/10017_test/unet_eb5_dice_CDCRF'

In [24]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [25]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [26]:
!cp {RESULT_DIR}/label_images.npy .

In [27]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [28]:
label_images.shape

(84, 3840, 3840)

In [29]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [30]:
!cp {RESULT_DIR}/best_config.txt .

In [31]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [32]:
radius = RADIUS

In [33]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [34]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

557 486
529 455
502 396
383 362
394 370
485 410
349 348
430 379
544 473
592 522
534 470
507 454
530 473
473 450
601 519
558 498
508 418
514 464
523 488
584 530
563 487
532 448
544 471
558 442
495 394
475 373
485 388
549 455
495 391
544 488
541 458
511 408
534 449
546 466
523 430
551 469
497 416
550 482
557 510
535 463
436 383
576 494
563 506
388 365
351 339
353 324
372 362
579 548
529 446
481 401
534 476
544 486
493 441
497 459
490 437
392 342
483 408
579 493
441 357
462 359
461 444
452 408
360 329
368 336
373 351
359 344
412 386
429 382
374 320
404 340
399 346
340 333
422 374
458 423
434 407
481 430
404 376
431 377
403 371
420 404
418 362
413 353
412 356
456 389

In [35]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [36]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/CRF-0.0.1-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [37]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [38]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,3526,3952,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,429,3951,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1510,3952,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,247,3948,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,3714,3944,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
35215,2363,186,00384@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35216,521,149,00385@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35217,315,147,00386@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35218,2857,154,00387@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
35219,3604,160,00388@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [39]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [40]:
cv_list

[[(3398, 3824),
  (301, 3823),
  (1382, 3824),
  (119, 3820),
  (3586, 3816),
  (626, 3814),
  (2412, 3818),
  (3040, 3809),
  (1810, 3792),
  (1152, 3812),
  (2827, 3788),
  (1782, 3766),
  (2700, 3791),
  (1564, 3780),
  (3694, 3768),
  (803, 3784),
  (1698, 3764),
  (1296, 3731),
  (977, 3734),
  (3449, 3689),
  (3409, 3687),
  (469, 3684),
  (33, 3677),
  (1788, 3683),
  (365, 3672),
  (1137, 3652),
  (1531, 3659),
  (2766, 3658),
  (1436, 3666),
  (3054, 3650),
  (1953, 3625),
  (1020, 3625),
  (816, 3651),
  (2330, 3627),
  (996, 3564),
  (3098, 3555),
  (756, 3563),
  (3229, 3551),
  (1127, 3539),
  (41, 3530),
  (907, 3501),
  (676, 3516),
  (1585, 3479),
  (2366, 3487),
  (2997, 3497),
  (2278, 3453),
  (135, 3484),
  (1567, 3463),
  (2777, 3459),
  (602, 3468),
  (3781, 3461),
  (1776, 3457),
  (3386, 3446),
  (763, 3429),
  (1478, 3435),
  (2261, 3412),
  (2528, 3448),
  (1000, 3414),
  (16, 3408),
  (2931, 3403),
  (2644, 3412),
  (516, 3410),
  (1930, 3398),
  (885, 3369),
  (672, 3348),
  (212, 3359),
  (3047, 3352),
  (1602, 3339),
  (2139, 3327),
  (1983, 3324),
  (3377, 3316),
  (329, 3323),
  (2662, 3303),
  (3820, 3285),
  (1071, 3301),
  (3655, 3289),
  (3578, 3298),
  (900, 3282),
  (1876, 3266),
  (3068, 3248),
  (3173, 3227),
  (2810, 3222),
  (327, 3212),
  (2600, 3208),
  (1221, 3193),
  (3431, 3179),
  (502, 3197),
  (3545, 3194),
  (2694, 3186),
  (3746, 3192),
  (2261, 3227),
  (211, 3169),
  (1072, 3167),
  (631, 3214),
  (2145, 3147),
  (3158, 3135),
  (792, 3121),
  (1598, 3122),
  (278, 3123),
  (1270, 3108),
  (3449, 3093),
  (608, 3087),
  (2305, 3083),
  (3638, 3054),
  (3366, 3033),
  (187, 3049),
  (1347, 3000),
  (3520, 3003),
  (3607, 2976),
  (368, 3008),
  (24, 2954),
  (3438, 2960),
  (3823, 2932),
  (2314, 2966),
  (3283, 2945),
  (2909, 2942),
  (2082, 2943),
  (2785, 2935),
  (2584, 2934),
  (270, 2925),
  (888, 2914),
  (3629, 2861),
  (1140, 2880),
  (191, 2870),
  (3030, 2875),
  (3362, 2861),
  (1231, 2857),
  (93, 2851),
  (3774, 2821),
  (2511, 2824),
  (2702, 2823),
  (3596, 2799),
  (2296, 2793),
  (870, 2776),
  (45, 2757),
  (3037, 2740),
  (2786, 2727),
  (1037, 2754),
  (3249, 2743),
  (2873, 2751),
  (3403, 2738),
  (2508, 2728),
  (2590, 2741),
  (3801, 2710),
  (3694, 2707),
  (1991, 2684),
  (479, 2672),
  (244, 2696),
  (2955, 2661),
  (3516, 2644),
  (689, 2657),
  (3416, 2652),
  (3590, 2650),
  (3239, 2648),
  (1740, 2646),
  (971, 2636),
  (2264, 2661),
  (2169, 2619),
  (597, 2611),
  (255, 2595),
  (29, 2600),
  (1639, 2602),
  (2679, 2598),
  (2524, 2573),
  (1330, 2564),
  (1549, 2591),
  (3238, 2549),
  (3347, 2553),
  (2336, 2546),
  (3802, 2531),
  (121, 2544),
  (1185, 2510),
  (3699, 2514),
  (2601, 2510),
  (2258, 2516),
  (398, 2485),
  (719, 2464),
  (1888, 2477),
  (1629, 2470),
  (3545, 2461),
  (1713, 2458),
  (2359, 2446),
  (1337, 2430),
  (3455, 2424),
  (3153, 2415),
  (123, 2401),
  (1560, 2403),
  (439, 2395),
  (3740, 2387),
  (596, 2401),
  (3040, 2380),
  (325, 2373),
  (3621, 2370),
  (1407, 2361),
  (2042, 2347),
  (1733, 2344),
  (1915, 2347),
  (194, 2333),
  (51, 2333),
  (3289, 2311),
  (1379, 2290),
  (2534, 2290),
  (1088, 2312),
  (3101, 2315),
  (1589, 2304),
  (2355, 2293),
  (361, 2278),
  (2779, 2219),
  (593, 2265),
  (506, 2234),
  (3764, 2274),
  (2734, 2221),
  (1996, 2238),
  (1607, 2217),
  (3015, 2230),
  (3249, 2191),
  (2463, 2194),
  (781, 2180),
  (441, 2183),
  (22, 2144),
  (1601, 2138),
  (3013, 2134),
  (642, 2125),
  (2343, 2110),
  (2542, 2104),
  (3447, 2126),
  (66, 2093),
  (1054, 2087),
  (2155, 2079),
  (20, 2045),
  (3200, 2050),
  (2012, 2042),
  (2671, 2088),
  (914, 2045),
  (2572, 2034),
  (691, 2036),
  (3779, 2036),
  (1331, 2012),
  (426, 2007),
  (827, 1971),
  (3443, 1964),
  (1724, 1973),
  (3342, 1938),
  (2276, 1921),
  (2597, 1927),
  (2737, 1950),
  (2258, 1949),
  (1105, 1922),
  (913, 1915),
  (2885, 1903),
  (1309, 1905),
  (3216, 1888),
  (3442, 1870),
  (3655, 1874),
  (669, 1861),
  (93, 1862),
  (1101, 1825),
  (1079, 1807),
  (2753, 1844),
  (2136, 1809),
  (3814, 1819),
  (3005, 1811),
  (1396, 1807),
  (1005, 1799),
  (2853, 1747),
  (2574, 1779),
  (2121, 1730),
  (3087, 1731),
  (47, 1712),
  (1110, 1727),
  (1583, 1730),
  (829, 1702),
  (2793, 1693),
  (3411, 1675),
  (2652, 1683),
  (1408, 1680),
  (3618, 1686),
  (1937, 1672),
  (3816, 1644),
  (3308, 1652),
  (2227, 1659),
  (1853, 1646),
  (569, 1646),
  (2713, 1627),
  (2988, 1623),
  (3181, 1595),
  (344, 1596),
  (3250, 1560),
  (1359, 1566),
  (3088, 1549),
  (157, 1558),
  (453, 1541),
  (1267, 1542),
  (1894, 1541),
  (2695, 1533),
  (967, 1520),
  (3152, 1494),
  (3615, 1503),
  (3708, 1501),
  (1460, 1481),
  (876, 1472),
  (205, 1473),
  (762, 1453),
  (3736, 1416),
  (287, 1391),
  (1190, 1408),
  (2215, 1399),
  (1400, 1387),
  (2697, 1389),
  (1096, 1383),
  (2320, 1386),
  (3664, 1383),
  (2087, 1367),
  (2449, 1316),
  (3293, 1352),
  (1261, 1317),
  (791, 1329),
  (1963, 1327),
  (1757, 1347),
  (3175, 1308),
  (1059, 1290),
  (2826, 1286),
  (1447, 1285),
  (3529, 1275),
  (2077, 1273),
  (416, 1266),
  (912, 1256),
  (2609, 1254),
  (3015, 1247),
  (58, 1255),
  (1352, 1240),
  (2282, 1221),
  (1825, 1204),
  (1240, 1213),
  (565, 1215),
  (2525, 1190),
  (1434, 1183),
  (2739, 1176),
  (2152, 1179),
  (3821, 1150),
  (2071, 1157),
  (1519, 1152),
  (3322, 1164),
  (3482, 1137),
  (616, 1117),
  (2999, 1109),
  (1802, 1085),
  (861, 1110),
  (1314, 1079),
  (3141, 1079),
  (2646, 1067),
  (511, 1107),
  (2432, 1063),
  (1062, 1071),
  (1935, 1038),
  (2819, 1022),
  (3221, 1016),
  (1347, 974),
  (1096, 982),
  (750, 987),
  (3063, 945),
  (2247, 975),
  (63, 973),
  (3400, 947),
  (476, 961),
  (1262, 944),
  (1850, 915),
  (1749, 917),
  (3146, 897),
  (3626, 869),
  (1579, 887),
  (1096, 884),
  (2410, 863),
  (3435, 848),
  (959, 853),
  (449, 831),
  (3066, 824),
  (3791, 817),
  (3675, 856),
  (1175, 813),
  (3363, 794),
  (350, 795),
  (2956, 793),
  (3569, 786),
  (2487, 781),
  (1281, 787),
  (919, 779),
  (1655, 765),
  (1956, 745),
  (3712, 728),
  (1427, 737),
  (1609, 694),
  (749, 680),
  (167, 675),
  (30, 711),
  (1140, 652),
  (851, 657),
  (1807, 643),
  (540, 645),
  (1032, 629),
  (1518, 618),
  (1328, 617),
  (2485, 608),
  (3151, 596),
  (3253, 570),
  (627, 585),
  (3806, 553),
  (2301, 561),
  (40, 559),
  (458, 561),
  (2616, 535),
  (1625, 575),
  (2385, 538),
  (1726, 517),
  (1450, 520),
  (1353, 519),
  (3623, 510),
  (3181, 508),
  (589, 499),
  (1135, 507),
  (1065, 476),
  (2837, 495),
  (3298, 468),
  (477, 479),
  (3692, 445),
  (3817, 454),
  (3445, 449),
  (2213, 454),
  (3073, 406),
  (1441, 424),
  (348, 418),
  (2296, 405),
  (1226, 368),
  (3239, 343),
  (1581, 355),
  (21, 355),
  (1409, 342),
  (952, 326),
  (1789, 294),
  (861, 316),
  (2538, 335),
  (179, 289),
  (1645, 292),
  (3534, 271),
  (1883, 272),
  (3184, 260),
  (333, 252),
  (2685, 237),
  (3771, 274),
  (724, 237),
  (1320, 241),
  (1724, 235),
  (2379, 204),
  (885, 211),
  (2469, 195),
  (1134, 211),
  (2290, 193),
  (2934, 174),
  (780, 166),
  (1448, 153),
  (2020, 138),
  (2565, 135),
  (166, 117),
  (2179, 111),
  (601, 109),
  (2713, 99),
  (1340, 89),
  (713, 98),
  (339, 108),
  (1800, 95),
  (1016, 66),
  (2821, 79),
  (2933, 60),
  (3218, 50),
  (3097, 26),
  (3002, 28),
  (1873, 34),
  (1194, 86),
  (124, 25),
  (3801, 42),
  (2076, 30),
  (2690, 19),
  (2309, 23),
  (3467, 63),
  (1401, 31),
  (220, 16)],
 [(3120, 3820),
  (278, 3817),
  (3383, 3823),
  (730, 3818),
  (3009, 3808),
  (1742, 3804),
  (1453, 3816),
  (3731, 3809),
  (958, 3800),
  (2589, 3803),
  (2166, 3795),
  (1185, 3792),
  (3608, 3786),
  (1892, 3784),
  (2783, 3786),
  (127, 3809),
  (2260, 3776),
  (1657, 3777),
  (505, 3768),
  (1316, 3757),
  (1579, 3751),
  (2674, 3722),
  (354, 3721),
  (2437, 3754),
  (1126, 3706),
  (40, 3705),
  (1391, 3709),
  (2956, 3691),
  (971, 3697),
  (2761, 3663),
  (1245, 3663),
  (3058, 3661),
  (3416, 3630),
  (103, 3634),
  (2382, 3649),
  (400, 3644),
  (2032, 3687),
  (564, 3638),
  (2585, 3619),
  (3333, 3605),
  (3205, 3601),
  (1072, 3593),
  (1481, 3589),
  (256, 3621),
  (1339, 3585),
  (2251, 3568),
  (1644, 3562),
  (2870, 3583),
  (871, 3551),
  (3042, 3538),
  (762, 3535),
  (2154, 3529),
  (1741, 3522),
  (160, 3482),
  (482, 3478),
  (2445, 3482),
  (2540, 3467),
  (1864, 3439),
  (3614, 3452),
  (2759, 3437),
  (2329, 3446),
  (296, 3439),
  (1520, 3432),
  (3302, 3419),
  (2949, 3421),
  (1768, 3418),
  (967, 3398),
  (3174, 3407),
  (1676, 3379),
  (185, 3362),
  (1122, 3347),
  (3691, 3346),
  (1228, 3345),
  (2656, 3325),
  (1560, 3330),
  (1320, 3348),
  (964, 3301),
  (1815, 3273),
  (3445, 3290),
  (159, 3269),
  (2573, 3274),
  (1664, 3262),
  (41, 3250),
  (3590, 3281),
  (1233, 3241),
  (3778, 3246),
  (3026, 3249),
  (799, 3217),
  (2168, 3233),
  (2868, 3222),
  (599, 3223),
  (2710, 3192),
  (2199, 3151),
  (1802, 3178),
  (943, 3172),
  (21, 3162),
  (3618, 3164),
  (1307, 3169),
  (1413, 3131),
  (2628, 3129),
  (1016, 3094),
  (3259, 3103),
  (3396, 3094),
  (1904, 3090),
  (1126, 3088),
  (573, 3085),
  (310, 3090),
  (2727, 3077),
  (77, 3078),
  (2120, 3065),
  (3156, 3033),
  (2879, 3073),
  (896, 3019),
  (1219, 3023),
  (233, 3020),
  (2261, 3019),
  (1453, 3017),
  (2008, 3000),
  (3096, 3016),
  (3726, 2972),
  (3014, 2972),
  (794, 2963),
  (3274, 2944),
  (43, 2940),
  (1563, 2923),
  (2078, 2930),
  (2428, 2934),
  (2307, 2903),
  (3819, 2876),
  (3580, 2882),
  (2177, 2870),
  (3175, 2854),
  (860, 2857),
  (240, 2845),
  (3657, 2837),
  (2104, 2812),
  (3398, 2817),
  (2347, 2812),
  (1584, 2804),
  (541, 2841),
  (56, 2797),
  (3815, 2770),
  (2485, 2769),
  (3227, 2760),
  (3031, 2720),
  (1955, 2747),
  (1360, 2705),
  (420, 2740),
  (3726, 2701),
  (2355, 2688),
  (1602, 2701),
  (512, 2705),
  (1702, 2690),
  (3280, 2676),
  (240, 2662),
  (46, 2671),
  (1782, 2642),
  (1243, 2641),
  (3665, 2633),
  (1584, 2603),
  (479, 2616),
  (1892, 2595),
  (3366, 2586),
  (2733, 2569),
  (2012, 2576),
  (3252, 2553),
  (1447, 2559),
  (3633, 2545),
  (1324, 2521),
  (2900, 2508),
  (151, 2501),
  (1071, 2487),
  (1424, 2465),
  (827, 2471),
  (2751, 2464),
  (3418, 2456),
  (3111, 2447),
  (47, 2441),
  (1982, 2428),
  (1310, 2424),
  (3034, 2407),
  (2065, 2370),
  (1631, 2370),
  (347, 2354),
  (1819, 2331),
  (908, 2362),
  (1733, 2338),
  (3505, 2320),
  (806, 2322),
  (2197, 2320),
  (1128, 2319),
  (261, 2307),
  (2493, 2289),
  (2379, 2281),
  (374, 2261),
  (1643, 2255),
  (706, 2260),
  (19, 2252),
  (1317, 2257),
  (2023, 2236),
  (1834, 2223),
  (3354, 2168),
  (2939, 2182),
  (157, 2191),
  (3173, 2140),
  (1453, 2166),
  (3331, 2135),
  (3432, 2161),
  (874, 2150),
  (366, 2139),
  (3221, 2171),
  (85, 2135),
  (2693, 2122),
  (2050, 2105),
  (2393, 2124),
  (3646, 2115),
  (964, 2108),
  (249, 2097),
  (709, 2071),
  (3160, 2062),
  (1644, 2054),
  (426, 2059),
  (2853, 2055),
  (3781, 2039),
  (43, 2029),
  (2081, 2017),
  (1527, 2010),
  (564, 2025),
  (183, 2029),
  (328, 1980),
  (2314, 1967),
  (3572, 1950),
  (1768, 1950),
  (3800, 1931),
  (1151, 1918),
  (2746, 1938),
  (3181, 1925),
  (1474, 1926),
  (3269, 1903),
  (1898, 1898),
  (1649, 1876),
  (819, 1880),
  (2841, 1839),
  (1981, 1819),
  (2602, 1847),
  (568, 1833),
  (1622, 1819),
  (1815, 1811),
  (947, 1853),
  (2156, 1806),
  (2735, 1801),
  (133, 1770),
  (419, 1789),
  (3421, 1778),
  (3013, 1784),
  (3318, 1760),
  (2286, 1761),
  (845, 1746),
  (2837, 1740),
  (2678, 1707),
  (3170, 1717),
  (1955, 1715),
  (596, 1728),
  (2168, 1695),
  (1767, 1695),
  (1922, 1641),
  (3463, 1660),
  (2324, 1652),
  (82, 1655),
  (1566, 1623),
  (1020, 1633),
  (1410, 1609),
  (3204, 1594),
  (2270, 1576),
  (516, 1556),
  (1467, 1554),
  (72, 1545),
  (2110, 1526),
  (2511, 1543),
  (1194, 1532),
  (2770, 1509),
  (151, 1501),
  (1118, 1494),
  (2890, 1487),
  (421, 1479),
  (1724, 1472),
  (1313, 1476),
  (2199, 1449),
  (3008, 1439),
  (841, 1422),
  (239, 1398),
  (2076, 1383),
  (3289, 1357),
  (2478, 1355),
  (1076, 1383),
  (109, 1375),
  (1554, 1375),
  (755, 1367),
  (2828, 1379),
  (17, 1337),
  (1649, 1359),
  (58, 1288),
  (2232, 1319),
  (3360, 1292),
  (921, 1288),
  (1787, 1324),
  (379, 1286),
  (1188, 1278),
  (2950, 1256),
  (2108, 1260),
  (2392, 1246),
  (1510, 1232),
  (2294, 1227),
  (2555, 1254),
  (3751, 1215),
  (2723, 1202),
  (1358, 1205),
  (1884, 1200),
  (115, 1222),
  (1061, 1204),
  (244, 1206),
  (1471, 1158),
  (2717, 1125),
  (2305, 1140),
  (667, 1137),
  (2219, 1118),
  (2778, 1107),
  (2846, 1159),
  (1654, 1114),
  (809, 1121),
  (3089, 1110),
  (3767, 1100),
  (2698, 1082),
  (1167, 1068),
  (47, 1058),
  (3607, 1049),
  (367, 1052),
  (2583, 1042),
  (1386, 1017),
  (1924, 1045),
  (3731, 1004),
  (733, 975),
  (2610, 939),
  (625, 956),
  (192, 947),
  (2354, 934),
  (3583, 952),
  (1374, 910),
  (3756, 925),
  (3127, 910),
  (2084, 891),
  (1813, 905),
  (2904, 888),
  (1112, 872),
  (3040, 848),
  (1589, 856),
  (2796, 830),
  (3332, 813),
  (678, 829),
  (945, 768),
  (30, 773),
  (3746, 772),
  (1638, 762),
  (804, 758),
  (1795, 761),
  (2430, 757),
  (3412, 753),
  (1391, 749),
  (3203, 751),
  (565, 728),
  (2271, 722),
  (1302, 714),
  (2129, 715),
  (3588, 702),
  (1731, 679),
  (686, 690),
  (55, 664),
  (1446, 652),
  (2389, 647),
  (1199, 658),
  (903, 664),
  (2158, 596),
  (3510, 628),
  (2980, 568),
  (3820, 554),
  (62, 543),
  (2275, 534),
  (2389, 542),
  (568, 538),
  (2028, 529),
  (769, 532),
  (3365, 520),
  (3492, 497),
  (2136, 497),
  (1761, 528),
  (1286, 513),
  (3258, 507),
  (3505, 466),
  (137, 491),
  (1169, 475),
  (375, 468),
  (64, 449),
  (2455, 442),
  (3384, 431),
  (1325, 418),
  (3079, 411),
  (900, 408),
  (1858, 394),
  (2025, 375),
  (2638, 374),
  (480, 372),
  (3457, 369),
  (3810, 358),
  (1117, 348),
  (3665, 316),
  (346, 301),
  (547, 309),
  (1498, 312),
  (1634, 303),
  (3057, 295),
  (1771, 276),
  (915, 277),
  (55, 252),
  (3506, 246),
  (431, 215),
  (3739, 224),
  (566, 214),
  (1439, 196),
  (651, 188),
  (53, 178),
  (3374, 164),
  (3174, 168),
  (201, 214),
  (2107, 161),
  (1341, 149),
  (876, 153),
  (1532, 139),
  (1184, 127),
  (692, 114),
  (514, 81),
  (3280, 69),
  (3796, 37),
  (3685, 46),
  (1989, 41),
  (1750, 60),
  (2566, 52),
  (2200, 56),
  (2086, 47),
  (263, 56),
  (591, 23),
  (2721, 33),
  (3569, 61),
  (435, 19),
  (2993, 17),
  (1359, 19)],
 [(1172, 3822),
  (2897, 3819),
  (1299, 3816),
  (1711, 3819),
  (2579, 3818),
  (1226, 3804),
  (3429, 3816),
  (2350, 3801),
  (493, 3800),
  (3287, 3800),
  (3559, 3794),
  (3699, 3783),
  (1514, 3777),
  (2724, 3770),
  (807, 3743),
  (1126, 3732),
  (19, 3725),
  (2308, 3724),
  (2922, 3728),
  (1345, 3722),
  (1439, 3689),
  (704, 3692),
  (3737, 3690),
  (3307, 3676),
  (3443, 3637),
  (1233, 3664),
  (2413, 3665),
  (2260, 3649),
  (3558, 3632),
  (1530, 3661),
  (1961, 3629),
  (1805, 3648),
  (2348, 3618),
  (53, 3619),
  (1384, 3616),
  (161, 3595),
  (376, 3579),
  (3812, 3567),
  (3378, 3555),
  (2114, 3547),
  (1252, 3535),
  (225, 3524),
  (1687, 3534),
  (2516, 3513),
  (2626, 3509),
  (2447, 3506),
  (3219, 3457),
  (2925, 3464),
  (2529, 3441),
  (3611, 3422),
  (1694, 3415),
  (2326, 3425),
  (441, 3364),
  (2661, 3397),
  (332, 3369),
  (3221, 3339),
  (2097, 3400),
  (907, 3369),
  (3126, 3358),
  (600, 3332),
  (1530, 3333),
  (2191, 3317),
  (3620, 3302),
  (232, 3297),
  (447, 3308),
  (3818, 3260),
  (2547, 3291),
  (1698, 3252),
  (530, 3250),
  (2119, 3241),
  (3533, 3253),
  (1927, 3243),
  (1328, 3233),
  (953, 3224),
  (2005, 3199),
  (3621, 3190),
  (1162, 3185),
  (3757, 3155),
  (1789, 3156),
  (398, 3137),
  (3467, 3129),
  (514, 3137),
  (2630, 3126),
  (2130, 3120),
  (2477, 3091),
  (1900, 3090),
  (3784, 3073),
  (1231, 3069),
  (2380, 3073),
  (587, 3056),
  (2296, 3058),
  (1028, 3042),
  (3472, 3017),
  (2629, 3007),
  (859, 3029),
  (2780, 2998),
  (389, 3003),
  (1256, 2979),
  (1824, 2973),
  (1947, 3000),
  (2174, 2958),
  (335, 2946),
  (2912, 2940),
  (1009, 2942),
  (1438, 2939),
  (908, 2904),
  (2326, 2907),
  (508, 2894),
  (2961, 2857),
  (1569, 2855),
  (2177, 2834),
  (1736, 2819),
  (1144, 2817),
  (3435, 2811),
  (186, 2781),
  (2889, 2786),
  (2087, 2775),
  (2618, 2779),
  (458, 2758),
  (3670, 2760),
  (994, 2744),
  (3292, 2730),
  (369, 2736),
  (3776, 2719),
  (2693, 2713),
  (2542, 2737),
  (646, 2710),
  (1229, 2714),
  (3556, 2713),
  (1282, 2728),
  (1952, 2693),
  (1742, 2684),
  (20, 2676),
  (540, 2669),
  (3064, 2661),
  (3212, 2648),
  (617, 2635),
  (374, 2630),
  (2855, 2626),
  (2200, 2616),
  (1457, 2608),
  (3133, 2607),
  (2487, 2588),
  (3339, 2568),
  (2084, 2584),
  (1002, 2612),
  (76, 2579),
  (1788, 2580),
  (1870, 2559),
  (897, 2515),
  (3109, 2528),
  (1157, 2524),
  (212, 2493),
  (400, 2490),
  (661, 2494),
  (1731, 2478),
  (1604, 2508),
  (92, 2438),
  (1459, 2470),
  (3599, 2369),
  (3707, 2382),
  (1691, 2358),
  (1943, 2359),
  (2083, 2354),
  (335, 2349),
  (1048, 2325),
  (3028, 2336),
  (3245, 2338),
  (457, 2322),
  (3414, 2325),
  (1632, 2290),
  (1372, 2305),
  (1247, 2349),
  (2925, 2297),
  (2769, 2276),
  (1160, 2268),
  (173, 2266),
  (2206, 2253),
  (2053, 2253),
  (3478, 2249),
  (759, 2243),
  (1823, 2238),
  (336, 2211),
  (952, 2171),
  (2902, 2169),
  (1204, 2160),
  (1462, 2125),
  (3024, 2134),
  (175, 2112),
  (474, 2100),
  (1654, 2115),
  (821, 2128),
  (2809, 2070),
  (1201, 2065),
  (1085, 2018),
  (3088, 2004),
  (1675, 2007),
  (1530, 1993),
  (703, 1998),
  (3632, 1990),
  (2285, 1994),
  (971, 1967),
  (3045, 1922),
  (97, 1925),
  (2176, 1877),
  (187, 1873),
  (1327, 1842),
  (1183, 1906),
  (912, 1833),
  (517, 1883),
  (3262, 1837),
  (1098, 1852),
  (2041, 1815),
  (2307, 1800),
  (852, 1792),
  (2129, 1790),
  (278, 1788),
  (2511, 1792),
  (980, 1781),
  (413, 1758),
  (2223, 1755),
  (1144, 1764),
  (123, 1752),
  (17, 1715),
  (1227, 1709),
  (3508, 1701),
  (887, 1689),
  (603, 1696),
  (2891, 1692),
  (1833, 1674),
  (495, 1660),
  (3064, 1674),
  (18, 1635),
  (1085, 1645),
  (1586, 1622),
  (3654, 1654),
  (2577, 1613),
  (3265, 1609),
  (3168, 1587),
  (1741, 1574),
  (3540, 1577),
  (814, 1582),
  (2821, 1571),
  (1314, 1593),
  (3668, 1542),
  (933, 1528),
  (97, 1524),
  (633, 1510),
  (3344, 1515),
  (1653, 1498),
  (1440, 1537),
  (2796, 1458),
  (1196, 1396),
  (666, 1397),
  (1686, 1393),
  (1772, 1377),
  (1920, 1379),
  (875, 1373),
  (1362, 1395),
  (749, 1365),
  (2579, 1355),
  (241, 1355),
  (3532, 1387),
  (2279, 1309),
  (2471, 1330),
  (1544, 1305),
  (379, 1296),
  (3742, 1301),
  (1726, 1283),
  (3820, 1258),
  (3328, 1289),
  (65, 1257),
  (1111, 1259),
  (1610, 1230),
  (3063, 1236),
  (1236, 1189),
  (299, 1195),
  (2045, 1213),
  (2253, 1178),
  (2897, 1208),
  (579, 1160),
  (1428, 1131),
  (3757, 1132),
  (3074, 1138),
  (2763, 1121),
  (3222, 1128),
  (2601, 1114),
  (2263, 1094),
  (1278, 1096),
  (3697, 1071),
  (2059, 1072),
  (3355, 1052),
  (1858, 1041),
  (1157, 1034),
  (2949, 1037),
  (19, 1015),
  (674, 1030),
  (263, 1018),
  (926, 1006),
  (787, 993),
  (3483, 996),
  (1684, 1002),
  (2435, 942),
  (576, 942),
  (3760, 953),
  (1907, 946),
  (1595, 931),
  (84, 938),
  (2635, 954),
  (1026, 886),
  (3383, 878),
  (3228, 866),
  (473, 881),
  (2619, 846),
  (2530, 850),
  (2417, 851),
  (3148, 819),
  (168, 800),
  (1226, 782),
  (1818, 766),
  (1050, 771),
  (3785, 756),
  (2390, 742),
  (2151, 737),
  (851, 741),
  (139, 716),
  (944, 717),
  (3389, 706),
  (3250, 697),
  (2864, 686),
  (2666, 693),
  (2545, 681),
  (2273, 669),
  (2016, 676),
  (1153, 646),
  (3662, 633),
  (2423, 630),
  (3297, 600),
  (545, 614),
  (2542, 594),
  (960, 611),
  (2748, 584),
  (2634, 582),
  (54, 603),
  (321, 540),
  (3737, 536),
  (3547, 534),
  (3460, 518),
  (214, 509),
  (2951, 459),
  (3615, 502),
  (875, 453),
  (3565, 438),
  (2751, 425),

In [41]:
tp_config

(0.25, 0.4)

In [42]:
import trackpy as tp

In [43]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [45]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

603
583
625
365
387
551
313
450
593
620
569
485
561
464
645
571
556
540
497
588
590
638
606
683
593
599
604
636
617
559
594
634
591
597
593
613
560
603
543
610
474
626
572
367
332
364
344
546
596
559
566
560
505
503
517
428
569
643
627
605
431
471
365
365
355
338
406
456
423
460
442
307
460
435
409
491
395
466
406
398
449
456
439
466

In [46]:
tp_list

[array([[ 709.31572494,   93.72562263],
        [1013.82875074,   64.7335556 ],
        [3214.5845698 ,   49.63688258],
        ...,
        [2031.52043885, 3749.27395368],
        [3203.55834945, 3743.02543162],
        [1907.02775758, 3737.36421844]]),
 array([[2400.27177727,   93.71179578],
        [ 225.87005906,   79.75505205],
        [3679.48940228,   47.51306835],
        ...,
        [3600.86630873, 3784.80287368],
        [ 477.93980477, 3763.9070344 ],
        [2778.24170153, 3782.48211276]]),
 array([[ 282.2452636 ,   62.54877444],
        [3728.23503974,   43.84864562],
        [2401.91981362,  110.78713411],
        ...,
        [3550.71852693, 3793.12370214],
        [1962.1627589 , 3765.77410915],
        [3690.26562906, 3780.16588313]]),
 array([[2920.4917967 ,   63.69040074],
        [ 875.39158118,   51.30094259],
        [2249.26448011,   51.22002791],
        [3562.99443181,   59.75241158],
        [1259.49304925,   63.04016766],
        [1422.50932411,   87.44190364],
        [3012.45718874,  151.88837956],
        [1745.05733042,   95.27002188],
        [3446.71403941,  176.53686371],
        [3228.34373552,  196.219759  ],
        [ 166.49142244,  158.55091909],
        [1067.3919433 ,  139.87459903],
        [2673.70553005,  178.45377049],
        [1478.20790978,  184.92347232],
        [2404.13975133,  231.82898277],
        [ 620.42056915,  210.63173406],
        [3304.33522717,  199.22554381],
        [1777.91095905,  195.36392035],
        [2714.09455427,  283.05634214],
        [ 383.72061754,  242.47265554],
        [1246.799044  ,  314.24950045],
        [1578.86318159,  253.08129065],
        [ 735.53139814,  327.18730654],
        [3589.00812687,  305.71461259],
        [ 820.56234204,  280.38930076],
        [2360.50590408,  294.42897561],
        [2835.23780388,  310.46067874],
        [1369.1042471 ,  369.81156622],
        [1496.53308545,  366.22549475],
        [1752.48426131,  346.27031156],
        [1848.7064521 ,  366.86857951],
        [3331.33080916,  329.86434643],
        [1073.18010078,  363.80046304],
        [1954.6147057 ,  397.79054012],
        [2528.93660019,  358.16509022],
        [3766.31324594,  362.70118251],
        [ 956.96740396,  429.58851975],
        [2274.59845944,  395.89496575],
        [2831.90621353,  443.26119818],
        [1194.97968275,  423.51680192],
        [2057.36760609,  503.87344886],
        [ 752.10162831,  455.11335914],
        [1866.96104361,  501.68752572],
        [2152.00053675,  487.77166474],
        [2509.78451506,  504.26041115],
        [2631.23346918,  470.919654  ],
        [ 307.41375692,  447.20273245],
        [2389.27183143,  442.80289339],
        [1576.32107613,  534.0595312 ],
        [2225.14229532,  558.67729051],
        [ 943.13077066,  503.40248839],
        [2924.12473768,  543.70635652],
        [3279.09515511,  570.36466442],
        [ 778.25280837,  592.83275017],
        [3185.72947844,  567.4546265 ],
        [ 130.92831325,  617.42266566],
        [1526.94926595,  577.39874838],
        [3730.89402206,  635.74973117],
        [ 619.10782749,  580.33571724],
        [1364.63815666,  590.30383064],
        [2625.17764067,  613.80054617],
        [3201.9355227 ,  691.75870163],
        [3322.66223938,  656.84138996],
        [1264.76288574,  673.33594662],
        [2498.07815538,  624.07815538],
        [1981.12826246,  641.2952727 ],
        [ 898.52246384,  650.18545365],
        [  86.43795876,  655.31488873],
        [ 751.87712734,  682.55151881],
        [ 302.67037563,  668.09850799],
        [ 406.2023836 ,  662.56643719],
        [1045.23034578,  679.31494543],
        [3246.75191303,  735.11435786],
        [1803.84978026,  704.55890826],
        [3623.53861664,  728.54741337],
        [3405.98669217,  767.32679032],
        [1555.9986811 ,  722.50839882],
        [1320.58759191,  722.85218032],
        [2507.40392353,  800.45139367],
        [2301.48234145,  796.53599523],
        [2749.78156215,  747.28545105],
        [2689.02691046,  773.91149647],
        [2392.11472485,  778.04716815],
        [1589.22713663,  845.05135494],
        [2200.93683982,  853.87628418],
        [1282.71001683,  821.1159894 ],
        [1734.63262783,  840.77467452],
        [2834.79392499,  873.40345077],
        [3456.64991392,  862.21517272],
        [1974.44587714,  851.01448125],
        [ 121.02854295,  887.04115629],
        [2524.072649  ,  904.2199458 ],
        [1574.51539278,  993.26291578],
        [ 771.38672642,  947.84242614],
        [1807.17583844, 1008.22142084],
        [ 283.17847378,  959.73442951],
        [2226.82182718, 1000.72208114],
        [ 499.51480354,  978.91806855],
        [2365.70206448, 1000.09254808],
        [1995.54155459,  990.24981033],
        [ 930.31211319,  978.2444728 ],
        [3699.41989673,  973.67355101],
        [2647.80257716,  988.01638562],
        [2833.00400327,  989.6573544 ],
        [ 158.97863981, 1029.98056865],
        [3319.16262846, 1007.07908232],
        [3619.04490071, 1045.13631774],
        [2232.49093972, 1093.31733574],
        [1700.94647302, 1095.70817142],
        [1230.17799043, 1093.40852545],
        [1111.51706932, 1148.10345545],
        [3398.80853002, 1137.14931677],
        [ 453.44389344, 1114.44576173],
        [  61.14091052, 1162.13310903],
        [ 892.97052542, 1149.98348284],
        [1875.12177569, 1109.49001662],
        [3749.70438704, 1165.59879756],
        [1547.40578375, 1161.56212136],
        [3035.51341055, 1152.86404118],
        [1422.04897571, 1216.87054721],
        [1226.44246772, 1208.5220742 ],
        [1055.66800373, 1236.93120271],
        [3582.78392889, 1266.38866397],
        [2061.64733903, 1265.7205979 ],
        [2622.76094442, 1284.42072471],
        [2939.67362954, 1244.0673368 ],
        [3486.26875069, 1231.34582762],
        [  94.86818362, 1251.60389067],
        [1333.53905075, 1262.98782656],
        [2443.3348194 , 1288.83511156],
        [1987.27134625, 1302.80453491],
        [ 883.24030297, 1316.82190895],
        [2328.70808772, 1302.71524012],
        [ 416.17669893, 1327.31338958],
        [2204.92908462, 1360.01921444],
        [3346.16015303, 1319.2260143 ],
        [1218.61494387, 1368.5094752 ],
        [ 983.40036938, 1371.24054997],
        [2557.24967514, 1370.1456593 ],
        [3028.56106052, 1382.98607392],
        [ 864.38783233, 1394.11643703],
        [1455.5327956 , 1372.37198344],
        [ 191.62261122, 1386.98922183],
        [2316.59000963, 1442.24858274],
        [2708.48075779, 1417.1512483 ],
        [1118.79542534, 1400.89000257],
        [3226.80996819, 1410.2021866 ],
        [3137.90062067, 1483.37156546],
        [2215.2992968 , 1438.85499105],
        [2920.77613626, 1490.70452768],
        [3554.07197987, 1471.43926174],
        [3634.50443496, 1460.35821117],
        [1296.2614942 , 1476.85970695],
        [ 113.56339777, 1468.7301531 ],
        [ 355.27140919, 1512.44444444],
        [ 879.76175503, 1511.4337956 ],
        [2362.30727544, 1524.87549113],
        [1091.58608311, 1582.48224908],
        [ 285.59510785, 1563.70139568],
        [1470.41118574, 1597.67051071],
        [2965.60579936, 1551.80406692],
        [ 575.58104908, 1584.90874993],
        [2464.836     , 1524.76072   ],
        [1773.90866933, 1545.24195547],
        [3498.4232776 , 1620.76969951],
        [ 666.13964602, 1620.63141593],
        [1668.21476034, 1591.67856826],
        [3314.23872252, 1606.75644428],
        [1279.44291805, 1596.3490872 ],
        [2085.25363143, 1622.25523797],
        [2930.42034579, 1654.66504521],
        [3389.87032467, 1700.30947986],
        [ 287.06441481, 1664.98994568],
        [2701.53926059, 1654.04294127],
        [3537.05548983, 1666.08048373],
        [3703.08067733, 1715.8672495 ],
        [ 148.53523496, 1669.46338852],
        [1428.31596511, 1695.10367842],
        [1781.84409689, 1715.31019684],
        [1716.81930976, 1713.01410121],
        [ 737.64799564, 1685.06804836],
        [1135.75814086, 1711.22848007],
        [2224.17400927, 1760.98900339],
        [1304.80120168, 1739.22643701],
        [ 519.56503013, 1805.9533184 ],
        [2773.5312594 , 1821.96080791],
        [1901.03000144, 1829.53600973],
        [2476.75120143, 1783.30337773],
        [3388.41443794, 1811.21399992],
        [ 296.72216355, 1799.11700362],
        [1159.8494496 , 1833.8144922 ],
        [2120.39332613, 1807.58469625],
        [2286.33413113, 1836.95104439],
        [3739.35903614, 1875.97771084],
        [ 442.09806169, 1842.81347902],
        [1479.40474541, 1848.2042778 ],
        [ 622.0075657 , 1846.16783189],
        [2173.72818159, 1946.31246415],
        [ 133.06088827, 1940.89453445],
        [2759.28020182, 1918.64762532],
        [3492.88088141, 1902.32487691],
        [3593.19695166, 1904.55841867],
        [2014.87858007, 1914.11528418],
        [2380.00432976, 1939.884144  ],
        [ 392.6923346 , 1977.34762194],
        [2999.13768977, 2016.65584158],
        [ 704.93953675, 1984.81253298],
        [1327.59654773, 2018.55048674],
        [ 908.80305944, 2070.90646498],
        [3290.11133658, 2072.95311814],
        [2743.81149584, 2027.58927812],
        [2140.67640183, 2041.71031679],
        [2555.74843828, 2055.0755375 ],
        [1585.89537558, 2098.10601581],
        [1870.59586178, 2115.22865245],
        [3456.82438377, 2128.8134285 ],
        [1260.71736229, 2139.49851579],
        [1959.11646323, 2156.17552569],
        [2419.67972196, 2120.04023526],
        [1035.20410399, 2106.69943041],
        [ 188.6145523 , 2124.08041964],
        [3172.490334  , 2150.59393939],
        [3719.8482224 , 2155.49375568],
        [2565.26474362, 2157.78727807],
        [ 751.27683034, 2235.97974988],
        [3519.86423059, 2179.05596223],
        [1611.77974911, 2214.03346374],
        [1207.1448512 , 2225.3752085 ],
        [3623.38277935, 2206.32485536],
        [1028.11678242, 2282.12898247],
        [ 860.58071691, 2213.95689104],
        [2702.66407939, 2271.60836059],
        [ 437.17722185, 2242.83637593],
        [3015.98070622, 2286.55540857],
        [2235.07741547, 2270.57255817],
        [1331.72099878, 2264.59194071],
        [2375.99502978, 2286.72959424],
        [2470.28844141, 2317.19135932],
        [3786.49343469, 2349.03895992],
        [2067.82097359, 2313.81835843],
        [ 704.30404092, 2352.43302302],
        [3434.76993824, 2394.27419864],
        [1147.14494257, 2402.32359526],
        [2931.40684076, 2367.93631849],
        [1778.53291916, 2373.02486659],
        [3699.64203285, 2410.03550821],
        [ 165.95319698, 2420.01260365],
        [2617.02751374, 2440.2370084 ],
        [1362.55716108, 2425.47116721],
        [ 823.15003797, 2452.58656036],
        [3026.70734083, 2465.17231914],
        [ 468.42534462, 2512.39612434],
        [ 222.35310867, 2566.46505442],
        [ 362.74700463, 2561.73588823],
        [1259.81049222, 2499.44006327],
        [1719.8566796 , 2561.80881329],
        [1127.82871769, 2543.09886261],
        [2883.99384899, 2533.12901738],
        [2340.51925038, 2543.33334569],
        [ 578.85789307, 2562.21823187],
        [2046.44161572, 2574.42536563],
        [2573.92855409, 2557.22194352],
        [ 468.62801731, 2618.5018312 ],
        [2442.17641451, 2626.11843212],
        [ 688.6483324 , 2595.14931992],
        [1462.87327541, 2638.01861491],
        [3241.07958077, 2690.7486086 ],
        [1717.61124255, 2631.29058081],
        [ 341.64654235, 2638.28842269],
        [1861.98567909, 2659.33353865],
        [ 209.00295921, 2661.88291804],
        [2522.3783531 , 2697.21311057],
        [ 509.1601461 , 2738.11561424],
        [1036.39405864, 2717.82896414],
        [1485.84192191, 2756.79751908],
        [1291.42525085, 2708.36418104],
        [2992.82175008, 2733.81622562],
        [2452.27300939, 2775.49147106],
        [1810.76952748, 2752.33926536],
        [1996.47401354, 2738.92755897],
        [3459.40512493, 2757.77201245],
        [ 425.10309654, 2802.33406193],
        [2612.80967561, 2806.6668289 ],
        [3310.6403348 , 2793.73887179],
        [1615.08930723, 2776.80112952],
        [ 215.62876033, 2783.69371901],
        [1734.80511691, 2884.0235228 ],
        [3693.4541317 , 2898.39297397],
        [3461.05642151, 2877.50241493],
        [ 577.6608208 , 2887.52309176],
        [1499.70496597, 2880.46197448],
        [2642.65527608, 2891.47669615],
        [2585.17014241, 2885.17816675],
        [ 942.27096907, 2867.79206211],
        [1655.63735453, 2962.00434355],
        [2105.09957082, 2925.80264664],
        [3074.10761598, 2977.58658162],
        [1743.87585057, 3000.2048737 ],
        [1355.19074144, 2999.70601914],
        [3589.79796336, 3042.2952388 ],
        [ 309.87113211, 3062.37542358],
        [ 150.1885198 , 3122.72324358],
        [1471.25917447, 3067.06242004],
        [3206.27086658, 3074.08206765],
        [ 789.66685136, 3137.53608734],
        [2785.23404678, 3062.56515432],
        [ 999.89387699, 3081.38083471],
        [2633.2116764 , 3091.12700584],
        [3419.48625105, 3112.41876862],
        [3693.63323246, 3117.92638239],
        [2439.01293128, 3091.00894084],
        [1132.88668555, 3172.15781778],
        [ 680.75852973, 3157.85943384],
        [1378.77403281, 3208.31994579],
        [3131.45868582, 3244.62630017],
        [1237.34638398, 3185.25604399],
        [1883.43667385, 3230.935877  ],
        [3238.8124964 , 3200.80215323],
        [ 856.18958658, 3214.7247881 ],
        [2977.24334065, 3247.93042933],
        [1982.70410195, 3222.70640294],
        [2797.73288219, 3251.67408863],
        [ 303.19159367, 3321.27224896],
        [ 442.03121075, 3292.79419216],
        [2546.21970709, 3313.85294928],
        [ 531.23655648, 3366.66020859],
        [3164.9868192 , 3336.64779905],
        [2155.68445454, 3344.1124042 ],
        [1616.04915774, 3322.92484891],
        [2638.37294344, 3417.51979488],
        [1086.46458025, 3428.69274688],
        [2831.67624021, 3401.2651455 ],
        [2462.54218582, 3437.50765331],
        [1256.34236923, 3461.39418554],
        [1619.25109334, 3531.40538198],
        [1851.60172718, 3493.35387635],
        [ 678.20439494, 3542.41533715],
        [ 820.1377294 , 3547.59898066],
        [2954.66373954, 3535.35413054],
        [ 333.75454869, 3518.18250398],
        [ 156.79946464, 3617.52905849],
        [1119.24381387, 3579.92959619],
        [2245.99315685, 3544.58209977],
        [1745.71003099, 3587.98527485],
        [1499.90844434, 3631.8935911 ],
        [2550.59054741, 3596.17390471],
        [2658.41395287, 3598.96793215],
        [ 917.35413994, 3613.06214642],
        [1186.60946204, 3604.01945622],
        [2092.53292486, 3670.15008054],
        [1316.09557252, 3601.05389313],
        [1882.35408954, 3616.21327145],
        [ 560.64674381, 3617.28015579],
        [2249.20919918, 3711.92370983],
        [2989.29880916, 3675.43272934],
        [2601.63305819, 3733.88220996],
        [1120.47182   , 3723.25390648],
        [2813.21587115, 3729.47279513],
        [ 720.14020238, 3679.18769772],
        [ 355.93947202, 3759.8297037 ],
        [2487.49810845, 3718.03033688],
        [ 144.80107081, 3744.95920368],
        [1427.46531434, 3739.2032363 ],
        [1315.39452979, 3770.20382166],
        [2379.09909204, 3787.80900124]]),
 array([[3016.55976768,   55.62914999],
        [3387.02664311,   60.75956957],
        [2015.42378362,   92.81170072],
        [2147.56417431,   71.84142727],
        [ 242.81142774,   67.7597412 ],
        [ 894.40433387,  152.43772071],
        [2424.7083553 ,   73.85763999],
        [ 687.67543446,   93.64764358],
        [1608.04450168,  169.99354008],
        [ 119.52516649,  142.71311978],
        [1302.17634702,  127.12239775],
        [1071.10002641,  127.04357586],
        [2914.17727007,  213.82637718],
        [3053.15126082,  144.57865487],
        [3288.97250718,  150.92016596],
        [2215.71949358,  207.53784682],
        [1963.85251669,  155.28312004],
        [2059.93534218,  235.64165166],
        [ 373.38871901,  195.10400472],
        [1662.49600881,  221.0083756 ],
        [ 577.57740302,  176.85532034],
        [ 688.75496714,  268.03535637],
        [1835.08829744,  224.96383232],
        [3533.47214142,  248.13705527],
        [2762.68640589,  281.46629463],
        [2391.21155742,  258.82303597],
        [3675.03220887,  257.86557246],
        [1190.69259326,  301.37970806],
        [3035.77194583,  277.18886919],
        [ 804.00212875,  287.73209288],
        [1625.10025686,  287.98179722],
        [ 628.81876186,  322.2814771 ],
        [1431.01537862,  355.88184284],
        [ 399.16527175,  420.6557404 ],
        [1751.9082372 ,  354.22617009],
        [ 922.36154687,  358.84132971],
        [2115.40612707,  390.16179858],
        [2331.6876167 ,  385.32429883],
        [3383.52103896,  399.66070501],
        [1376.89242311,  403.45348837],
        [1586.6119676 ,  471.6115321 ],
        [2792.37591961,  433.48110998],
        [ 169.33299484,  485.72006431],
        [ 234.57954735,  476.88402009],
        [2468.60255628,  458.582205  ],
        [1305.0196974 ,  533.47104387],
        [2085.10637007,  509.26579036],
        [1840.56825337,  513.20470321],
        [1461.55348446,  509.71122245],
        [1132.70905303,  527.88759656],
        [ 705.12375578,  559.83086449],
        [1954.04221131,  524.57642033],
        [2256.86217698,  532.75097886],
        [3670.19099242,  542.28864798],
        [ 419.89469368,  573.85183747],
        [3181.19882482,  588.96768256],
        [2825.15987987,  577.85125632],
        [3254.55968947,  602.69455341],
        [3769.53598691,  584.18197928],
        [3373.97162207,  572.16998903],
        [2626.02512934,  574.31328333],
        [ 152.22316697,  589.64416749],
        [3536.90431745,  615.40418099],
        [ 585.07754558,  618.24591803],
        [1013.92477329,  679.51974658],
        [ 473.99786896,  616.76604258],
        [1193.56406436,  633.13819242],
        [1061.85978184,  687.95211239],
        [ 661.63134724,  643.72322231],
        [1528.94564339,  651.4892095 ],
        [2689.27796856,  659.18163087],
        [ 866.16084759,  662.74732973],
        [2930.88729498,  697.39172817],
        [1266.62535951,  690.99821093],
        [3080.95695664,  733.19182452],
        [ 529.6053704 ,  765.09683643],
        [3307.42741699,  716.20437553],
        [2085.85814729,  716.10017396],
        [2187.09994299,  755.90492479],
        [2320.76165554,  726.38371399],
        [1905.01657339,  838.43350785],
        [2484.82731279,  777.64246262],
        [ 418.32617306,  766.07051019],
        [3633.36890205,  756.72266874],
        [ 824.8587939 ,  814.22729293],
        [2794.01047559,  825.48578811],
        [2204.0397467 ,  859.81122307],
        [3473.09790747,  817.30841121],
        [ 719.65126899,  838.7064196 ],
        [3083.35169926,  831.79085476],
        [1997.7917601 ,  832.8057864 ],
        [ 442.32780376,  891.21653578],
        [3227.31903278,  849.69312208],
        [1690.21995344,  858.05472291],
        [ 572.76902606,  881.18063205],
        [3610.5046344 ,  913.68036701],
        [ 654.07586193,  970.11746237],
        [1300.91382599,  917.78714846],
        [2408.25834934,  948.26088378],
        [2691.99076029,  926.51614959],
        [3153.07029954,  993.98986988],
        [3723.8305455 ,  946.54963499],
        [ 856.70459797,  945.84226918],
        [1825.58879078,  982.33498108],
        [1448.2636121 , 1024.8612004 ],
        [2555.94418306,  966.10614485],
        [3606.69796262, 1022.3534336 ],
        [3312.32592174, 1012.43389038],
        [ 130.66692915,  998.99364676],
        [ 449.19798861,  995.63795026],
        [ 994.6081674 , 1033.68612892],
        [1658.23442566, 1089.07278372],
        [1272.65257329, 1069.30184632],
        [1509.86451065, 1091.74357048],
        [1943.69147838, 1099.65836498],

In [47]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [48]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [49]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,837.315725,221.725623,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,1141.828751,192.733556,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,3342.584570,177.636883,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,1288.430135,233.311136,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,1466.816616,223.738010,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
43016,3754.404280,3819.852911,00461@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43017,188.069955,3823.475202,00462@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43018,1627.363095,3861.655478,00463@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43019,1521.787563,3909.883205,00464@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
43020,3565.164247,3905.844153,00465@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [50]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [51]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [52]:
nms_config

(0.5, 0.6)

In [53]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [54]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 638
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3466
Number of Particles: 607
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 666
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3248
Number of Particles: 444
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3268
Number of Particles: 444
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3416
Number of Particles: 604
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3043
Number of Particles: 462
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3370
Number of Particles: 487
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3423
Number of Particles: 632
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3489
Number of Particles: 640
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3307
Number of Particles: 604
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3444
Number of Particles: 520
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3459
Number of Particles: 599
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3403
Number of Particles: 501
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 666
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3476
Number of Particles: 600
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3471
Number of Particles: 570
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3159
Number of Particles: 578
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3145
Number of Particles: 544
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 616
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 627
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3460
Number of Particles: 663
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3341
Number of Particles: 644
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3425
Number of Particles: 730
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 648
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3477
Number of Particles: 642
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3459
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3478
Number of Particles: 667
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 670
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 587
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 641
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3460
Number of Particles: 684
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3470
Number of Particles: 620
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3458
Number of Particles: 631
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3466
Number of Particles: 640
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3482
Number of Particles: 655
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 602
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3486
Number of Particles: 633
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3316
Number of Particles: 588
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3442
Number of Particles: 651
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2891
Number of Particles: 563
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3461
Number of Particles: 669
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 605
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3207
Number of Particles: 446
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3031
Number of Particles: 496
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3231
Number of Particles: 471
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3181
Number of Particles: 469
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3396
Number of Particles: 564
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3446
Number of Particles: 638
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3394
Number of Particles: 601
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3452
Number of Particles: 606
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 584
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3394
Number of Particles: 539
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3446
Number of Particles: 545
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3437
Number of Particles: 548
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3192
Number of Particles: 486
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 613
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3442
Number of Particles: 695
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3341
Number of Particles: 701
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3460
Number of Particles: 674
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3232
Number of Particles: 476
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3374
Number of Particles: 507
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3216
Number of Particles: 469
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3135
Number of Particles: 479
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3179
Number of Particles: 476
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3165
Number of Particles: 446
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3296
Number of Particles: 467
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3388
Number of Particles: 502
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3304
Number of Particles: 484
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3342
Number of Particles: 517
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3329
Number of Particles: 527
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 2893
Number of Particles: 512
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3385
Number of Particles: 503
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3380
Number of Particles: 484
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3314
Number of Particles: 464
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3441
Number of Particles: 530
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3269
Number of Particles: 468
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3345
Number of Particles: 521
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3377
Number of Particles: 448
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3251
Number of Particles: 457
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3324
Number of Particles: 488
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3251
Number of Particles: 531
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3226
Number of Particles: 499
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3345
Number of Particles: 546

In [55]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [56]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [57]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,2300.8,3760.8,00000@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
1,2799.2,3098.2,00001@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
2,1137.6,1786.4,00002@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
3,3043.0,430.0,00003@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
4,432.0,1867.0,00004@Falcon_2012_06_12-15_43_48_0.mrc,Falcon_2012_06_12-15_43_48_0.mrc
...,...,...,...,...
47595,2395.0,1024.0,00541@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
47596,2815.0,2304.0,00542@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
47597,3455.0,1867.0,00543@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
47598,3071.0,1983.0,00544@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc
47599,3694.0,1101.0,00545@Falcon_2012_06_13-10_27_05_0.mrc,Falcon_2012_06_13-10_27_05_0.mrc

In [58]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')